### ISSUE TITLE
sole-no generates a ~& %dy-made-dial-abort

### ISSUE THREAD

**Issue by galenwp** [urbit/arvo#101]
Running `+code` on a fake `~zod`:

```
%dy-made-dial-abort
> +code
wisnyx-sitnev-podwen-matzod
```

Just sorta confusing.

**Comment by juped** [comment]
`+code` is fine, but there's one of those stray debug printfs when `sole-no` is used

**Comment by ohAitch** [comment]
Well, not stray exactly, sole-no means essentially `!!`, and is intended for "this line of input is invalid, try something else to proceed".

**Comment by ohAitch** [comment]
Merged I think?
