### ISSUE TITLE
Hall crashes on resubscribe on the livenet

### ISSUE THREAD

**Issue by eglaysher** [urbit/arvo#1022]
In my scrollback, I discovered this on my planet:

```
; ~zod not responding still trying
; ~zod is ok
; ~zod not responding still trying
~ponnys-podfer[hall]: failed (re)subscribe to ~zod on
                      /circle/mino/config-l/group-l/grams/1.085
               attached: stack trace
; ~zod is ok
~ponnys-podfer[hall]: failed (re)subscribe to ~zod on
                      /circle/mino/config-l/group-l/grams/1.085
               attached: stack trace
```

and then when looking at one of the crash stacks:

```
  0v1.3n3u5.ff0ld.pmsdu.em9ht.1mdvo at ~2019.1.20..23.53.56..ad6f
  ~ponnys-podfer
  to :
[hall]: 
failed (re)subscribe to ~zod on /circle/mino/config-l/group-l/grams/1.085
= stack trace
/~zod/home/0/app/hall/hoon:<[2.998 3].[3.010 38]>
/~zod/home/0/app/hall/hoon:<[2.999 3].[3.010 38]>
/~zod/home/0/app/hall/hoon:<[3.000 3].[3.010 38]>
/~zod/home/0/app/hall/hoon:<[3.001 3].[3.010 38]>
/~zod/home/0/app/hall/hoon:<[3.001 27].[3.001 49]>
/~zod/home/0/app/hall/hoon:<[3.001 46].[3.001 48]>
mack
```

**Comment by Fang-** [comment]
The stack trace is saying "permission denied", which is a valid reason to deny (re)subscribing. Looks like @ixv did ops on this channel, which makes this not-an-issue.

(The stack trace should be more verbose about this, maybe, but last time I tried `~|` didn't actually make it across to the other ship?)

**Comment by ixv** [comment]
Yes, I deleted the channel and recreated it with open permissions so that it can be federated. You should be able to rejoin. I re-sent invites to everyone from their star so you can join in landscape, or if you want to do it from talk please join on your star.
