### ISSUE TITLE
failed (re)subscribe

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/arvo#1048]
I booted my planet after the Jan 31 breach (`urbit 0.7.1`) and tried (from the CLI):
```
;join ~wanzod/urbit-help
```
and got:
```
~dirwex-dosrev[hall]: failed (re)subscribe to ~wanzod on
                      /circle/urbit-help/config-l/group-l/grams/~2019.2.1..19.46
                      .44..3a19
               attached: stack trace
```

**Comment by ohAitch** [comment]
Can you post the stack trace?

**Comment by ohAitch** [comment]
I think a single ';' expands the most recent message? ;help might have more
info

**Comment by Fang-** [comment]
That makes sense, urbit-help doesn't exist on ~wanzod this era. Hall should maybe try a little bit harder to explain. Try ~dopzod/urbit-help instead!

(Though, ~zod is down for [surgery](https://twitter.com/zodisok/status/1091907488616574977) right now, so you might not be able to reach it...)
