### ISSUE TITLE
Immediate error upon re-keying star

### ISSUE THREAD

**Issue by urcades** [urbit/arvo#1102]
The following error occurs on bootup as I attempt to restart this star:

https://gist.github.com/urcades/cfe1439265858ea809540a4ddca552a6

**Comment by urcades** [comment]
Interestingly, when I tried making a new folder in the console to place this pier, I received the following warning on my ec2 instance:

`mkdir: cannot create directory ‘temp2’: No space left on device`

**Comment by joemfb** [comment]
That makes sense, the error message points to a failed disk write in the snapshotting system. `~sabbus` booted successfully, so you should be fine once you clear some space on that disk.

**Comment by urcades** [comment]
Gotcha! So there has been no breaking error that'd sink the ship? That's a relief 👍

**Comment by joemfb** [comment]
That's right, you should be able to start that ship back up (`urbit sabbus/`) once you have free space on disk. It will replay some events first, since the most recent snapshot attempt failed.
