### ISSUE TITLE
Udon treats *this* as <strong> instead of <em>

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#1149]
Expected behavior is what you find on Github and most other places that support markdown-style formatting, where `<strong>` and `<em>` are distinguished by the amount of formatting characters around a string, rather than distinguishing between `*` and `_`. The fact that udon deviates from that is confusing and frustrating.

In other words:

Current:
`_this_` --> _this_
`*this*` --> **this**

Expected/desired:
`*this*, _this_` --> *this*
`**this**, __this__` --> **this**

**Comment by ohAitch** [comment]
Udon is not markdown, and is intentionally trying to be simpler in a number
of incompatible ways. (In this case, commonmark-spec parsing of nested
***foo** bar* is admittedly pretty hairy; but I generally agree that udon
should never have been introduced and we should have stuck with real .md)

**Comment by rmariani** [comment]
I also perceived this to be an intentional simplification

**Comment by jtobin** [comment]
Markup in Keybase chat behaves similarly.  I dig it.

**Comment by jtobin** [comment]
@Fang- Want to do anything with this one, i.e. propose a change more formally?  Otherwise my closing finger is getting itchy..

**Comment by Fang-** [comment]
Seems like most others are fine with the way things are now. We can reopen if it comes up again.
