### ISSUE TITLE
Changes to /sys files not autoloading on release candidate

### ISSUE THREAD

**Issue by jtobin** [urbit/arvo#1199]
Making changes to `sys/zuse.hoon`, `sys/vane/*`, or presumably `sys/hoon.hoon` on a mounted desk does not prompt the expected autoload.

Occurring on `v0.8.0.rc.2` vere (i.e. urbit/urbit@2a9808ea995bcf4b4a97f44245ba3fe50cea1b4a) with `v0.8.0.rc.1` arvo (i.e. 2f6f6c142b9f4309673cf1b00fb0c98c634263ea).

### To reproduce

Ensure you have [Nix](https://nixos.org/nix/) installed (and that `~/.nix-profile/bin` has precedence on your `PATH`).

Copy and paste the following commands into your terminal:

```
mkdir sandbox
cd sandbox
git clone https://github.com/urbit/arvo.git
git clone https://github.com/urbit/urbit.git
pushd arvo
git checkout v0.8.0.rc.1
popd
cd urbit
git checkout v0.8.0.rc.2
make install
urbit -F zod -sA ../arvo -c zod
```

In urbit, mount your desk:

```
~zod:dojo> |mount %
```

In an editor, open e.g. `zod/home/sys/vane/gall.hoon` and add a few commented-out lines somewhere:

```
::
::
```

Save the file.  The changes should trigger a rebuild/reload of the vane in `:dojo`, but nothing happens.  `|autoload` should indicate that it is indeed on by default.

**Comment by philipcmonk** [comment]
This is a "cc-release" branch, right?  You need to manually run `|commit %home`.  They nuked the inotify stuff.

**Comment by jtobin** [comment]
Yep, that did it.  Closing.
