### ISSUE TITLE
Remove vestigial tap argument 

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#12]
I do not believe I've ever seen `tap:by` in any form other than `(~(tap by foo))`. Would anyone (@cgyarvin, @philipcmonk) mind if I added a `+-  all  (tap)` to `by`, `in`, `to`, and converted existing code to use it? Perhaps tap should go altogether, but that would involve (minor) mucking with jets, official deprecation, etc.

**Comment by juped** [comment]
- `gas` is append list elements to set, `tap` is append set elements to list, so I have no idea what you intend by `+-  all  (gas)`
- if you meant `+-  all  (tap)`, you would have to replace `(~(tap by s))` with, uh, `(~(all by s))`
- if you meant something about gassing, casual containers exists
- even if nobody ever uses `gas` or `tap` with anything but an empty set/list, which is pretty dubious, the argument still provides the type to use

**Comment by ohAitch** [comment]
Oops, definitely meant `(tap)` in the end there yeah. **edited**

**Comment by ohAitch** [comment]
- no, I would replace `(~(tap by a))` with `~(all by a)`, no outer "kick" parens. The motivation here is unwarranted boilerplate.
- gas is definitely used, tap is always(afaict) used without arguments so it sure isn't being provided at the _call site_. In practice tap uses `(list _?~(a !! n.a))`, which is the right type.

**Comment by juped** [comment]
OK, sure, let's replace tap while we can still cheat it in there, but only if there's no uses.

**Comment by juped** [comment]
(Do I want to know why tap is a `+-  |=`?)

**Comment by ohAitch** [comment]
I mean, "tap into accumulator" sounds maybe useful, but without is
definitely the common case; this is why I'm proposing a new name. Though I
suppose if it does never get used, tap can be considered deprecated, and
the thing renamed back to tap eventually(I recall something similar
happening with union/difference).

**Comment by juped** [comment]
I would suspect it to be used in jug or whatever, but you're the proposer, presumably you've been doing due diligence?

**Comment by ohAitch** [comment]
Performance optimization, so that you can e.g. (roll list-of-sets
|=([a=small-set b=big-accumulator] (~(tap in a) b)) without having to
re-weld every time. In practice I don't think I' ve ever seen it come up.

**Comment by juped** [comment]
Right, I'd expect it in jar/jug if anywhere. Those are pretty barebones right now, though. Anyway, isn't optimization for jets? :)

Can't kick the can to an unspecified future, though. If you *foresee* "deprecating" something, then do it now, or don't.

**Comment by ohAitch** [comment]
Idk about "been", there's a reason this is phrased as "hey everyone else,
have /you/ ever used the non-empty version?"

But I can't remember off the top of my head seeing any hoon that used it,
except a couple examples I contributed to documentation; and this has been
slightly bugging me pretty much every time I have the extra parens in a
one-liner, and I couldn't think of any usage any of those times either.

Wrt jugs, I think they currently don't /have/ tap/gas; but they should, and
that would be valid usage yes. Though I wouldn't be too worried if tap in
current form /didn't/ already exist, the definition used weld, and got
jetted if there were memory thrashing problems(which there would be from
function calls anyway).

**Comment by ohAitch** [comment]
I'd prefer to have a set timeline, so everybody gets a chance to quietly port their branches; but fair enough

**Comment by juped** [comment]
Jugs have some kind of gas. gas gasses into an accumulator too, it's just that it's the prettier (gas:in etc) when you don't, which doesn't offend your taste.

The issue is that when the incredibly informal times end, changing jetted library functions will be a lot more difficult.

**Comment by juped** [comment]
And probably involve sacrificing a kelvin.

**Comment by juped** [comment]
I think it's just bad early Hoon style, however - I see accumulator arguments that are never actually replaced in the sample in a lot of old code. If tap didn't tap into an accumulator, we'd never miss it...

**Comment by ohAitch** [comment]
I believe the official solution for strongly bound names is to come up with
new names(see: marks), which doesn't sit well with me in general but is
probably fine in this case. A kelvin would have to be sacrificed anyway if
you were to add the functionality in the first place, and make it checkable
by /?. In practice this is folded into breaches :/

Generally I feel like we are at(and started at!) far too few kelvins,
preventing good development practices. Minor version numbers are useful.

**Comment by cgyarvin** [comment]
Of course the non-empty version is there because otherwise you need to
weld.  But I would be perfectly ok with ~(all by set), etc.

We also need a ++li that's the equivalent of in and by.  This can be done
later with plenty of bikeshedding, though.

**Comment by ohAitch** [comment]
It's _there_, the question is whether it is ever used, especially in unjetted code.

**Comment by ohAitch** [comment]
Wrt `++li`, if the syntax was #16 made less heavy-handed maybe, and I agree that limo/homo should go to the constructors section, but

**Comment by juped** [comment]
cf. `(~(gas by a) b)`, which is both *there* and used, because having to `put:by` one at a time would suck. No analogous case exists for `tap` that I can think of.

Only vaguely apropos, but I seem to recall a `(map something ~)` in extant code, which should obviously be a `(set something)`.

**Comment by ohAitch** [comment]
It's in arch for performance reasons, being stripped from a (map something
value). I am not sure how justified those performance reasons actually are.

**Comment by juped** [comment]
And while we're making up heap-based container wishlists, I need to add an arm for treap join, the other internal algorithm operation besides treap split (`+-bif`) - it's in the curious position of being jetted (as a helper function) but not implemented in Hoon...

**Comment by ohAitch** [comment]
Treap join as separate from +- uni? I think it's not an arm because it's
interleaved with most of the algorithms. P

**Comment by juped** [comment]
Join is not union, it's a lower-level operation just like split is. The algorithms are naive. It's not an arm because I couldn't think of a punchy three-letter name. I should be able to given time. :)

**Comment by ohAitch** [comment]
Ah, the thing at the bottom of +-del which assumes nonintersection? +-mer
perhaps, I can see why del being defined as ?~(a ,~ |=(b/_n.a (mer (bif
b)))) would be cleaner.

**Comment by juped** [comment]
It's a matter of following the standard literature. `mer` is an alright name, if a bit aquatic...

**Comment by ohAitch** [comment]
Wait no you still need to descend nvm

**Comment by ohAitch** [comment]
*wants to comment the first loop in del a "=+(axe=(dig b) ?~(axe a a(+{axe}
$(a +{axe}.a))))" now*

**Comment by ohAitch** [comment]
(if you're cleaning up h/h anyway)

**Comment by juped** [comment]
pls no this is not an api-opaque refactoring

**Comment by ohAitch** [comment]
It is if you add it as a new name and then breach that part out, but yeah
the "cleaning" involves jets being moved to %zuse in a way I was
assuming would require a vere revision anyway.

**Comment by juped** [comment]
i said api not abi, i know one letter is just the other vertically flipped but there is a big difference!

**Comment by ohAitch** [comment]
Sure, I don't see how you'd execute the latter in a way that wouldn't allow
for the former though.

**Comment by juped** [comment]
Do you remember all the stuff you were just complaining about re: electroplating &c.?

You cannot do this stuff *en passant*, or worse, encourage Curtis to.

**Comment by cgyarvin** [comment]
We should have a new name which is argumentless tap.  tap must not change.

**Comment by juped** [comment]
*Nothing* must change "while you're there" refactoring hoon.hoon

**Comment by juped** [comment]
(well, not quite nothing, removing whitespace from the ends of lines would be cool, for instance :))

**Comment by joemfb** [comment]
This seems like a nice thing to fold into cc-release. Is your preference still a new name for argument-less `+-tap`, or could it just be changed?

**Comment by juped** [comment]
Good question. I'd say the answer is "discuss that on the thread for the actual patch" :)

**Comment by cgyarvin** [comment]
This doesn't rise to the level of an issue.  It's a potential feature of very dubious autistic value.

**Comment by ohAitch** [comment]
I appreciate the desire to be done with these, but careful API design isn't of "very dubious value", especially when concerning core language containers.

**Comment by juped** [comment]
Reopening in order to close with pointer

**Comment by juped** [comment]
Closed, discussion continues on #352
