### ISSUE TITLE
%bad-cookie

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/arvo#1210]
Got this when I booted up my ship:

[%bad-cookie 'lomnyt-doppes-dovper-racpel']
[%bad-cookie 'lomnyt-doppes-dovper-racpel']
[%bad-cookie 'lomnyt-doppes-dovper-racpel']
[%bad-cookie 'lomnyt-doppes-dovper-racpel']
[%bad-cookie 'lomnyt-doppes-dovper-racpel']
[%bad-cookie 'lomnyt-doppes-dovper-racpel']
[%bad-cookie 'lomnyt-doppes-dovper-racpel']

**Comment by Fang-** [comment]
Might be a browser session you still had open, that's sending stale cookies. These aren't harmful, but eyre should certainly not be this shouty about it.

Luckily, new eyre is on its way, and will make it into the next release. Closing this as solved by that.
