### ISSUE TITLE
+ticket appears to be broken?

### ISSUE THREAD

**Issue by zaphar** [urbit/arvo#144]
running `+ticket ~tomped` returns `blocking not care`. on real and fake ~ped.

 I've tried stars, planets, and moons and they all appear to return the same thing.

**Comment by ohAitch** [comment]
~tomped isn't a child of ~ped(until crub), like how ~doznec is a child of
~zod not ~nec. Is it failing for any ship where =(~ped (sein SHIP))?

**Comment by zaphar** [comment]
Yep I just realized the problem myself. It works for stars that are actually owned by the galaxy. False alarm sorry.
