### ISSUE TITLE
/ren/tree/body should inject a noscript link

### ISSUE THREAD

**Issue by galenwp** [urbit/arvo#149]
As per discussion here: https://news.ycombinator.com/item?id=11817867 it'd be nice to get the plain text on the page by default.

**Comment by philipcmonk** [comment]
Does anyone know if we're indexable by google right now?  If not, would this solve that?

**Comment by galenwp** [comment]
The first problem there is definitely the `robots.txt`

**Comment by juped** [comment]
https://www.google.com/?q=site:urbit.org

Yours,
r

**Comment by philipcmonk** [comment]
Did you try clicking any of the links?

**Comment by juped** [comment]
posts/constitution is present for me; I know Google search results are
nondeterministic

Yours,
r

**Comment by belisarius222** [comment]
I think this will be solved by merging the mve branch: https://github.com/urbit/arvo/tree/mve

**Comment by jtobin** [comment]
Closing as I'm guessing this is no longer relevant.
