### ISSUE TITLE
`|serve` should detect changes between branches and refresh pages

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#157]
In the same way that updating a file refreshes the page, `|server %branch` should refresh pages where the backing assets have changed.

**Comment by belisarius222** [comment]
@joemfb You mean changes between desks, right?

**Comment by joemfb** [comment]
That's right, desk not branch. But I'm not sure if this is still relevant: will static-web subscribe for updates from ford and trigger refreshes on build changes?

**Comment by ohAitch** [comment]
It was my impression that we were keeping the autoload behavior, yes

**Comment by jtobin** [comment]
> But I'm not sure if this is still relevant

Closing, as neither am I.
