### ISSUE TITLE
Bikeshedding: `++li`

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#17]
Cc @cgyarvin 
I am fond of names like `weld`, `skim`, and `skip`, and the `%~` "method call" syntax is at present too unweildy(see #16). Additionally, things like `sort`, `flop`, `scag`/`slag`, etc. have no clear analogue in trees(except perhaps qeus?), and while this doesn't matter for the principle of `|_` cores, it is a consistency of hoon/hoon interface that would be sacrificed.

Homo and limo should definitely go next to silt and milt in the constructor section, and `any~li`/`all~li` would be outright better names, but the rest are far too commonly used to move them without coming up with three-letter mnemonics that are significantly better than e.g. the average runic keyword.

**Comment by juped** [comment]
pls no change for the sake of change

**Comment by ohAitch** [comment]
This has in fact occurred to me as a change to make before, I just didn't
have any idea what to do with the calling convention, and still don't for
the names.

**Comment by juped** [comment]
Nothing must be done, this is nothing, therefore we must do it

**Comment by galenwp** [comment]
@cgyarvin please weigh in.

**Comment by cgyarvin** [comment]
Raymond is right.
