### ISSUE TITLE
Ames falls into one-way connectivity with ~doznec

### ISSUE THREAD

**Issue by philipcmonk** [urbit/arvo#170]
This era we've had a number of reports of ships being able to send to ~doznec but not hear from them.  Still don't know how to reproduce, but this just happened to ~wictuc-folrex, and it happened right as we should have been getting a clay sync.  Not sure what in the clay sync could clog the tubes, but it looks like the problem is in there.

Here's the log of ~wictuc-folrex before it stopped receiving packets from ~doznec.

```
~haclud_malfep= a network sync is incoming
-------[13.270]
~haclud_malfep= if you're curious about what they look like
~wictuc-folrex= indeed
~haclud_malfep= (very boring is what they look like)
~hidwes-matped= my feet are hardly damp at this point
~wictuc-folrex= there's also some traffic on r/urbit
-------[13.275]
~hidwes-matped= these docs are a real head trip 
; ~zod not responding still trying
; ~zod not responding still trying
~hidwes-matped= i'm getting now "~zod not responding still trying"
; ~zod is ok
; ~zod is ok
~torbyt-sogwyx= same, it'll resolve itself
; ~doznec not responding still trying
; ~doznec is ok
~hidwes-matped= lol: "zod is ok". phew.
```

**Comment by juped** [comment]
Anyone with ames fixes should come forward now

**Comment by cgyarvin** [comment]
I think this has to be my highest priority as a programmer...

**Comment by juped** [comment]
Make sure it's as a *programmer*.

**Comment by belisarius222** [comment]
@cgyarvin There's a fix for this in master, right?

**Comment by jtobin** [comment]
Closing as this one no longer appears to be relevant.

**Comment by joemfb** [comment]
The fix for this is replacing %ames, and @belisarius222 is actively working on exactly that.
