### ISSUE TITLE
Sole scroller always right-aligning is confusing

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#18]
Currently, if you type more than _termwidth_ characters, the left side of your input scrolls off the side of your prompt; and if you go back any, anything to the right of the cursor scrolls back off the right side. Would it make more sense for the current visible slice to be "sticky", with only motion to the left or right edges moving it? I know I find it confusing when I see a typo, scroll back to it, and can no longer see the five words I've entered since.

**Comment by juped** [comment]
Probably yes, this is what people expect from their text entry fields.

**Comment by galenwp** [comment]
I'd love to see this fixed.

**Comment by joemfb** [comment]
closed by #360
