### ISSUE TITLE
list/tape search (index-of)

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#185]
I've spent some time implementing index-of lists and tapes: https://gist.github.com/joemfb/d033e9205208604f53345a7ff029f6b9.

I'd like to put together a PR, but, first I have some questions about the API design. And, of course, naming ...

There are several different collection index-of use cases: 

- index of first-match
- indices of all matches
- index or indices, starting at an offset
- needle as a single element, needle as a sub-list

I don't think there's a way to contort the type system into supporting the various combinations of these use cases - separate arms will most likely be required. Here's my stab at the simplest set of arms:

- `(index-of single-element-needle haystack)`
- `(indices-of single-element-needle haystack)`
- `(index-of sublist-needle haystack)`
- `(indices-of sublist-needle haystack)`

(The last two being the primary `tape` search interface, the first two more suited for `list` search).

I think that starting at an offset is the least important use case; it's handy, but also pretty easy to `++slag` first. Alternately, each of those arms could optionally accept a 3-tuple sample, with the starting-offset as the third element. That's the approach I took in the linked gist (see `++args`).

The gist includes both KMP and brute-force search, but, per discussions on `~doznec/urbit-meta`, brute-force should be sufficient for the std-lib. The jet could have some fancy heuristics to upgrade to KMP or Boyer-Moore ...

Is this something you'd like to have in the std-lib? Which of these search patterns should be supported?

**Comment by juped** [comment]
I recommend two arms (one for first match only and one for all matches). Use subsequences, and don't bother with taking a starting offset.

**Comment by cgyarvin** [comment]
I'd like to hear Anton's opinion as well, his nitpicking skills are very strong...

**Comment by joemfb** [comment]
Those two arms are `++brut` and `++brat` in the linked gist...

Do you have a naming recommendation? I haven't noticed a singular/plural naming pattern in the std-lib...

And this would go in `hoon.hoon#2bB`, maybe right after `++lent`?

**Comment by juped** [comment]
Wherever the other list utility functions are. If you can find dumb four-letter names that evoke substrings somehow, that's the best...

**Comment by ohAitch** [comment]
Agree that after-index and single-element are redundant; and having first-only is probably worth the performance benefit. Official +1, esp if existing `?: (~(has in (sy a)) b)` are replaced with a less-egregious `?^ (find [b]~ a)`.

**Comment by joemfb** [comment]
Sorry, I don't quite follow that last part. Where are the `?: (~(has in (sy a)) b)` to be replace?

**Comment by ohAitch** [comment]
And yes, esp in a wet gate you want your types to be as straightforward as possible with a `(unit)` if an optional argument is _that_ useful. Which rule I've probably broken a couple times to normalize weird literal types(see `++parsf`), but ~canis latinus authoritatum~

**Comment by ohAitch** [comment]
Scattered throughout arvo and userspace where I've been, because this gate didn't exist(thank you btw). Of which apparently the only one that actually got deployed is `app/ask/hoon`, so I guess just that :P

**Comment by juped** [comment]
I await your patch!
