### ISSUE TITLE
`++ache` has wrong default, is identical to `++each`

### ISSUE THREAD

**Issue by dhaffey** [urbit/arvo#205]
```
> *(ache $a $b)
[%.y p=%a]
> *(each $a $b)
[%.y p=%a]
```

Strangely, the fork order is only lost when the mold is computed. Bunting the relevant literal directly gives the expected result:

```
> *$%({$| p/$b} {$& p/$a})
[%.n p=%b]
> *$%({$& p/$a} {$| p/$b})
[%.y p=%a]
```

Compare to a trivially-computed mold:

```
> *|-($%({$| p/$b} {$& p/$a}))
[%.y p=%a]
```

**Comment by max19** [comment]
This may be the offending section
https://github.com/urbit/arvo/blob/master/arvo/hoon.hoon#L7004-L7014

Seems that ++whip:al for tagged forks produces a multiple-if, checking for the cases in order and defaulting to the _last case_. (Bunting directly produces a twig with ++bunt:al instead)

**Comment by cgyarvin** [comment]
Yup.  I'd been meaning to look into this...

**Comment by belisarius222** [comment]
`++ache` no longer exists, so this is irrelevant.

**Comment by ohAitch** [comment]
Forks having no defined order? That is definitely still an issue, though
@cgyarvin may have fixed it in the new defaulting code
