### ISSUE TITLE
Can impersonate other ships in talk.

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#208]
%Talk can be made to send messages using %poke moves. Problem is, I can poke someone else's %talk to have them send the message for me. (At least, that's what I figure is happening here.)

Example:

```
[ost %poke /repeat/1/shipname/stationname [~zod %talk] (said our somestation %talk now eny [%leaf "i am fake ~zod"]~)]
```

Results in this line in the station the message was sent to:

```
          ~zod+ i am fake ~zod
```

In the example, `~zod` can be changed to any other ship name, and it will "impersonate" that instead.

**Comment by cgyarvin** [comment]
That's what comes from our early-Internet ethos!  Definitely must fix...

**Comment by ohAitch** [comment]
I believe this is what ["XX security"](https://github.com/urbit/arvo/blob/ab73f36/app/talk.hoon#L1548) is referring to: the problem is not pokes being accepted per se, but the author ship information being overridden to be the host. For usage by comets presumably?

**Comment by joemfb** [comment]
My "fix" in #221 was rolled back (since it broke everything). Should this be reopened?

**Comment by juped** [comment]
Sure.

**Comment by ohAitch** [comment]
Presumably this is what ++team is for, and the line can be changed to

  =.  her  ?:((team our.hid her) our.hid her)

This does conflict with the idea of using jael to issue web-yachts though.

**Comment by galenwp** [comment]
Wait, did this get fixed?

**Comment by cgyarvin** [comment]
No, the bug is still live -- just checked.
