### ISSUE TITLE
Composing @-messages of more than 64 characters in talk

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#210]
Currently, when composing a message starting with `@` and typing past the 64 character limit, the new line gets created with `•`, causing anything past it to not be recognized as an `@`-message.

Ideally, you'd want any input starting with `@` to be automatically split using `•@` instead of just `•`.

**Comment by Fang-** [comment]
Has been fixed in #211, this issue can be closed.

**Comment by philipcmonk** [comment]
Thanks!
