### ISSUE TITLE
|Start-ing app with bogus core breaks app permanently.

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#219]
Consider the following Hoon program, saved as `app/testapp.hoon`:

```
|_  {bowl}
++  poke-noun
  |=  a/*
  ^-  {(list move) _+>.$}
  ~&  [%poked-with a]
  [~ +>.$]
--
```

Doing `|start %testapp` in dojo activates the app, but also gives the message: `%testapp: bogus core`. This keeps the app from functioning properly, makes sense.

However, fixing it (by doing `|_  {bowl state/$~}` instead), does not restore functionality to the app. `|start` will tell you it is already running, and `|unlink`ing and `|link`ing doesn't fix it either.

Curiously, if the initial error was a `find` error (ie `a` had been renamed to `b`, and the core was not "malformed"), then fixing it does allow the app to run as expected.

**Comment by ohAitch** [comment]
"bogus core" appears not to leave the app in a state of "non-functional,
waiting for first useful version" as ford errors do. Thank you for the bug!

**Comment by Fang-** [comment]
This may be the same issue as urbit/urbit#296.
