### ISSUE TITLE
Marks are immutable

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#230]
If you try to mutate them, horrible things(read: stack traces and misbehavior with no user-visible link to the mutation being the problem) happen because arvo expects this invariant but does not maintain it. See: the issues when `.plan` had a `path` changed to `@t`, `:talk`'s behavior when a new `speech` type is added.

This is a tracking issue, various solutions have been proposed(integrity checking that on failure blocks on further clay revisions, passing "created-on" beaks around with marks everywhere) but further design is necessary.

**Comment by galenwp** [comment]
This could be a good fora discussion.

**Comment by belisarius222** [comment]
Ford heuristically adds a dependency on the whole /mar directory for $core silks, which I think mitigates this issue somewhat, but it's not a very principled solution, and I don't think it's a full solution.

**Comment by belisarius222** [comment]
A fuller explanation of the issue and its deleterious results would be helpful here.

**Comment by jtobin** [comment]
> A fuller explanation of the issue and its deleterious effects would be helpful here.

Closing this one, absent that.

**Comment by ohAitch** [comment]
(I'm assuming the fora discussion didn't happen?)

Fuller explanation:
- suppose you have a mark `mar/my-mark/hoon`,
```
|_  [@ @]
++  grab  |%
          +=  noun  [@ @]
--        --
```
- you write a file, `*web/test/my-mark [1 1]`
- you decide your mark type has not reached its final form! You edit it slightly,
```
|_  [@ @ @]
++  grab  |%
          +=  noun  [@ @ @]
--        --
```
- various problems occur in clay, ford, on your moons, and so on

I do not have an exhaustive list of the latter, but here's a list of urbit operations _some_ of which I would expect to break in such a scenario
- saving a file in the new format `*web/test/my-mark [1 1 1]`. saving any unrelated file to the same desk
- loading the file via ford for use in an app
- copying a file in the new format. copying a file in the old format
- viewing the files from the web / syncing it to unix, if it has a grow++mime. running mark translations on it in general
- copying the file from a different ship. syncing the containing desk to a different ship. acessing any file from a different ship to which you have attempted to sync the containing desk
- using talk or dojo on an affected ship, which poses no issue, because the number of stack traces printed per second remains less than one
