### ISSUE TITLE
Changing core and getting prep mismatch deletes state contents

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#231]
If I change my state from, say, `{bowl a/@}` to `{bowl a/@ b/@}`, gall sends a `prep mismatch` message. In addition to that, the current state data gets wiped.

Reproduction: Poke `examples/sum.hoon` to build up a sum. Change its state as described above. Poke it again to check the sum, you'll notice it has reset.

**Comment by galenwp** [comment]
I believe this was just fixed.  @cgyarvin, correct?

**Comment by cgyarvin** [comment]
Correct.
