### ISSUE TITLE
Clay off by one (?)

### ISSUE THREAD

**Issue by juped** [urbit/arvo#24]
This is a strange one, and probably difficult to reproduce. The short of it is that I got a weird sync that clipped the last character off every file in clay. Email thread:

https://groups.google.com/d/msg/urbit-dev/BY8ePTgkulw/5EW0yB64IwAJ

**Comment by ohAitch** [comment]
This sounds related to lore not knowing what to do with trailing newlines

**Comment by juped** [comment]
Curtis thought so too, but I don't see how it could possibly be related. It'd break on zod.

**Comment by juped** [comment]
Allegedly fixed, though I can't reproduce it either way

**Comment by philipcmonk** [comment]
I had a reproduction case, then I fixed the bug, and that case at least was
fixed.
