### ISSUE TITLE
nest:wa doesn't have a "crash for more specific error messages" mode

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#244]
Which makes it difficult to informatively check things in an efficient manner.

**Comment by belisarius222** [comment]
This needs more explanation.

**Comment by jtobin** [comment]
Closing per above comment.

**Comment by ohAitch** [comment]
From memory, correct me if I'm wrong / out of date
- `nest:ut` is the compiler "are these two types compatible" gate, and takes three arguments(one in the `|_` "this" slot): the desired type, the maybe-compatible type being checked, and a "crash if there's an error" bit. Setting this bit enables error reporting more specific than "these two types aren't compatible"(I believe it prints _which_ parts of the types aren't compatible), at the cost of, well, doing that via a nock crash, which you don't want if you _can_ handle a "no they don't nest" result. (A possible solution here is to just change the nest signature from `?` to `(unit error)`, I forget if there's useful information anywhere on the stack \~other\~ than the immediate crash site.) In the compiler nest is mostly called in asserts so this works out fine.
- `nest:wa` is the cached compiler "do they nest:ut" gate, used iirc primarily by arvo.hoon and gall. It does _not_ support the "crash on mismatch" flag, and always sets it to `|`, thus never reporting error messages. I'm guessing it's used in a `?>` somewhere anyway, where setting that flag would be desirable.
- The task is plausibly a 15-minute "add argument to nest:wa, have it `|` in all current callers, if nest is cached then it succeeded so ignore the argument, otherwise pass it down"; given I filed an issue instead of doing so there are probably jets involved or sth 🤷‍♂ 
- Alternately `wa` might store _failed_ nests, in which case it would be prudent to always call `nest:ut &` under `mule` from `nest:wa`; which was impractical in 2016 but I think costs a lot less perf nowadays.
