### ISSUE TITLE
key:by breaks set invariant

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#266]
`++key` in `by` should use `put:in` instead of trying to be clever with preserving structure.

```
~pittyp-datfyn# ~(key by (my [/a 1] [/b 2] [/c 3] ~))  {[%c ~] [%a ~] [%b ~]}
~pittyp-datfyn# (sy /a /b /c ~)  {[%a ~] [%c ~] [%b ~]}
~pittyp-datfyn= one of these things is not like the other
~pittyp-datfyn# (~(put in ~(key by (my [/a 1] [/b 2] [/c 3] ~))) /a)  {[%a ~] [%c ~] [%a ~] [%b ~]}
~pittyp-datfyn# (~(has in ~(key by (my [/a 1] [/b 2] [/c 3] ~))) /a)  %.n
```

**Comment by joemfb** [comment]
It's worth noting that `++apt` doesn't catch this. The right branch noun-order conditions* look suspicious to me:

```
?&((vor n.a n.r.a) (hor n.a n.r.a) $(a r.a))
```

**Comment by cgyarvin** [comment]
I'm not sure what seems suspicious to you?  n must be above l and r
vertically, between n and r horizontally?

**Comment by joemfb** [comment]
I didn't realize "h-order" meant "horizontal" -- I just mentioned the only part of `++apt` that looked (maybe) off ...

Am I correct in assuming that `++apt` should only produce `&` for valid sets? It works correctly here:

```
> (apt (sy 1 3 2 ~))
%.y
> (apt [1 [2 ~ ~] [3 ~ ~]])
%.n
```

But not here:

```
> (apt (sy /a /b /c ~))
%.y
> (apt ~(key by (my [/a 1] [/b 2] [/c 3] ~)))
%.y
```

**Comment by cgyarvin** [comment]
Are you sure that isn't just a coincidence? :-)

**Comment by joemfb** [comment]
I'm not sure what that means -- as distinct from a bug ;)

Is `++apt` just roughly documentary, or should it have the same perspective as `+-put:in`?

```
> ({n/* l/* r/*} (sy /a /b /c ~))
[n=[99 0] l=[[97 0] 0 0] r=[[98 0] 0 0]]
```

`(apt (sy /a /b /c ~))` reduces to the following comparisons:

```
(vor [99 0] [97 0])
(hor [97 0] [99 0])
(vor [99 0] [98 0])
(hor [99 0] [98 0])
```

```
> ({n/* l/* r/*} ~(key by (my [/a 1] [/b 2] [/c 3] ~)))
[n=[99 0] l=0 r=[[98 0] [[97 0] 0 0] 0]]
```

`(apt ~(key by (my [/a 1] [/b 2] [/c 3] ~)))` reduces to:

```
(vor [99 0] [98 0])
(hor [99 0] [98 0])
(vor [98 0] [97 0])
(hor [97 0] [98 0])
```

**Comment by cgyarvin** [comment]
It should certainly have the same perspective!  Let me stop my children from screaming at me and get to a computer...

**Comment by max19** [comment]
`++apt` does not check h-order recursively, therefore doesn't detect all faulty sets. In-order traversal is warranted, probably.

**Comment by joemfb** [comment]
I see that the right branch of the `+-key:by` example is a valid set:

```
> r:({n/* l/* r/*} ~(key by (my [/a 1] [/b 2] [/c 3] ~)))
[[98 0] [[97 0] 0 0] 0]
> `*`(sy /a /b ~)
[[98 0] [[97 0] 0 0] 0]
```

Is the only solution to compare `n` to every node of `l` and `r`, for every `n`?

**Comment by ohAitch** [comment]
Ordering is definitely transitive, if that's a reasonable way to interpret
your question

**Comment by cgyarvin** [comment]
Hm?  h-order is a total order, so

?&  ?~(l.a & ?&((vor n.a n.l.a) (hor n.l.a n.a) $(a l.a)))

      ?~(r.a & ?&((vor n.a n.r.a) (hor n.a n.r.a) $(a r.a)))

==

will also check the ordering for l.a and r.a -- it is an in-order
traversal.  Is there something obvious and stupid my aged brain is missing?

**Comment by max19** [comment]
If `(hor n.l.r.a n.a)`, which shouldn't be the case, that algorithm won't find it.
It will only check `(hor n.a n.r.a)` and `(hor n.l.r.a n.r.a)`... will not prove that every single item in l-subtree is hor n, nor will it prove that n is hor every single item in r-subtree.

I think `+-tap:in` produces the items in (reverse) h-order, so you could `++reel` over that and check ordering that way...

**Comment by ohAitch** [comment]
Won't $(a r.a) check (hor n.l.a n.a)?

**Comment by cgyarvin** [comment]
Ah right.  Thanks Max.  I think the answer is that ++apt is purely
documentary.  :-)

BUT - it shouldn't be, because we send sets and maps over the network.  I
shouldn't have to worry in %jael that someone is practicing some kind of
hanky-panky by sending me an invalid will map.

The correct answer is that the gate (map foo) should actually work
correctly as a mold -- it should cast its product to the span it currently
generates, but if you call ((map foo) bar), it should either normalize bar
to a correct map of foos by applying the map invariant, or (at the very
least, and probably it should be the very least) crash if the map is
malformed.  I can't say the failure to do this is a security hole, but I
can't say it isn't a security hole either, if you know what I mean.

Anyone want to send a patch?

**Comment by joemfb** [comment]
I've opened a PR to fix `++apt`. I suspect that `++ept` has the same problem, but I'm having trouble generating an invalid map to prove it. Any tips?

**Comment by ohAitch** [comment]
Any invalid set is also an invalid map?

**Comment by joemfb** [comment]
I don't follow -- a valid set is also an invalid map:

(there's probably some noun that's both a valid set and a valid map, but I wouldn't know how to find it)

```
> (apt (sy /a /b /c ~))
%.y
> (ept (sy /a /b /c ~))
%.n
```

**Comment by ohAitch** [comment]
Oh huh, they have different v-order? I thought the whole point of hor
trickiness was so that maps were sets.

**Comment by cgyarvin** [comment]
Maps are ordered on p.n, not on n.

**Comment by ohAitch** [comment]
I can see how that would cause this error, but either hor should be gor or
sets should also have special vor handling. Right now (sy foo) and (my foo)
create incompatible datastructures that(intentionally?) look the same when
pretty-printed, which is the worst of both worlds.

**Comment by ohAitch** [comment]
Anyway, try [/f ~ /b [/d ~ ~] ~] for a "crossover" invalid map

> (~(has by `(tree (pair term $~))`[/f [/d ~ ~] [/b ~ ~]]) %d)
%.y
> (~(has by `(tree (pair term $~))`[/f ~ [/b [/d ~ ~] ~]]) %d)
%.n
> (ept [/f [/d ~ ~] [/b ~ ~]])
%.y
> (ept [/f ~ [/b [/d ~ ~] ~]])
%.y

**Comment by joemfb** [comment]
Perfect! The update in #275 catches that one.
