### ISSUE TITLE
Automatic conversion in &examples-cord doesn't work.

### ISSUE THREAD

**Issue by ponnys-podfer** [urbit/arvo#271]
In the [documentation for Marks](http://urbit.org/~~/docs/arvo/marks/), the user is asked to put this in `/mar/examples/cord.hoon`:

```
/?  314
|_  cod/@t
++  grab
  |%
  ++  atom  |=(arg/@ `@t`(scot %ud arg))
  --
++  grow
  |%
  ++  md  cod
  --
--
```

For cases where &atom is supplied directly, this works:

```
> &examples-cord &atom 9
'9'
```

However, the next line doesn't print '57' as the docs say it will, but results in a build error:

```
> &examples-cord &atom &examples-cord &atom 9
ford: no link: [%examples-cord %atom]
ford: casting %examples-cord to %atom
ford: cast %atom
```

Unsure if the docs are wrong or arvo is wrong; there's no explicit atom in `++grow`, but I'm not sure if there's supposed to be.

**Comment by ohAitch** [comment]
You would definitely need a ++grow ++atom (or a corresponding grab in
mar/atom) if you want the conversion to work.

**Comment by belisarius222** [comment]
This is really a documentation issue, it would appear.
