### ISSUE TITLE
proposal: tape-join gate

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#273]
I'd like to add a gate for joining tapes to the standard library. It's a fairly common operation, easily available in the other languages.

Here's an example that does what is says on the tin:

```
=join |=  {a/tape b/(list tape)}
^-  tape
?~  b  ~
%+  weld  i.b
?~  t.b  ~
(weld a $(b t.b))
```

`(join " - " ~["foo" "bar" "baz"])` produces `"foo - bar - baz"`.

Is it worth using a wet gate here? It seems like joining a collection-of-collections is generically useful.

```
=join |*  {a/(list) b/(list (list))}
=.  a  `_?>(?=(^ b) i.b)`a
|-  ^+  a
?~  b  ~
%+  weld  i.b
?~  t.b  ~
(weld a $(b t.b))
```

(Callers then have to supply the cast: `(join " - " (limo ~["foo" "bar" "baz"]))`)

**Comment by cgyarvin** [comment]
This is good (though maybe just for tapes, not sure about the generic), but...

What would be even more cool is a ++by-style two letter door for tapes.  The string handling code is *really* old and ad hoc...  a much more complex proposal, I understand!

**Comment by joemfb** [comment]
I don't know of many generic, tape-specific gates -- are you suggesting that new ones should be added? Any recommendations for how `++join` would work in such a door?

Also, would this be separate from the oft-proposed list engined (`++of`)? I started working on that for my own amusement, just folding Section 2bB into a door.

**Comment by belisarius222** [comment]
Looks like `++zing` works for this, at least in Hoon %143. Closing.

**Comment by ohAitch** [comment]
This is "join with separator", not plain unspaced concatenation.

**Comment by jtobin** [comment]
Closing this one as it doesn't seem to have gone anywhere.

**Comment by joemfb** [comment]
I've written several versions of this in several places, will probably just PR a generic stdlib implementation at some point. The issue certainly doesn't need to be open (we'd drown in issues for stdlib proposals ...)
