### ISSUE TITLE
galaxy-name.domain.tld confuses %eyre

### ISSUE THREAD

**Issue by philipcmonk** [urbit/arvo#281]
My development server is DNS'd to dev.pcmonk.me, and it's got ~wicdev-wisryt running on port 8080.  If you visit it through the web browser, it claims to be ~dev.  I haven't tried using other subdomains.

**Comment by philipcmonk** [comment]
I should note that I can still log in correctly if I change the autofilled ~dev to ~wicdev-wisryt.

**Comment by ohAitch** [comment]
Is it actually proxying to ~dev, perchance? I would guess that to be the
problem, with the solution being to comment out the "if shipname.domain"
code in %eyre

**Comment by philipcmonk** [comment]
Ah yes, it looks like it is.  `|verb` shows my web requests causing a bunch of ames messages.

Perhaps the check should look specifically for shipname.urbit.org?

**Comment by joemfb** [comment]
The %ames proxying code is still in %eyre, but not (deliberately) used by anything. If this issue comes up again, we should certainly just that code.

**Comment by jtobin** [comment]
Closing per above comment.

**Comment by ohAitch** [comment]
I'm guessing it's checking for `.arvo.network` specifically nowadays, wherever that code ended up(outside of urbit I think?)

**Comment by joemfb** [comment]
Yeah, it is (in `vere/http.c`). FWIW, that proxy will no longer be enabled by default in the next-breach. We'll (maybe) reconsider once %ames is in a good place.
