### ISSUE TITLE
Floating point rounding glitch/jet mismatch

### ISSUE THREAD

**Issue by max19** [urbit/arvo#289]
```
> (sub:rs .1 (bit:rs [%f & -26 3]))
.9.9999994e-1
> (bit:rs (sub:pa:ma:rs [%f & --0 1] [%f & -26 3]))
.1
```

In `++sub:fl`, there's a shortcut that checks whether the subtrahend is less than 1/2 the ULP (unit in last place) of the minuend, and if that's the case, doesn't bother actually subtracting but rounds the minuend in a particular way to get the right result. This keeps, for example, `(sub:fl [%f & --0 1] [%f & -10.000 1])` from performing a 10000-bit shift when the answer is already clear.

But even if a subtraction passes the shortcut conditions, the difference can sometimes be one degree more precise than the minuend. In this case, "round difference to nearest ties to even" cannot simply be replaced with "round minuend to nearest ties toward zero". Although addition has a similar shortcut, this problem doesn't happen, because the result can only get _less_ precise.

In the example code, minuend's ULP is `2^-23`, and subtrahend is `0.75 * 2^-24`; the ULP of the correct, jetted result is `2^-24`.

The fix is very simple: in `++sub:fl`, replace `=+ ^= x %+ sum:si e.b (sun:si mb)` with `=+ ^= x %+ sum:si e.b (sun:si +(mb))`, making the shortcut require the subtrahend to be less than **1/4** the minuend's ULP instead; this way, no round-to-nearest subtractions will result in the difference being more precise than the minuend. Pull request to cc-release branch is in the works.

**Comment by cgyarvin** [comment]
Great catch!!!
