### ISSUE TITLE
Compiling =,(foo ..bar) emits span instead of nock

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#334]
Minimal repro
```
> =>(a=b=1 =,(a ..b))
ford: build failed ~[/g/~zod/use/dojo/~zod/inn/hand /g/~zod/use/hood/~zod/out/dojo/drum/phat/~zod/dojo /d //term/1]
```
This obviously shouldn't happen; digging in some
```
> =>(a=b=1 =,(a !=(..b)))
[1.836.020.833 25.717 0]
> _term 1.836.020.833
%atom
> _span =>(a=b=1 =,(a !=(..b)))
#t/@ud
```

And this isn't some `!=` peculiarity, it's actually emitting `[%atom %ud ~]` as the "nock".
```
> _* =>(a=b=1 =,(a |.(..b)))
[[1.836.020.833 25.717 0] 1]
```

**Comment by max19** [comment]
This appears to be fixed in master now.

**Comment by juped** [comment]
I thought you said this was only partially fixed by #806?

**Comment by max19** [comment]
That's what I thought, but `=>(a=b=1 =,(a ..b))` works just fine now. When I was testing it wasn't, for some reason.

**Comment by juped** [comment]
Cool!
