### ISSUE TITLE
|mass dumps core

### ISSUE THREAD

**Issue by heow** [urbit/arvo#336]
When |mass is executed, even on a newly created comet, it bails and dumps core after displaying stats.

```
...
total marked: MB/60.778.316
leak 0x36f729c0 2910e359
leak 0x37596684 bf74e2e
leak 0x3874646c 2ae6ff4b
leak 0x3879368c 1ebbf8ff
leak 0x38aa0264 bf74e2e
leak 0x38b84d30 2910e359
leak 0x39bcf630 2910e359
leak 0x39dea31c 6b15c34c
leaked: B/344

bail: oops
Aborted (core dumped)
```

**Comment by cgyarvin** [comment]
That's the GC showing leaks, which basically need to be tracked down.  We
probably shouldn't crash on detecting 344 bytes of leaks on a 60MB core...
still, the more leaks you have, the harder it is to find each one.

**Comment by galenwp** [comment]
Since both `vere` and `arvo` are under pretty heavy development (compare the maintenance and master branches) this will need to get fixed eventually — but not right away.

`|mass` should definitely work, but it'll need to happen once master stabilizes.  Thanks for the report though!
