### ISSUE TITLE
Replacing /@ with a /_ argument

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#34]
There used to be three horns for "`/_`, except only for filenames of a specific odour". Now, only `/@` "by `@da`" remains, and it's used once in tree-comments; and a ford [example](http://github.com/urbit/examples/issues/13) using the defunct old meaning of "by `@ud`".

- A filter arm can be added in zuse, with `/@` officially becoming `/;  (ordered %da)  /_`. But the functionality is in ford is so that the non-matching paths are ignored as opposed to built, so:
- An optional argument can be added to `/_`, accepting an odor(or filter) with which to filter the path names.
- Alternately, "filtered `/_`" can be a separate horn altogether, but leaving it specialized to `@da` seems a bit weird.

CC @cgyarvin, sorry this is less coherent than it could be

**Comment by galenwp** [comment]
I don't think I really understand why this feature is that useful.  I mean, we don't even really use it.  I'd vote for the optional argument that accepts an odor or filter.

**Comment by ohAitch** [comment]
It's useful so that a directory with  /1.md /2.md
/unrelated.slowly-parseable-to-md /3.md  doesn't try to build the
/unrelated only to discard it later. In practice, the only place we use it
is comments, in which case you have nothing else in the directory anyway.

**Comment by galenwp** [comment]
Yeah, I liked all of these features but don't see them as *essential*.

Which option do you like best?

**Comment by ohAitch** [comment]
I like "/_  @da  ...", but that syntax might be too confusing.

**Comment by galenwp** [comment]
That's the same one I'm in favor of?

**Comment by ohAitch** [comment]
Yes, if @cgyarvin signs off on it I'll put it in.

**Comment by cgyarvin** [comment]
Signed off.
