### ISSUE TITLE
%dy-no-prompt error could be more helpful

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#340]
Should be rephrased as "dojo blocked" or sth; ideally put a "waiting, backspace to cancel" in the console prompt similarly to what happens with `hood` on pier boot.

**Comment by Fang-** [comment]
It sounds like you're describing `%dy-edit-busy`. When/how is `%dy-no-prompt` triggered? Should they both display a "waiting"/"busy" message?

**Comment by Fang-** [comment]
Duplicate of #251.
