### ISSUE TITLE
+https alters state somewhere

### ISSUE THREAD

**Issue by hoclun-rigsep** [urbit/arvo#341]
Suppose that `+http://mysite.com` works as expected, but then you do:
    
    ~zod:dojo> +https://mysite.com
    error code: 14090086
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Fair enough, but then subsequent attempts at `+http://mysite.com` (no `s`) fail with the same error.
Also, instead of handling the failed verification gracefully, you're left with `%dy-no-prompt`.

**Comment by cgyarvin** [comment]
Anton, any comments?

**Comment by ohAitch** [comment]
Can't immediately find anything in dojo or eyre that would retain hostnames at all, let alone across secure/insecure; does the problem persist if you restart the pier?

**Comment by hoclun-rigsep** [comment]
Problem persists on fresh fakezod using urbit/master and arvo/master.

**Comment by jtobin** [comment]
Can't reproduce this using various examples from the really convenient https://badssl.com.
