### ISSUE TITLE
Recent regression on master branch causes syntax errors

### ISSUE THREAD

**Issue by eglaysher** [urbit/arvo#357]
Boot a pier using current master (4c2ac929 and its pill), and attempt to apply this patch to `dojo.hoon`:

```
--- fakezod/home/app/dojo.hoon	2017-02-26 20:20:37.746006999 -0800
+++ arvo/app/dojo.hoon	2017-02-26 20:16:38.950006999 -0800
@@ -279,12 +279,10 @@
     ++  dy-amok  +>(poy ~)                              ::  terminate
     ++  dy-ford                                         ::  send work to ford
       |=  {way/wire kas/silk:^ford}
       ^+  +>+>
       ?>  ?=($~ pux)
-      ::  adding this line breaks compile on master.
-      ~&  %starting-dojo
       (he-card(poy `+>+<(pux `way)) %exec way our.hid `[he-beak kas])
     ::
     ++  dy-eyre                                         ::  send work to eyre
       |=  {way/wire usr/(unit knot) req/hiss:^eyre}
       ^+  +>+>
```

I consistently get the following syntax error:

```
syntax error: 285 25
ford: fade /~zod/home/3/app/dojo
ford: core /~zod/home/~2017.2.27..05.16.14..28ac/app/dojo
```

To confirm, line 285 is the line with the `~&` after the patch.

If you go back to an older point on the master branch and boot a pier from it (4288aab089 and its pill), the patch above compiles and puts a debugging line on each generator call. So this is a recent regression.

(Discovered this when trying to rebuild a ship with the doccords patch when applied to current master, which throw likewise impossible syntax errors.)

**Comment by juped** [comment]
Can you give a vere revision and the OS, platform, etc. to aid in my reproduction attempts?

**Comment by joemfb** [comment]
I've reproduced this on OS X, Terminal.app, bash 3:

urbit/arvo#4c2ac92947d4e4e6d499fbfad5295ce2be458178
urbit/vere#cee04c794bb596484e475a560895c516441bda31

I've seen it on other commits as well, but can't verify them right now ...

**Comment by juped** [comment]
Thanks! By the way, do you ever experience urbit/urbit#817?

**Comment by joemfb** [comment]
No, I haven't reproduced that one.

**Comment by eglaysher** [comment]
I can verify that I can reproduce using the commits @joemfb posted, though on Ubuntu 16.04 instead of OSX.

**Comment by juped** [comment]
Thanks! More to come shortly.

**Comment by juped** [comment]
This is a text diff problem - while it's being tracked down, a workaround is deleting, committing, recreating, and committing again.
