### ISSUE TITLE
Nondelivery of browser talk messages

### ISSUE THREAD

**Issue by keatondunsford** [urbit/arvo#367]
I've tested this on both newly booted fake ~zods and newly booted comets off latest Arvo maintenance running 0.4.4. Talk messages sent to my porch don't show up at all.

Reproduce by `|mount %`ing, `touch`ing a trivial test.html file, `cp`ing a boilerplate test.html file that calls a function in a test/main.js file which sends a basic talk message via urb.js to the ship's court/floor/porch depending on its clan and console.logs it. A successful message send will show up in the ship's CLI window. One that doesn't show up doesn't produce an error, though, as the message payload is still valid.

Sending works on my not-latest-Arvo fake ~fun and my not-latest-Arvo comets. Doesn't work on my planet (which is now synced to latest maintenance), a newly booted fake ~zod off maintenance or my latest-booted comets running latest maintenance.

What might be the issue? Are newly booted / synced ships on the live network losing DMs?

Edit: Sending Talk DMs from the CLI works. Should probably specify in the issue title "Talk messages sent from the browser".

GIF video attached reproducing the issue:
![reproduce](https://cloud.githubusercontent.com/assets/13459143/23829924/bd26e9f4-06b2-11e7-9a15-759fc302e8b3.gif)

**Comment by galenwp** [comment]
Can you try DMing your planet?

**Comment by galenwp** [comment]
That seems to work for me.  Can you point me to the html / js you're using?

**Comment by keatondunsford** [comment]
So somehow after sending Talk messages to my porch through the web UI, and then trying my code, my thing works on those previously not-working other ships. So I think the issue has to do with cookies or authentication or something. Still weird though.

Have a quick fix though so I'm good for now.

**Comment by galenwp** [comment]
@ohAitch might have some ideas here.  We can all talk tomorrow.

**Comment by galenwp** [comment]
Well, as far as I can tell, things are actually working as they should.  Closing for now.
