### ISSUE TITLE
Latest build — ship fails to restart

### ISSUE THREAD

**Issue by hoclun-rigsep** [urbit/arvo#376]
- Linux Mint
- urbit/arvo@35d174565f5a0301070313c33d2199737103a66a
- urbit/urbit@1d052ab7bac8517ac665dcaa27d99dc865aeb5d9

On Tue, 21 Mar 2017 13:09:24 -0700
@joemfb wrote in https://github.com/urbit/docs/pull/153#issuecomment-288202747

> Are you building from source? I just tested everything again on OS X.
> 
> - urbit/arvo@35d174565f5a0301070313c33d2199737103a66a
> - urbit/urbit@1d052ab7bac8517ac665dcaa27d99dc865aeb5d9
> 
> ```
> $ make
> $ curl -o latest.pill http://bootstrap.urbit.org/35d174565f5a0301070313c33d2199737103a66a.pill
> $ bin/urbit -FI zod -A ./arvo/ -B latest.pill -c test-zod
> ```
> 
> Once that booted:
> 
> `|mount %`, ctrl-d to quit, same command to restart.
> 
> I made a trivial change to `%/gen/hello/hoon`, copied that in, and restarted. It then was committed automatically.

I did exactly as you did on Linux Mint 18. (Almost exactly. I ran `make distclean` before `make`.)
Here is my output.

```
$ bin/urbit -FI zod zod-2017-03-21/
~
urbit 0.5-devel
urbit: home is zod-2017-03-21
loom: mapped 2048MB
boot: installed 423 jets
lite: arvo formula 651372b4
hoon-assembly
arvo-boot
lite: core 77ffbb6c
lite: final state 6fa012e6
cmd socket up
address (nil) out of loom!
loom: [0x36000000 : 0xb6000000)

bail: oops
Aborted (core dumped)
```

It also leaves behind /tmp/urbit.sock

**Comment by juped** [comment]
I will grab a Linux and try to reproduce

**Comment by ohAitch** [comment]
Is `address (nil) out of loom!` distinct from `address 0x0 out of loom!`? Because otherwise the symptoms seem very similar to what I was experiencing last Monday, which urbit/urbit@1d052ab itself was trying to address.

**Comment by cgyarvin** [comment]
Sounds like a minor difference in the C library of the distro.  Same thing
basically.

**Comment by joemfb** [comment]
You need to reuse the creation arguments *exactly* when you restart.

Otherwise:

```
$ bin/urbit -FI zod test-zod
~
urbit 0.5-devel
urbit: home is test-zod
loom: mapped 2048MB
boot: installed 423 jets
lite: arvo formula 651372b4
hoon-assembly
arvo-boot
lite: core 77ffbb6c
lite: final state 6fa012e6
cmd socket up
address 0x0 out of loom!
loom: [0x200000000 : 0x280000000)

bail: oops
^CAbort trap: 6 (core dumped)
```

**Comment by cgyarvin** [comment]
This is super weird and appears to affect even arguments that aren't used
when restarting, like -B.  Ray?

**Comment by juped** [comment]
Yes, this is the state revere left it in - there are places it strcpy()s out of null pointers if you didn't provide an option or something like that. Just use the exact same command, as the commit message states. The command line options are on the chopping block in general, but this work is incomplete.

**Comment by ohAitch** [comment]
Would it plausibly be a 5-15 minute task to allocate a persistent buffer
and copy the initial arguments there, reparsing them on every restart, or
at least checking for consistency? "Clean but broken" is probably worse
than "hack but informative error message" here

**Comment by cgyarvin** [comment]
PR submitted (ignore #924 please).

**Comment by belisarius222** [comment]
@cgyarvin this seems solved. Please close if it is.

**Comment by joemfb** [comment]
This report concerns on obsolete, interim state of the cc-release branch.
