### ISSUE TITLE
Non-deterministic Hoon type bunting

### ISSUE THREAD

**Issue by chc4** [urbit/arvo#383]
This is probably the weirdest Hoon bug I've ever hit.

```
=>  |%
++  tuple
  |*  el/(list mold)
  ?^  el
    ?~  t.el
      i.el
    {i.el $(el t.el)}
  !!
--

=/  a  (tuple (limo @ @ @ ~))
=/  b  (tuple (limo @ ~))
:~
  *a
  *b
==
```

Running the above with output `[0 0 ~]`, which is obviously not right at all. However, you get different values returned depending on spooky action at a distance.

Using `=/  a  (tuple @ @ @ ~)` will correctly give you `[[0 0 0] 0 ~]` out, and changing ++tuple to:
```
++  tuple
  |*  el/(list mold)
  =+  something=1
  ?^  el
    ?~  t.el
      i.el
    {i.el $(el t.el)}
  !!
```

with correctly give `[[0 [0 0]] 0 ~]`. Even changing the tisgar to `=>  :-  .  |%` will give you `[[0 [0 0]] 0 ~]` - *but if you have both the changes, then you get `[0 0 ~]` again.*

People mentioned in urbit-meta that this feels like a jet mug matching issue, but I can't imagine that's correct after seeing cons plus tisgar breaking when individually they work, or it working correctly without limo. It seems to work correctly if I pepper in `^~` (compile time evaluate) everywhere, so I'm leaning towards the compiler seeing `_(tuple)` as a `[%fork el [%hold ...]]` without it, and set shenanigans.

**Comment by max19** [comment]
1. Create a fresh fake `~zod` and prepare a copy of `tuple.hoon` in a separate folder.
2. Mount to `%home`.
3. Copy `tuple.hoon` to `home/gen/tuple1.hoon`. Commit and run `+tuple1`. Result should be `[0 0 ~]`.
4. Copy `tuple.hoon` to `home/gen/tuple2.hoon`. Commit and run `+tuple2`. Result should be `[[0 [0 0]] 0 ~]`.
5. Copy `tuple.hoon` to `home/gen/tuple3.hoon`. Commit and run `+tuple3`. Result should be `[0 0 ~]`. Note that `+tuple2` still returns `[[0 [0 0]] 0 ~]`, and `+tuple1` still returns `[0 0 ~]`.
6. #@%$@#?!?

**Comment by juped** [comment]
![image](https://cloud.githubusercontent.com/assets/115765/24532788/1d8e1be0-1591-11e7-9460-30548545c6af.png)

I think you must be right @chc4 - only a `%hold` in a `%set span` carrying a core (carrying `!:` traces carrying beaks?) explains this to me

**Comment by max19** [comment]
Compiler giving several creative interpretations of the same code.
```
:-  %say
|=  *
:-  %noun

=>  |%
++  tuple
  |*  el/(list mold)
  ?^  el
    ?~  t.el
      i.el
    {i.el (tuple t.el)}
  !!
--
=/  a  (tuple (limo @ @ @ ~))
=/  b  (tuple (limo @ ~))
!.
=>  |%
++  runme
  |.
  :~
    *a
    *b
  ==
--
[(runme) -.runme]
```

```
: /~zod/home/4/gen/tuple1/hoon
> +tuple1
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
> |commit %home
>=
+ /~zod/home/5/gen/tuple2/hoon
> +tuple2
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] 1 0 0] 0 1]]
> |commit %home
>=
+ /~zod/home/6/gen/tuple3/hoon
> +tuple3
[[0 0 ~] [[1 1 0 0 0] 0 1]]
> |commit %home
>=
+ /~zod/home/7/gen/tuple4/hoon
> +tuple4
[[0 0 ~] [[1 [1 0] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
> |commit %home
>=
+ /~zod/home/8/gen/tuple5/hoon
> +tuple5
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
```

**Comment by cgyarvin** [comment]
Don't take my silence as evidence that I don't find this weird!

**Comment by max19** [comment]
Mint code: in jet, `u3_noun wim = u3n_nock_an(cag, u3k(q_nef));`, in hoon, `=+ moc=(mink [u.cag q.nef] |=({* *} ~))`
When this errors (head = %2), it passes through q.nef, so gets `[[[0 [0 0]] 0 ~]`.
When this succeeds (head = %0), it replaces with constant, so gets `[0 0 ~]`. It seems to switch between erroring and succeeding randomly.

The second argument is always consistent, so it must be the first argument, the result of `burn`, which is changing in some way as to cause the evaluation to error.

**Comment by cgyarvin** [comment]
It wouldn't surprise me to see some interesting noise in burn.  But burn is
not that complicated...

**Comment by max19** [comment]
One weird thing is that currently the jet doesn't match: the hoon version produces a unit and the C version doesn't, but fixing that doesn't seem to make any difference.

**Comment by chc4** [comment]
That's normal. You're building the gate in a generator, and generators have that `|=  *` at the top which is filled by %gall with entropy and the current time. The gate has that value in the context when you build it. Also, that shouldn't affect the type-level stuff, that I know of, since we care of the type of the result of the gate.

I checked `!>(*(tuple (limo @ @ @ ~)))` and it is, indeed, a `[%fork @ [%hold ...]]`. I did some noun surgery to look into it, and it contains multitudes of complex cores, and I really don't get why (shouldn't it just have a twig? why would a hold have a core...). It looks like the non-determinism problem is at least partly due to `@` having the context of where it was defined at, which includes the entire kernel and entropy and time.

Oddly, `!>(*(tuple @ @ @ ~))` actually has a fully-evaluated type of just `{@ @ @}` sometimes, without a hold, which explains why it magically works even when they're functionally identical.

I switched my generator to a single-argument one, which doesn't have entropy/time (`|=  @t  =>  |% ...`, call with `+tuple 'a'`), and it still occasionally bunts incorrectly through spooky action...

**Comment by joemfb** [comment]
This is fixed on `release-candidate`:

```
+ /~zod/home/4/gen/tuple1/hoon
> +tuple1
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
+ /~zod/home/5/gen/tuple2/hoon
> +tuple2
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
+ /~zod/home/6/gen/tuple3/hoon
> +tuple3
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
+ /~zod/home/7/gen/tuple4/hoon
> +tuple4
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
+ /~zod/home/8/gen/tuple5/hoon
> +tuple5
[[[0 [0 0]] 0 ~] [[1 [7 [0 30] 9 2 0 1] [7 [0 14] 9 2 0 1] 1 0] 0 1]]
```
