### ISSUE TITLE
nest-fail / load-lost on recent %gall

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#388]
I've seen this myself, and seen it discussed on urbit-meta as well. Maybe %gall ++load doesn't account for recent changes? (There's no stack trace -- I'm just guessing).

**Comment by mattlevan** [comment]
```
> |load %gall
  /~mastyr-harlud/home/~2017.6.11..15.52.41..dada/arvo/ford
  <[1.418 24].[1.418 38]>
nest-fail
- want
{ { now/@da
    eny/@uvJ
    byk/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}
  }
  {dap/@tas pas/@uw $~}
  $~
}
- have
{ { now/@da
    eny/@uvJ
    bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}
  }
  {$gall $~}
  $~
}
```

**Comment by mattlevan** [comment]
Also:
```
[%vane %g /~mastyr-harlud/home/~2017.6.11..16.26.42..73c1/arvo/gall ~ligwep-hinfer]
nest-fail
%load-lost
> |reload %gall
>=
```

**Comment by cgyarvin** [comment]
Yeah, that's what you see when there's a type mismatch between the old vane
state and the new vane state.  Very unclear how people got a bad vane.  I
can't wait to reboot this network...

**Comment by ohAitch** [comment]
The former is using |load instead of |reload; |load should maybe be renamed
to |load-womb to reflect current functionality

**Comment by mattlevan** [comment]
Network reset fixed it! Very good; thanks. Glad to have a functioning planet again.
