### ISSUE TITLE
Special handling of .hoon mark should move to clay

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#39]
Second point of #38
- `%pact` shouldn't be used for the first revision anyway according to @philipcmonk
- `%bunt`, used only by `%volt`, can easily be special cased with a `++volt-silk` arm.
- `%cast` to not-mime only ever occurs on direct cages, and can be similarly wrapped with `++cast-cage`.

**Comment by philipcmonk** [comment]
That last point is unclear to me.  Can you clarify?

**Comment by ohAitch** [comment]
From clay, `++lake` is used in `%cast`(and in `%vale`, but I don't _think_ that happens in nil revision scenarios; if it does, that could also be guarded). Three of the casts are `:+  %cast  %mime`, and irrelevant here.
The other two are `[%cast -:(flop pax) $+cay]`. Each of those could be replaced with
```hoon
=+  mar=-:(flop pax)
?.   =(%hoon mar)
  [%cast mar %$ cay]
?:  &(?=(@ q.q.cay) ((sane %t) q.q.cay))
  [%$ mar [[%atom %t ~] q.q.cay]]
[%dude |.("clay: bad %hoon {<pax>}") %ride [%zpzp ~] $+!>(~)]
```

**Comment by ohAitch** [comment]
Would this be a reasonable thing to do?

**Comment by philipcmonk** [comment]
My only concern would be that we'd have two definitions of the %hoon mark
that need to be kept in sync.  Doing it in ford means it all gets treated
the same.

**Comment by ohAitch** [comment]
We currently have two definitions: mar/hoon.hoon, and the special handling in ford. The latter is what I'm proposing to move claywards; or would some of it need to stay in ford?

**Comment by philipcmonk** [comment]
Under what conditions do we use the handling in mar/hoon.hoon?

**Comment by ohAitch** [comment]
- while we don't _use_ the definition of `++grab++noun` it's definitely still checked in, which is the main factor wrt potentially confusing errors
- diffing dosen't have special ford handling; patching does but probably shouldn't.

**Comment by philipcmonk** [comment]
Is it just `++grab-noun` that should get special handling?  If so, that's small enough that it's fine to duplicate.  Otherwise, I would prefer checking out the unused definition to creating two separate *used* definitions.

**Comment by ohAitch** [comment]
Actually, %cast %hoon seems to be only used inside of ford, so that building mar/hoon/hoon doesn't depend on itself. `%bunt` is the only one that gets run without a building mar/hoon/hoon during the initialization sequence(for carriers, subs seem to be ~completely~ fine).
- The reason there's a circular dependency is that files are coerced to their marks after being fetched from clay, presumably predating caged `.^`. If I just use the scried cage as is and trust clay to preserve mark integrity, is that likely to cause any problems?
- Is there some more comprehensive test I should run than "start a carrier, start a sub, load tree", to check that the "only bunt is special-cased anywhere(i.e. in clay)" variant doesn't break anything important?

**Comment by philipcmonk** [comment]
- Yes, that shouldn't cause any problems.
- That test case should be sufficient.
