### ISSUE TITLE
Potential ++zing issue?

### ISSUE THREAD

**Issue by mattlevan** [urbit/arvo#394]
In celebration of reserving my first star, I thought I'd explore the potentially available star names. I ran these commands in `dojo`:

```
> =p (turn (gulf 0x1 0xff) |=(a/@p (turn (gulf 0x1 0xff) |=(b/@p (cat 3 a b)))))
> =q (zing p)
> (lent q)
65.025
> q
recover: dig: over
-
bail: meme

recover: top: meme
meme
leak 0x360048d4 524afbd6
leak 0x360048ec 64b98402
...
leak 0x3d421504 5da0da6b
leak 0x3d423240 f54bf9
address 0xbe440000 out of loom!
loom: [0x36000000 : 0xb6000000)

bail: oops
Aborted (core dumped)
```
What's going on here? According to the [docs here for `++zing`](http://urbit.org/docs/hoon/library/2b/), `q` should simply be a flattened list. However, when I try to run a simple `snag`, I also receive an error:
```
> (snag 0 q)
/~mastyr-harlud/home/~2017.4.17..22.17.39..3dd3/arvo/ford:<[1.211 24].[1.211 52]>
fuse-loop
ford: build failed ~[/g/~mastyr-harlud/use/dojo/~mastyr-harlud/inn/hand /g/~mastyr-harlud/use/hood/~mastyr-harlud/out/dojo/drum/phat/~mastyr-harlud/dojo /d //term/1]
```

I am new to Hoon, so hopefully this isn't a mistake on my part (it probably is!). I'll bet there's a better way to generate `p` also, rather than nesting `turn` calls.

Thanks!

**Comment by cgyarvin** [comment]
These are real issues that everyone has unfortunately learned to work around.

65535 names is a giant list, you don't really want to print that.  And cast the product of ++turn before using it.

You shouldn't have a problem with this -- the prettyprinter shouldn't head recurse on a list, for instance.  But rough spots which are easily worked around don't get enough love.

**Comment by mattlevan** [comment]
Yes, giant list: 65.025 to be exact!

I just want a handy text file, so I try:
```
> =p (turn (gulf 0x1 0xff) |=(a/@ (turn (gulf 0x1 0xff) |=(b/@ `@p`(cat 3 a b)))))
> =q `(list @p)`(zing p)
> (snag 0 q)
~marnec
> *%/web/stars/txt (turn q |=(a/@p (scot %p a)))
```
And now we wait for the spinning to cease. Casting was the trick!

Thanks Curtis.
