### ISSUE TITLE
efactor lens and ?anon pokes to not use oryx system

### ISSUE THREAD

**Issue by galenwp** [urbit/arvo#397]

**Comment by belisarius222** [comment]
@galenwp This would benefit from a more detailed description.

**Comment by galenwp** [comment]
Pretty sure this was an Anton bug filed from my keyboard. @ohAitch want to add some color here?

**Comment by ohAitch** [comment]
I think this exists on cleaner-eyre? The `urb.py` interface spins up an `auth.json` identity despite really not needing it, as do `?anon` webhook callbacks. Probably makes more sense as an eyre comment than an issue
