### ISSUE TITLE
Write a library that can translate old zuse -> new zuse

### ISSUE THREAD

**Issue by galenwp** [urbit/arvo#399]
In order to forward port all userspace code we really should have a library of some kind that exposes the old zuse arms and calls their renamed counterparts.  

You could throw a printf every time these arms are called as a way of finding old code that needs to be forward ported.

**Comment by ohAitch** [comment]
Or like, have the core be not in scope by default, and grep for anything pulling it in
(printf for something like URL parsing in an inner loop might get bothersome)

**Comment by ohAitch** [comment]
exists, `lib/old-zuse`. Used in 58 files, mostly marks and generators.
