### ISSUE TITLE
Api connectors match domains exactly

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#4]
www.googleapis.com and pubsub.googleapis.com expect the same authentication session, but eyre currently keys sessions on the full domain.

**Comment by galenwp** [comment]
Is this universally true for API connectors?  I could see subdomain.domain.com <http://subdomain.domain.com/> expecting a different authentication session in some cases.  Exceptions by domain?

**Comment by ohAitch** [comment]
The thing I started to implement, but then tabled for the purpose of
prototyping, was longest-match: a sec/ containing com/goog/hoon and
com/goog/special/hoon would match foo.goog.com and bar.goog.com with the
former and special.goog.com with the latter, each file having a
corresponding (map username tokens) in eyre.

**Comment by galenwp** [comment]
So, the idea is to actually implement that?

**Comment by ohAitch** [comment]
The ~issue~ is that some solution is necessary. The proposed is a
reasonably straightforward one, and I or @philipcmonk can go forward with
it after eyre-sec is 151ified. I remember another idea was explicitly
 linking domains' sessions, but I'm not sure what precisely that would look
like, or how much the pattern of "foo.info + api.old-foo.com” appears in
the wild.

Mainly flagging this for further discussion.

**Comment by cgyarvin** [comment]
I would just hardcode it to the second-level domain (googleapis.com).
Cases where the third level matters must be incredibly rare.

**Comment by ohAitch** [comment]
I would expect graph.facebook.com and oldapi.facebook.com to maybe be
separate auth flows, though I suppose it's a fine thing to hardcode until
we hit it.

I did have thoughts about having a ship.urbit.org http api driver, just for
Rosetta Code effect against eyre /~/auth.js, but I suppose the code would
be shared there anyway, and the right thing would be asserting that the
client identity matches the subdomain.

**Comment by cgyarvin** [comment]
"Hardcode till we hit it" sounds fine to me in this (and many other) cases.
:-)
