### ISSUE TITLE
+foo &bar ...  not recognized as valid syntax by dojo

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#401]
in e.g. `+transform &json +http://...`, I think the motivating example was `|init-auth-google &json .^(json %cx %/keys/json)`?

**Comment by Fang-** [comment]
This was actually closed in favor of #402, which contained some details that were missing here. Should've referenced. Will copy your edit over for you.

**Comment by ohAitch** [comment]
Ah, so the "+foo &eBay" was just a typoed spurios duplicate, got it
