### ISSUE TITLE
Reintroduce ren/red-quri.hoon

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#41]
```
~talsur-todres= how do i write a redirect?
--------[4.550]
~talsur-todres= (that's for fyr too)
...
          ~fyr@ could have sworn there was a ren/red-quri checked in
          ~fyr= maybe it got "cleaned" along with the docs?
```

It used to exist, probably got deleted because it was used only to point `/doc` to `/docs`, should exist again to demonstrate how to set up redirects.

**Comment by galenwp** [comment]
Do we still have `red-quri`?  I don't see it, and we don't use it.

**Comment by ohAitch** [comment]
We do, you see it in "out of options" stack traces; but we in fact don't use it, and if it's not gone on master it should be.
