### ISSUE TITLE
urbit.org/stream fails to load, syntax error

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#419]
[let me know if this should be in the urbit/urbit issues and I'll move it there]

When I navigate to https://urbit.org/stream (google chrome, ubuntu 16.04) the initial page load finishes, but no talk messages appear and the loading icon spins indefinitely.

In the JS console, I see the following messages:

```
main.js:1633 listen station
main.js:1634 (2) ["home", "~2017.8.8..23.37.00..0000", callee: function, Symbol(Symbol.iterator): function]
Symbol(Symbol.iterator): function values()__proto__: Object
VM343:1 Uncaught SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.urb.getXHRWasp ((index):40)
    at XMLHttpRequest.urb.waspLoadedXHR ((index):35)
urb.getXHRWasp @ (index):40
urb.waspLoadedXHR @ (index):35
```
Then I start seeing 504 errors coming in every minute or so, but no repeats of the error logs. Here's one of the 504s:
```
0v1.98p7i.o64rq.f2hm5.57pc2.tl4l3.js:19 GET https://urbit.org/~/on.json?0v1.98p7i.o64rq.f2hm5.57pc2.tl4l3&0v4.sbr5s.p3k…7q.8gurp&0v5.9gg1r.q4inh.baa4d.u4v09.e69fk&0vs6dtl.hjbl5.aj4ti.k2eaa.q2tle 504 ()
```

**Comment by galenwp** [comment]
I just kicked one of our caching processes, although it loaded for me before doing that.

There could be something wrong with the ship serving urbit.org.  Do you have trouble in incognito mode?

**Comment by ohAitch** [comment]
The ~/on is a red herring, that's just the maybe-update-page long poll
timing out

The syntax error looks like json got returned not wrapped in an
array/object; does the Network tab have a copy of the full response?

**Comment by ohAitch** [comment]
…and the parsing was a CloudFlare misconfiguration, fixed. Do the messages
still fail to load?

**Comment by belisarius222** [comment]
It's fixed for me when I load it now. I had closed the page, so unfortunately the Network tab from the failed load is no longer available to me.

**Comment by ohAitch** [comment]
Yeah I tracked down that particular error, it was unrelated to talk :3

**Comment by belisarius222** [comment]
:+1:
