### ISSUE TITLE
failure to reconnect bug

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#424]
When my modem loses power, my ship shows:

`; ~zod not responding still trying`
`ames: czar at zod.urbit.org: not found (a)`

This is what I'd expect.  But when the modem powers back on, my ship never attempts to find the Urbit network again.  It stays offline until I exit and restart the ship, at which point it connects as it should.

**Comment by joemfb** [comment]
what urbit version are you running? I think this may have been fixed.

**Comment by joshuareagan** [comment]
0.4.3

**Comment by joemfb** [comment]
fixed in 0.4.4: https://github.com/urbit/urbit/releases

**Comment by joshuareagan** [comment]
Oh dear.  Why is 0.4.3 still the one linked at urbit.org?

**Comment by joshuareagan** [comment]
Looks like the link to 0.4.5 is updated in the docs repo on github, but that the changes aren't reflected at urbit.org.  Who does those updates, @galenwp?

**Comment by galenwp** [comment]
Yep.  It's me.  Will deploy.  Sorry!

**Comment by galenwp** [comment]
OK, deployed.
