### ISSUE TITLE
Mast branch sinks ships on bad-softing

### ISSUE THREAD

**Issue by eglaysher** [urbit/arvo#432]
While experimenting with marks, some sort of error on my end sank my fakezod on master. urbit repeatedly spits out:

```
serf_send_replace 220 crud
pier: replace: 220
pier: (220): compute: replace
[%bad-softing 'crud']
serf_send_replace 220 crud
pier: replace: 220
pier: (220): compute: replace
[%bad-softing 'crud']
serf_send_replace 220 crud
pier: replace: 220
pier: (220): compute: replace
[%bad-softing 'crud']
```

And over and over again until I ctrl+c, which sinks the ship as if I kill the urbit/urbit-worker process, it just retries the computation.

**Comment by joemfb** [comment]
I've similarly crashed several master (cc-release) fake-zods after failed hoon.hoon resets.

**Comment by belisarius222** [comment]
Hmm, not sure exactly what this is about, but I believe the trace is coming from here:
https://github.com/urbit/arvo/blob/master/sys/vane/clay.hoon?utf8=%E2%9C%93#L3272

`%clay` is trying to call `++soft` to clam a card it received, but the card didn't nest into the kind of card `%clay` knows how to deal with. The tag on the card was `%crud`, which sure enough isn't one of the types of `++task` clay recognizes, defined in zuse.hoon here:
https://github.com/urbit/arvo/blob/master/sys/zuse.hoon?utf8=%E2%9C%93#L339

It looks like the older versions of clay didn't understand `%crud` cards either, which I found a little surprising. `%eyre` and `%dill` deal with `%crud` cards, though, and in particular `++task:able:eyre` defines a `%crud` card with an `XX rethink` comment, so ... maybe we should rethink that.

**Comment by belisarius222** [comment]
`%crud` looks like it's the card type indicating an error, so maybe some other vane errored out in response to a `%clay` request and sent back a `%crud`, which `%clay` didn't know how to handle. Another part of this I don't understand is that the only places I see `%crud` in the vane interfaces in the master branch are in their `++task` sections, not in their `++gift` sections, so it seems wrong for another vane to send a `%crud`, as opposed to knowing how to receive them. Maybe there's some generic error handler in a vane that sends a `%crud` back to whatever vane sent the request, and in this case it was `%clay`, despite `%clay` not knowing how to deal with a `%crud`.

One thing to try might be to add a debug printf for `%crud` messages in `%clay` that prints the stack trace contained in the card, then trigger this crash. @eglaysher do you remember what command you ran to get the crash?

**Comment by cgyarvin** [comment]
Yes, there are plenty of bugs in bad-event handling in master.

Fortunately, if you grab cgyarvin/remaster for arvo, and cgyarvin/retrofit
for vere, you can run the old interpreter with the latest arvo.  Pills are
on https://bootstrap.urbit.org/${commit}-maint.pill.

**Comment by joemfb** [comment]
Any vane that receives cards from unix (ie, with an entry in `+dint:is`) must be able to handle a `%crud` task. As of #900 and #907, they all can.
