### ISSUE TITLE
[remaint] Cores are syntax error in sample molds

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#434]
Found on [cgyarvin/remaint-merge](/cgyarvin/arvo/tree/remaint-merge).

Typing this into dojo works fine:

```
a/|-($@(@tas {@tas $}))
```

Trying to type this into dojo stops you when trying to type the bar in `|-`:

```
|=  a/|-($@(@tas {@tas $}))
```

Manually expanding that into something like the following still syntax-errors, on the `|%`:

```
|=  $=  a
    =<  $
    |%  ++  $  $@(@tas {@tas $})  --
```

Temporary workaround is doing:

```
=+  mol=|-($@(@tas {@tas $}))
|=  a/mol
```

**Comment by joemfb** [comment]
I finally found the relevant post: [from doccords to decorations](https://urbit.org/fora/posts/~2017.4.7..06.37.22..c960~/). The parser is unable to statically determine that your `|-` is a mold, and it's become strict about this. You can wrap your `|-` in `$;` to remove the ambiguity:

```
> %.  %foo  |=(a/$;(|-($@(@tas {@tas $}))) a)
%foo
> %.  [%foo %bar]  |=(a/$;(|-($@(@tas {@tas $}))) a)
[%foo %bar]
```

/cc #435
