### ISSUE TITLE
[remaint]  Lark in ^- is syntax error

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#435]
Found on [cgyarvin/remaint-merge](/cgyarvin/arvo/tree/remaint-merge).

This works:

```
^-  _+>
^-  (quip @ _+>)
```

These don't, they syntax error at the lark:

```
^-  +>
^-  (quip @ +>)  ::  should be nest-fail instead
```

According to ~master-morzod: "this is the whole "statically identify molds" thing, that leads to `[a=@ b=@]` instead of `{a/@ b/@}`".  
That shouldn't lead to syntax errors where you'd expect nest-fails, I feel.

**Comment by cgyarvin** [comment]
That's correct -- it's one of the few places where the difference between
old and new syntactic models is visible.

**Comment by Fang-** [comment]
I'm assuming then that turning this should-be-nest-fail "syntax error" into a nest-fail is more effort than its worth?

**Comment by ohAitch** [comment]
Aw but my ,[. .]:(each ~ @foo) constructs 3:

(To be clear, this is an argument /for/ lark molds staying illegal)

**Comment by cgyarvin** [comment]
It actually is a syntax error!  I’ll explain in a doc.

**Comment by ohAitch** [comment]
As long as non-lark wings still work, so you can namespace things
properly :P
