### ISSUE TITLE
=, tiscom causes bail: fail

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#440]
I've been seeing weird behavior when using `=,`. This appears to be a compile-time one, it occurs even when the compilation should nest-fail.

See [this](https://github.com/urbit/arvo/blob/master/mar/hall/action.hoon#L13) file for my workaround. Just uncommenting the `=,` on lines 13 or 41 causes the issue to appear, printing the following whenever you attempt to use the mark:

```
> &talk-action [%convey ~]
bail: fail
bailing out
```

**Comment by cgyarvin** [comment]
Interesting, I'll take a look.

**Comment by Fang-** [comment]
Just confirmed this is still an issue on current master.

**Comment by cgyarvin** [comment]
Yes, sorry, it’s fixed on a branch...
