### ISSUE TITLE
[remaint] Find error in ++my:nl when calling ++op:dejs-soft:format

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#444]
On the latest master commit (dbc802a9) with the latest pill (4018c1b5), triggered by [this call](https://github.com/Fang-/arvo/blob/31cd0593aa4150795d67c8688de3a3c0992c1ef0/lib/talk-json.hoon?utf8=%E2%9C%93#L379) to `++op` (`:dejs-soft:format`), I get a stack trace and the following lines:

```
%redo-match
####
-redo: dext: ref.{a/nlr({p/* q/*}) <1.dth 1.rlo 1.hru $143>}
####
-redo: dext: ref.{a/nlr({p/* q/*}) <1.dth 1.rlo 1.hru $143>}
####
-redo: dext: ref.a/nlr({p/* q/*})
####
-redo: dext: ref.a/nlr({p/* q/*})
####
-redo: dext: ref.nlr({p/* q/*})
####
-redo: dext: ref.nlr({p/* q/*})
####
-redo: dext: ref.nlr({p/* q/*})
####
-redo: dext: ref.nlr({p/* q/*})
-find.p.i.+2.a
find-fork-d
```

It seems [this call](https://github.com/urbit/arvo/blob/master/sys/zuse.hoon?utf8=%E2%9C%93#L3338) to `++my:nl` messes up.  
A temporary fix for this is to add faces (`p` and `q`) to the items in list `a` there (ie `a/(list _[p=(wonk *fel) q=(need *wit)])`), but seeing as how other existing calls to `++op` work fine, this shouldn't be necessary.  
An alternative fix is to make `++my:nl` use lark instead of `p` and `q`, but it's working with a `(pair)` so it really shouldn't need to?

To reproduce, get [Fang-/arvo/remaint-merge-talk](https://github.com/Fang-/arvo/tree/remaint-merge-talk), and then run in dojo:  

```
&talk-prize [%friend ~]
````

**Comment by Fang-** [comment]
Smallest reproduction case appears to be just this:

```
::  /gen/test-op.hoon
(op ace so):dejs-soft:format
```

```
~zod:dojo> +test-op
```

If this compiles, it'll spit out `%one-argument` `%dojo-lame`. But it won't, because it doesn't compile. (Until you apply one of the fixes above.) Seems this isn't exclusive to new talk's use after all?  
Should note that `++op` was only ever used in the old talk marks, which I haven't actually tested on remaint (since they're replaced now).

**Comment by cgyarvin** [comment]
That's better but it's still not a minimal reproduction case -- you need to
tear apart ++dejs-soft.

**Comment by Fang-** [comment]
That's true.

```
::  /gen/test-my.hoon
(my:nl *(list {@ @}))
```

Also noteworthy: with a dry gate it does compile:

```
::  /gen/test-my.hoon
%.  *(list {@ @})
::  the below is ++my:nl with its gate modified
|=  a/(list (pair))
=>  .(a ^+((le:nl a) a))
(~(gas by `(map _p.i.-.a _q.i.-.a)`~) a)
```

**Comment by cgyarvin** [comment]
Wow, I could swear I'd tested this case pretty thoroughly.  Thanks!  I'll
look into it.

**Comment by cgyarvin** [comment]
OK, brain fart -- this is "not a bug."  Anything that's a recursive type
can't be repainted.  You have to do (list (pair @ @)) or (list [p=@ q=@])).

**Comment by Fang-** [comment]
So that means `++op` is in the wrong here, and should be doing `a/(list _[p=(wonk *fel) q=(need *wit)])` or `a/(list (pair _(wonk *fel) _(need *wit))` instead? (The latter feels slightly prettier.)

**Comment by cgyarvin** [comment]
Yes, you're right.  Try it! :-)

**Comment by ohAitch** [comment]
++op is not exactly in the wrong there, we just need `malt` back.
