### ISSUE TITLE
, syntax in hoon %143

### ISSUE THREAD

**Issue by mattlevan** [urbit/arvo#450]
Experimenting with new comma syntax in a %143 dojo this evening (for those who haven't seen it: the comma toggles between the hoon parser's noun and pattern modes):
```
> `@`1
1

> `,@`1
1

> `,,@`1
nest-fail

> `[@ ^]`1
nest-fail

> `,[@ ^]`1
1

> `,,[@ ^]`1
nest-fail
```

Shouldn't casting to molds be a syntax error (such as with `` `,@`1 ``)?

**Comment by joshuareagan** [comment]
I can't replicate your first `nest-fail`:

```
> `,,,,@`1
1
```

But I can replicate and say a little about this:

```
> `,[@ ^]`1
1
```

Normally a pattern goes between the irregular cast backticks, so the `,` switches it to value mode.  That means you have a pair of molds in a cell.  When you call a tuple of gates, the first one will take the sample:

```
> ([add dec] 2 3)
5
```

It looks like when you cast with a tuple in value mode, it takes whatever is at the head as the mold to be used for type-checking.  Hence the reason you get a `nest-fail` here:

```
> `,[^ @]`1
nest-fail
```

**Comment by mattlevan** [comment]
Thanks for the explanation on the second one. That makes sense. As far as the first `nest-fail`, some update to Hoon between now and then must've fixed it. Keaton had me file this issue some time ago, I think it is now safe to close.

**Comment by ohAitch** [comment]
@cgyarvin can we *please* make , not be a toggle? This is reminding me of
when _ did both unbunt and into-pattern-mode
