### ISSUE TITLE
Dojo commands can be executed against comet during boot

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#466]
During the boot process, a ship is temporarily a comet, even if it will emerge from its chrysalis as a planet. If you manage to send it a dojo command quickly enough while it's booting, that dojo command can execute while the ship still thinks it's a comet. In practice, this is a race condition, especially in scripting contexts like urbit/fleet. For example, if you type `|mount %` quickly enough, it could mount the `%home` desk on the comet. Then when you copy in files from unix, they won't show up in a `+ls %`.

I've heard [who?][citation needed] that the cc-release boot process will fix this, at which point we should mark this issue as closed.

**Comment by joemfb** [comment]
Fixed on `release-candidate`.
