### ISSUE TITLE
Status & config notifications getting rendered twice.

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#479]
As evidenced by urbit-meta, most notably by presence notifications, federated circles seem to be sending changes twice. Curiously, subscribers are also processing (or at least relaying to clients) both these changes, despite the fix made in #475.

**Comment by galenwp** [comment]
This seems relatively high priority.

**Comment by Fang-** [comment]
Have had reports of people who *aren't* seeing double presence notifications, so my guess is there's something funky with sourcing going on. Definitely investigating further, but this luckily isn't "it's bouncing messages into infinity" levels of bad.

Hope to have this figured out sometime tonight.

**Comment by Fang-** [comment]
I just received double config notifications when I invited someone to a village on my ship. I suspect the culprit is #469's change to talk's prep having resulted in double subscriptions for people where the hall-talk subscription was never dropped in the first place. Will have to research more to confirm, but that's fairly benign and might be an easy fix.
