### ISSUE TITLE
Hall subscription woes

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#498]
_breathes out_ ...Okay.

Recent downtime (or rather, un-federation) of urbit-meta ~was~ is being caused by federation-related subscriptions being dropped. ~wanzod and ~binzod weren't listening to their parent anymore, ~samzod's parent wasn't listening to it anymore, and ~marzod had gotten completely disconnected.

Despite the fact that the developer docs never mention "for every `%peer` you make, be ready to handle a `++quit`" (which, honestly, should be drilled as soon as you learn to do subscriptions), hall implements a generic `++quit` to handle all subscriptions that don't need any special logic for re-subscribing.

```
++  quit  ::  dropped subscription
  |=  wir/wire
  ^-  (quip move _+>)
  :_  +>
  ?.  =(src.bol our.bol)  ~
  [(wire-to-peer wir) ~]
```

Note how it's ignoring the quit if it originated from a foreign ship. They may want to end our subscription for any number of reasons (we got banned, our subscription range has ended) that are totally legit. We only re-sub on locally caused quits, because those happen when gall says "you're holding up the queue, get out".

Or so I thought. Federation subscriptions don't get quit by hall manually, so they *should* only be caused by local gall. And yet the federation subscriptions just end, without re-subscribing.

(As an aside, if it were to actually re-sub, it'd still be terrible because subbing for federation currently *always* returns *all* data, which is slow and redundant and may or may not push down to subscribers depending on circumstances.)

Have added printfs to hall so that when ++quit fires, it prints out the origin and the affected wire. Curious to see if this tells us anything interesting. Expectation: foreign `src.bol`... Still won't tell us why though.

**Comment by ohAitch** [comment]
I think @cgyarvin said you should always retry on a quit, and only handle
"banned" type errors on resubscription? Though I can see checking the range
in the wire and not retrying if we actually have all the messages, as an
optimization

(Or rather, it's a corner case of "reopen the range subscription minus the
first however messages we've gotten")

**Comment by Fang-** [comment]
Right, because if you get kicked/errored out as a direct result of the %peer, rather than an event happening to it down the line, it doesn't go back into ++quit, but just hits the ++reap instead.  
That makes sense. Will have to make reap fails less ugly first, maybe.

**Comment by ohAitch** [comment]
Yeah, ++reap is the handler for actual errors, ++quit just means "the
remote queue filled up or the local queue filled up or in general your
subscription as a piece of transient nonlocal state has met its end" and is
not a value judgement of any sort

**Comment by Fang-** [comment]
I'd say that's it a bit confusing then that userspace applications can also %quit incoming subscriptions. If you implemented your ++quit right, sure, it's going to end up at ++reap eventually. But taking your definition of ++quit as truth, it might be more semantically coherent if I could %pull an incoming subscription whenever, say, we ban someone from a channel.

**Comment by ohAitch** [comment]
By all means %pull their subscription if this's is useful for server
bookkeeping, just don't use this as the sole information channel.

**Comment by ohAitch** [comment]
Er, by all means %quit incoming subscriptions*

Client-side %pull should not result in a ++quit hopefully
