### ISSUE TITLE
Potential problem in the security driver autoreload system

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#5]
After starting a fakezod on a DO droplet, and making a shim com/googleapis/pubsub to deal with #4, @ault011 is still getting 401s. Track down, eliminate.

**Comment by galenwp** [comment]
Since #4 is closed, perhaps this can be closed?

**Comment by ohAitch** [comment]
Probably, "getting 401s" on gcloud pubsub is not really enough information to reproduce.
