### ISSUE TITLE
List stations you've created? 

### ISSUE THREAD

**Issue by c-johnson** [urbit/arvo#503]
I want a simple way to list the stations you've created through the ;talk interface

I'm ~zod, and I write (from /docs/using/messaging.md):

~your-urbit:talk> ;create channel %my-channel 'Some description.'

Can there be something like ;list-stations to print out all the stations I've created, to confirm that this works? 

Ideally I would like this to be exposed via Hall as well. (Update: Apparently this is served by Hall already, I just need to figure out how)

**Comment by cgyarvin** [comment]
This essentially needs a connection between the .^ namespace and %gall, something we don’t have but have wanted to do for a while...

**Comment by ohAitch** [comment]
we don't?

➤ cat gen/twit/feed.hoon

::  Display twitter feed

::

::::  /hoon/feed/twit/gen

  ::

/?    310

/-    twitter

/+  old-zuse

=,  old-zuse

::

::::  ~fyr

  ::

:-  %say

|=  $:  {now/@da eny/@uvJ bek/beak}

        {{who/iden $~} typ/?($user $home)}

    ==

=+  pax=/(scot %p p.bek)/twit/(scot %da now)/[typ]/[who]

:-  %tang

%+  turn   (flop .^((list post:twitter) %gx pax))

|=  post:twitter  ^-  tank

rose+[": " `~]^~[leaf+"{<now>} @{(trip who)}" leaf+(trip txt)]

(this is what ++peek and ++peer-scry-x arms are about, in apps that have
them)

**Comment by galenwp** [comment]
As we discussed with Mark, it does seem to be exposed via an API endpoint.

**Comment by cgyarvin** [comment]
Right, we do :-)
