### ISSUE TITLE
In-app wish .^ not functioning

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#512]
I can't seem to make wishes from within apps. Take this simple example app, which uses a `.^` suggested by @ohAitch as a simple case.

```
|_  {bol/bowl:gall $~}
++  poke-noun
  |=  a/@
  ~&  %trying-wish
  =+  res=.^(json %gx /=mark-dashboard=/json)
  ~&  res-is+res
  [~ +>.$]
--
```

Normally, you'll want to set line 46 in `/app/mark-dashboard.hoon` to `%+  turn  ~`. I don't think it matters right now though, as its code doesn't seem to get run at all. (Printfs in its `++peek` and `++peer-scry` arms don't show up.)

Poking this (after `|start`ing both `%test` and `%mark-dashboard`) will print this:

```
%trying-wish
> :test 5
/gx/~zod/mark-dashboard/0/json
```

Running the same wish from dojo, you do get the expected output:

```
> .^(json %gx /=mark-dashboard=/json)
[%camping %g %x [p=~zod q=%mark-dashboard r=[%da p=~2017.12.19..14.00.36..b1c7]] s=/json]
[%o p={}]
```

The `%camping` there might be noteworthy.

**Comment by joemfb** [comment]
You won't be able to use `.^` against the mark dashboard from an app. It's `++peek` arm produces `~`, which means "blocking". Blocking `.^` is simulated in %ford with `++camp`, which subscribes for you `++peer-scry` and re-runs your code once it receives data from the subscription. But it only does that for stateless code.

If you create a `++peek` arm somewhere that directly produces data (`(unit (unit (pair mark something)))`), you'll be able to dereference that from an app.

**Comment by Fang-** [comment]
The `(pair mark something)` is news to me, but other than that I've already tried that.

Using this expanded test-app:

```
|_  {bol/bowl:gall $~}
++  poke-noun
  |=  a/@
  ~&  %trying-wish
  =+  res=.^(* %gx /=test=/noun)
  ~&  res-is+res
  [~ +>.$]
::
++  peek
  |=  a/*
  ^-  (unit (unit (pair mark *)))
  ~&  %peeked
  ``[%noun [1 2]]
--
```

The same issue occurs. `%peeked` doesn't even get printed.

**Comment by joemfb** [comment]
I can't get it to work either. I've tried everything I can think of. %ford goes straight to camping, and never calls `++peek`. Maybe there's been a regression?

/cc @ohAitch

**Comment by ohAitch** [comment]
.^(* %gx /(scot %p our.bol)/test/(scot %da now.bol)/noun), gall scry only
functions at the current time and is orthogonal to the constant numeric
clay revision the app was compiled with

**Comment by joemfb** [comment]
I should've been more explicit with examples: I've tried every modification to the path itself that I can think of. In the app, it just prints the path (EWOULDBLOCK), and in the :dojo, it always camps:

```
.^(* %gx /(scot %p our)/test/(scot %da now)/noun)
```

I have `~&` inside and outside the ++peek, and they never print. It appears that the ++peek arm is not being called at all.

The only thing I can get to work is this:

```
++  peer-scry
  |=  a/*
  ~&  peer-scry+a
  :_  +>.$
  [ost.bol %diff %noun [1 2]]~
```

```
> .^(* %gx /(scot %p our)/test/(scot %da now)/noun)
>> [%camping %g %x [p=~zod q=%test r=[%da p=~2017.12.19..17.19.17..8305]] s=/noun]
[%peer-scry [120 0]]
[1 2]
```

I thought non-blocking scry was working in %gall apps in the previous era, but now I'm not sure. I know I had a bunch of trouble getting `:twit` to work. I'd be happy to test, but I can't find a maint pill -- do you have a link?

**Comment by ohAitch** [comment]
hey @cgyarvin, when was ++shop introduced? I think I've fixed this by
duplicating aaa92672 on gall, but I'm not sure what the implications of
"DNS identity" even are. Was this an attempt to unify .^ and http namespace?

**Comment by cgyarvin** [comment]
Yes, and a mistaken one.  Where are we on this issue?  Sorry to lose the
thread...

**Comment by ohAitch** [comment]
#522 is awaiting your review, though if ++shop can be reverted it'll be
taken back out of master promptly
