### ISSUE TITLE
kick: lost %hear on //ames

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#515]
Today on talk I tried to activate line on ~tonweb-pilseb.
Suddenly talk quit with some line saying "underflow" (the exact line got lost because the console buffer was too small).
Next, talk quit working. I did |reset and relinked it. Works, but every few seconds I see

```
[%swim-call-vane %e %west ~]
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[1.993 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.002 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.003 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.013 3].[2.021 13]>

/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.014 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.015 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.016 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.017 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.018 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.019 3].[2.021 13]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.020 5].[2.020 63]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[2.020 10].[2.020 63]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[634 5].[768 7]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[635 5].[768 7]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[636 5].[768 7]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[637 5].[768 7]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[740 7].[765 9]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[741 7].[765 9]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[742 7].[765 9]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[745 7].[765 9]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[747 15].[747 61]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[747 16].[747 44]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[747 28].[747 44]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[945 27].[945 58]>
/~tonweb-pilseb/home/~2017.12.21..14.52.46..5c71/sys/vane/eyre:<[945 38].[945 57]>

kick: lost %hear on //ames
```

**Comment by mikolajpp** [comment]
Good news. I reproduced the issue:

[unlinked from [p=~tonweb-pilseb q=%talk]]
/~tonweb-pilseb/home/0/app/talk:<[2.243 3].[2.243 27]>
/~tonweb-pilseb/home/0/app/talk:<[2.243 11].[2.243 27]>
/~tonweb-pilseb/home/0/app/talk:<[484 5].[487 36]>

/~tonweb-pilseb/home/0/app/talk:<[485 5].[487 36]>
/~tonweb-pilseb/home/0/app/talk:<[487 5].[487 36]>
/~tonweb-pilseb/home/0/app/talk:<[487 13].[487 36]>
/~tonweb-pilseb/home/0/app/talk:<[545 7].[550 9]>
/~tonweb-pilseb/home/0/app/talk:<[546 7].[550 9]>
/~tonweb-pilseb/home/0/app/talk:<[549 15].[549 22]>
/~tonweb-pilseb/home/0/app/talk:<[898 7].[915 9]>
/~tonweb-pilseb/home/0/app/talk:<[899 7].[915 9]>
/~tonweb-pilseb/home/0/app/talk:<[901 7].[915 9]>
/~tonweb-pilseb/home/0/app/talk:<[902 7].[915 9]>
/~tonweb-pilseb/home/0/app/talk:<[903 7].[915 9]>
/~tonweb-pilseb/home/0/app/talk:<[929 7].[1.399 9]>
/~tonweb-pilseb/home/0/app/talk:<[930 7].[1.399 9]>
/~tonweb-pilseb/home/0/app/talk:<[930 11].[930 15]>
/~tonweb-pilseb/home/0/app/talk:<[930 11].[930 15]>
/~tonweb-pilseb/home/0/app/talk:<[939 9].[976 11]>
/~tonweb-pilseb/home/0/app/talk:<[960 20].[960 34]>
/~tonweb-pilseb/home/0/app/talk:<[1.249 9].[1.262 78]>
/~tonweb-pilseb/home/0/app/talk:<[1.250 9].[1.262 78]>
/~tonweb-pilseb/home/0/app/talk:<[1.251 9].[1.262 78]>
/~tonweb-pilseb/home/0/app/talk:<[1.256 9].[1.262 78]>

/~tonweb-pilseb/home/0/app/talk:<[1.257 11].[1.261 53]>
/~tonweb-pilseb/home/0/app/talk:<[1.259 11].[1.261 53]>
/~tonweb-pilseb/home/0/app/talk:<[1.259 15].[1.259 41]>
/~tonweb-pilseb/home/0/app/talk:<[1.259 19].[1.259 41]>
/~tonweb-pilseb/home/0/app/talk:<[991 9].[995 42]>
/~tonweb-pilseb/home/0/app/talk:<[992 9].[995 42]>
/~tonweb-pilseb/home/0/app/talk:<[993 9].[995 42]>
/~tonweb-pilseb/home/0/app/talk:<[994 9].[995 42]>
/~tonweb-pilseb/home/0/app/talk:<[994 13].[994 42]>
/~tonweb-pilseb/home/0/app/talk:<[994 30].[994 41]>
subtract-underflow

This happens when one tries to reference message of index MAX where MAX is the index of the last message in talk

**Comment by mikolajpp** [comment]
I tried to |reset several times, nothing helps. Get that kick messages every few seconds. 
I will be happy to provide planet for closer inspection.

**Comment by mikolajpp** [comment]
Update: The errors mysteriously went away.
I saw this some time after:

%posh-fail
%posh-fail
%posh-fail

**Comment by jtobin** [comment]
Closing this one as it's not clear it's still relevant.
