### ISSUE TITLE
Strange prompt error triggered while activating lines

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#517]
```
--------------| ;2.600
? 2.600
0v4.rj3ii.n9qlp.oc9pt.2gc3p.j3p49 at ~2017.12.21..14.48.35..b757 ~taglux-nidsep to + ~binzod/urbit-meta
https://www.youtube.com/watch?v=wlLYM2IbBXA
--------------| ;2.700
? 2.700
0v7.35che.8ob12.1bf00.5gotg.8sane.17077 at ~2017.12.21..15.32.38..ca7e ~tonweb-pilseb to :, + ~binzod/urbit-meta

i think these are 2 bugs
--------------| ;2.700
? 2.700
0v7.35che.8ob12.1bf00.5gotg.8sane.17077 at ~2017.12.21..15.32.38..ca7e ~tonweb-pilseb to :, + ~binzod/urbit-meta
i think these are 2 bugs
; ~marzod not responding still trying
~tonweb-pilseb:talk[+ ~binzod/urbit-meta]
```

As you can see the '+' character is inside brackets.

It goes away only after activating some line:

```
~tonweb-pilseb; test
~rivseb_hadref+^ :: test successful!
--------------| ;2.600
? 2.600
0v4.rj3ii.n9qlp.oc9pt.2gc3p.j3p49 at ~2017.12.21..14.48.35..b757 ~taglux-nidsep to + ~binzod/urbit-meta
https://www.youtube.com/watch?v=wlLYM2IbBXA
~tonweb-pilseb:talk+

```

**Comment by mikolajpp** [comment]
What is even more strange, activating lines seems to randomly change the prompt, disregarding the glyph:
```
--------------| ;2.725
? 2.725

0va2m2g.rrger.va5qu.c3ipa.7de0a at ~2017.12.21..15.43.02..ab03 ~palfun-foslup to + ~binzod/urbit-meta
seems to get the increasingly smaller head of the path
--------------| ;2.730
? 2.730
0ve9uth.ulbfv.rfhr5.lssrm.m7ff8 at ~2017.12.21..15.48.54..603e ~tonweb-pilseb to :, + /urbit-meta
ee
~tonweb-pilseb:talk[+ /urbit-meta] ;2.730

```

**Comment by mikolajpp** [comment]
Is it a feature? It seems to be taking the destination of sent messages...

**Comment by ohAitch** [comment]
Activating basically puts you in reply-mode yes, though if + and
/urbit-meta are the same channel they definitely shouldn't both be in your
prompt.

**Comment by Fang-** [comment]
The behavior you're seeing is not incorrect.

Activating a message sets your audience to match that message's.

When it's showing the audience with brackets it means you're going to be sending messages to both your inbox and the shown target. This is done automatically when talk detects you're sending to a target you're not subscribed to, to make sure you do see your message echoed locally.

There is a bug where talk sometimes doesn't recognize you've joined a channel properly. #513 should fix that.

**Comment by mikolajpp** [comment]
Okay, closing then.
