### ISSUE TITLE
How to access compiler API

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#520]
I am struggling with tapping Hoon compiler. 
Basically I would like to be able to access stuff like parser, compiler and execution. 
I have managed to uncover some bits, such as ++reap, ++slap, ++mule. With first two I seem to have generated parsed hoon. How do I get it to execute, and where can I find more information?

**Comment by cgyarvin** [comment]
If you have a ++hoon, the core of the compiler is ++mint:ut.  With
[sut=type gen=hoon], (~(mint ut sut) %noun gen) will give you a [type nock]
cell.  The nock is a formula you can run with .*.

**Comment by mikolajpp** [comment]
What's the use for mule then? I was hoping it would provide some kind of sandbox. Basically I want to run a code in a context where say certain decks are unaccessible. Is it possible?

**Comment by cgyarvin** [comment]
It’s a sandbox.  It gives you a crash report if you crash.

**Comment by ohAitch** [comment]
++slap will in fact both compile and run the thing, (slap !>([a=1 b=2])
limb+%a) should get you !>(1)

++mule actually cuts of all access to .^, which is kind of what you want;
as you saw in talk the combination (mule |.((slap !>(.) (ream input))))
will get you an either type containing an evaluated result or a stack trace

++mint on the other hand will give you nock, which you can run with .*
while not inside a !> vase; either in or outside of ++mule as per above

++mock, and the other arms near it in hoon.hoon, will give you more
raw-form virtualization, including accepting a non-"always crash" function
for .^

Note that either with .* or mock, you will not be able to get typed data
out, and will instead get the type as a value output by ++mint:ut. You can
however, validate the untyped * nock result as a specific type using
++hard, or get a pretty-printed rendering of the output [type value] "!>"
pair using ++text

**Comment by mikolajpp** [comment]
This is very helpful, I promise I will build a tutorial for this once I master these compiler concepts ;-)

Suppose I would want to have my own command line tool with parsing (which I presume is what talk is doing). Are there any specific arms in compiler core which I should be interested in?

As a side note, I discovered a nice way of sandboxing stuff.
For example, a simple 'calculator environment' would be:
`(slap !>([add=add mul=mul div=div sub=sub]) (ream '(add 2 3)'))`

To make sure I fully understand what's going on:
1. `ream` parsed the hoon and produced AST. It contains among other things, a wing (reference of sorts) 
    to add. 
2. !>(x) produces a vase out of any noun x. In this case i supplied it with a tree
   which contains relevant operations meant to be accesible. 
   One thing I don't understand here, is what exactly how exactly does it work. Does the vase for slap 
   becomes the subject (payload?) of the hoon? If I do `!>(..zuse)` it seems that at least standard library is accesible. Why `!>(..hoon)` does not at least expose arms defined in hoon? 

For example, if I would want 'bare hoon' to be accesible, but disallow use of clay, to prevent user from messing with the filesystem, I would like to say `!>(..hoon)` and have the Hoon language and standard library accessible. For some reason it does not work this way...

**Comment by mikolajpp** [comment]
Okay, it seems something like 
`(slap !>(..hoon:arvo) (ream '(add 2 5)'))`
works. On the other hand, the same line with `!>(hoon:arvo)` also works, which adds to my confusion. 
I know `..` gets the core of an arm. But slap seems not to care...

**Comment by mikolajpp** [comment]
After poking at it for some time, I think I mostly figured it out. 

One last question: Is it possible to send moves to arvo vanes when `zuse` is in our subject?
By the time mule runs, the hoon is already executed as per @ohAitch . 
So I don't understand how using `mule` would prevent anything.

**Comment by ohAitch** [comment]
|. is a "trap", a thunk of unexpected code. Just |.(foo) compiles to a
constant; mule takes the code within and executes it. (The other notable
usage of |. is parser combinators, where ++knee creates nesting levels on
demand, by defering parser construction until parse-time)

You send arvo moves as the callee, not the caller: you can certainly *make*
arvo moves by using the `task-arvo` type(though gall uses a simplified
whitelisted subset of them), but for them to have any effect, they'd need
to be produced by the ^- [(list effect) self] arm that is the entry point
from gall into the app. So it would very much require cooperation from the
virtualizer.
And if you're in a mark or ford web file, you have no way to cause effects
at all

I guess you could compile a duplicate arvo ~inside~ the user code, and send
moves to it, but the resulting inner-arvo state would have no bearing on
what processes the rest of the events flowing through your urbit; unless,
once again, you export the inner-arvo from the virtualizer, and also patch
arvo.hoon to accept its successor in an operation similar to |reset

**Comment by galenwp** [comment]
I don't have much to add — but adding documentation in this area would be really fantastic.
