### ISSUE TITLE
Gall - can not disable once defined arm by deleting it

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#525]
I feel like this could be the correct behaviour, but anyway:
Suppose you have an app with defined prep arm.
Suppose arm is not empty and for example sets timer. Now, if you removed this arm from the code completely, the app will recompile, but the gall will still call the prep arm from previous version of the arm. 

I.e. deleting an arm from app does not remove it altogether. The Gall will see the arm as it was last defined. Obviously to get rid of that we can recompile app first with empty arm and remove it from source code.

In either case I think this is worth documenting, as it could prove to be a source of frustration for or even impossible to trace bugs.

**Comment by ohAitch** [comment]
Can you post the app you're seeing this in? Deleting an arm should
definitely disable it; the gotchas I can think of are:
- if your changes to the app cause it to not compile, and you see
corresponding a stack trace in your urbit log, gall will in fact keep
running the old app core and not the current impossible-to-compile one
- ++prep in particular might be called, once, as the app is being replaced
with its update? But I think that's just ++save in vanes
- if you set a timer from ++prep, the timer now exists in %behn up outside
your app, and will come back as an eventual ++wake callback, regardless if
the arm that could send other independent future timers still exists or not.

**Comment by mikolajpp** [comment]
@ohAitch ,

I tried to reproduce it, but without success. It seems I fell into one of your cases. 
Closing for now, if I see it again then will be sure to report with some reproducible example.
