### ISSUE TITLE
Ford not building app, gall fails with "bogus core"

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#527]
I have run into strange issue.
I tried to start an app, which gall did without complaining. But
poking the app does not work at all, fails with "mo-not-running". 

I renamed the file and tried to start it again. It seems gall is failing with this strange message I have never seen before.

```
activated app home/problem
%problem: bogus core
>> [%mo-not-running %problem %peer]
> |start %problem
>=
```

From this point any changes to the source code do not trigger ford ever again. 
Source code (which works on another ship):
```
/=  env  /~  !>(.)

|%
+=  move  [bone card]
+=  card  $%  ~
      ==
--

|_  [bow/bowl:gall]
++  eval
  |=  src=tape
          =/  res  =>  |.((sell (slap env (ream (crip src)))))
                        (mule .)

                ?-  -.res
                %&  "An utter success"
                %|  "An utter failure"
                ==

++  poke-noun
  |=  src=tape
  ^-  (quip move _+>)
      ~&  eval+src+src
      ~&  (eval src)
      [~ +>]
--

```

**Comment by Fang-** [comment]
Bogus core means the app core `|_` doesn't take  a "correct" sample.  
You want it to take the bowl and application state. If you have no application state, that should explicitly be set as null.

So, assuming I have my new syntax right, you want this:

```
|_  [bow/bowl:gall ~]
```

**Comment by joemfb** [comment]
`[bow=bowl:gall ~]` is the new syntax. (`{bow/bowl:gall $~}` was the old)

**Comment by mikolajpp** [comment]
I copied it verbatim from the other planet where I thought it was running, but you are right...
Anyway, after changing it to the correct sample, the app still is not running. 
It seems once the core is bogus, the ford won't recompile it again.

Is there any way to restart the app? I would prefer to keep the current name of the app...

**Comment by cgyarvin** [comment]
Ooh, that's definitely a bug.  Please file.  %gall should also have more
sophisticated ways to migrate apps -- changing names shouldn't be
impossible.

Usually our habit is to develop on comets or fake zods, because of problems
like this.  But this is a bad habit and keeps the problem from getting
solved.  You should be able to develop on your real ship, duh.

**Comment by mikolajpp** [comment]
I tried to do different things, like |restart, |rc, |wipe-ford,  but nothing works. 
For the solution is to rename the app and be careful not to break the sample.

**Comment by cgyarvin** [comment]
Thanks for walking on our thin ice!

**Comment by mikolajpp** [comment]
My pleasure ;-)

Is it some deeper problem? I have been looking around in gall.hoon, and from what I am able to understand so far, `++mo-boom` which is responsible for new boot looks different than `++mo-boon` which boots the old app. I am assuming this means booting after the update. 

`++mo-boom` fail with: 

`(mo-give %onto %| [%leaf "{<dap>}: bogus core"]~)`

And I am inferring after this move `++mo-boom` will never run again.

**Comment by mikolajpp** [comment]
Another, probably related: starting non-existent app, result in ford-fail, but subsequent calls to |start will fail with 'already running' from drum. 

```
activated app home/platoee
fame: no /~ponmep-litsem/home/59/app/platoee
ford: core /~ponmep-litsem/home/~2017.12.30..06.13.59..a6ff/app/platoee
>> [%mo-not-running %platoee %peer]
> |start %platoee
>=
[already running %home/%platoee]
> |start %platoee
>=

```

**Comment by cgyarvin** [comment]
The fundamental problem is that %gall is long in the tooth and needs a bit
of a rewrite.  Mark and I have already worked on some designs.

**Comment by mikolajpp** [comment]
Rooting for the new gall then. In the meantime I will follow the advice and spin a comet or two for Hoon development.
