### ISSUE TITLE
dejs:format in zuse: unclear interface for json reparser

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#529]
First, it seems docs are outdated, at least the examples don't work. 
I have managed to have stuff like this:

`((ot:dejs:format type+sa:dejs:format src+sa:dejs:format ~) testjson)`

work. For reasons i don't understand, of:dejs:format checks some this condition:
` ?=({$o {@ *} $~ $~} jon)`
which prohibits me from using it on enjs:format generated objects. 

For now I have only managed to convert JSON object -> tuple, but for obvious reasons I would like to have it in a map.

**Comment by ohAitch** [comment]
grep dejs in mar/ for common usage; ++of in particular parses a $% frond,
and should work fine in e.g. =>(format ((of foo+ni bar+so ~):dejs (frond
%foo (numb 42)):enjs))

**Comment by mikolajpp** [comment]
Thanks, I am slowly getting a grip on this.

As a side note, would following code

```
=-  ((ot -<) ->)
                   [~[type+sa:dejs] jon]
```

Be considered good hoon? (seems bad to me)

Originally I have the following mark:

```
++  json
      |=  jon=^json
          ~&  jon
          =/  par  =-  ((ot -) jon)
                   ~[type+sa:dejs]
                   eval+par
  --
```

But the above fails with ford error. It seems this is because there js no jon in the subject. 
On the other hand, the following:

```
  |=  a/json
    ^-  action:hall
    =-  (need ((of -) a))
```

works. I fail to see how `need` makes a difference, but obviously hall works.

**Comment by mikolajpp** [comment]
This is embarassing, after changing jon->a it works.
Now, I scourged zuse for any ++  jon, but there is nothing. And why would it suddenly work, as jon is innermost symbol.

**Comment by mikolajpp** [comment]
To be precise. 
The following:

```
/-  plato
!:
=,  format
|_  src=program:plato
++  grab
  |%
  ++  json
      |=  jon=^json
          ^-  program:plato
          =/  par  =-  ((ot -) jon)
                   ~[type+sa:dejs]
                   ~&  par
                   eval+par
  --
--
```

does work. If I change jo -> jon it fails with

```
/~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/home/0/mar/plato/program:<[9 11].[13 28]>
  /~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/home/0/mar/plato/program
  <[10 11].[13 28]>
  /~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/home/0/mar/plato/program
  <[10 20].[11 35]>
  /~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/home/0/mar/plato/program
  <[10 24].[10 36]>
ford: casting %json to %plato-program
ford: cast %plato-program
```

Idk if this is a bug, but i have no jon defined anywhere.

**Comment by mikolajpp** [comment]
Even more strangely, the following works:

  ```
++  json
      |=  jon=^json
          ~&  jon
          ~&  =-  [- jon]  2
          eval+"haha"
```

It seems to break once it reach the (ot:dejs ...) line

**Comment by mikolajpp** [comment]
Ok, I have narrowed down the issue, which has nothing to do with marks. Closing this and opening new one.
