### ISSUE TITLE
Unexpected(?) Hoon behaviour related to "=-" rune and name clashes.

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#530]
Steps to reproduce:

```
=testjson (pairs ~[[%type (tape "eval")] [%src (tape "42")]]):enjs:format
=jon testjson
```

The following works:
`=-(((ot:dejs:format -) testjson) ~[type+sa:dejs:format src+sa:dejs:format])`

The following fails:
```
> =-(((ot:dejs:format -) jon) ~[type+sa:dejs:format src+sa:dejs:format])
\/ford: build failed ~[/g/~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/use/dojo/~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/in\/
  n/hand /g/~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/use/hood/~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/out/dojo/drum/ph
  at/~dispex-binwed-sivweg-dosnul--larwen-mirdem-widnem-poshet/dojo /d //term/1]
\/
```

I am pretty sure this is related to the fact that 'jon' is defined in ot:dejs:format, which returns a gate accepting argument with this name. 

The ford fails with no error message.

**Comment by ohAitch** [comment]
The particular error message ford doesn't fail with would be something like
"dejs deserialization error", dejs should probably have ~|s in it similar
how when you get %hard on a failing ((hard foo) `*`bar)

**Comment by ohAitch** [comment]
(The cause of it is indeed jon being *json, from the gate sample, which is
~ and not [%o etc] as is being ?> asserted)

**Comment by mikolajpp** [comment]
I feel like I do not fully understand what is going on. Why then the following example works:
`=-(((|*(b/@ |=(a/@ (add a b))) -) a) 42)`

Isn't it functionally equilavent?

**Comment by ohAitch** [comment]
If you said =/(a 42 =-((- a) |=(a=@ (dec a)))) you would run into the
problem; you're absolutely right that =- =, and =+ (without immediate
faces) are tricky because they unify namespaces from two places.

**Comment by mikolajpp** [comment]
Hmm, your example fails as expected. Just by looking, I am not able to say why. 
How do =-, =-, =+ runes do their lookup? Do they first look inside the second hoon and find a/@ --> a=*@ and this is the problem?
