### ISSUE TITLE
Talk/hall connections get really slow, blocking other traffic

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#533]
Not 100% sure what's happening here, but I have observed the following:

- Re-connecting to my parent's urbit-meta caused ~palfun to get into one-way connectivity with it. After rebooting both ships, all unsuccessful `|hi`s suddenly went through (from star to planet).
- Booting a moon, it initially didn't seem to get connectivity to the planet's hall, and wasn't receiving `|hi`s from the planet either. Rebooting and forcing talk to reconnect eventually caused some amesing and a big chunk of messages making their way onto the moon.
- Had to wait a long time (during which I also rebooted and reconnected again) for smaller chunks of more recent messages to come through. After those mostly completed, the `|hi`s finally came through as well.

This seems to me as if big prizes take a ton of time to go to the recipient and be processed, which blocks other communication in the same direction until that has finished (because packets need to stay in-order).

Maybe talk shouldn't ask for the entire history on-connect? Clients will likely want to load it in at some point though. Should we somehow cut up large prizes into smaller chunks?

**Comment by cgyarvin** [comment]
That's interesting -- a case of false one-way connectivity.  Doing |verb
when this happens should reveal what's actually going on.  If this
interpretation is right.

Yes, the "whole history" approach will inevitably fail to scale... rapidly
as the "whole history" grows.  Definitely worth limiting this, probably
chronologically (a week?)

**Comment by Fang-** [comment]
Subset of #582.
