### ISSUE TITLE
Infinite loop when starting same app from different desks

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#542]
I think I hit a bug of 2018 ;-)

I run a blog from non-home desk.
Comments gets saved in %home, even though I serve from %blog. 

I discovered that rendering fails
```
{"pax":"/=blog=/web/urbitetorbi/planet-crash","sup":"/planet-crash/urbitetorbi/web","txt":"Test"}
ford: cast %fora-comment
ford: casting %json to %fora-comment
####
```

It must be that home/app/fora & home/blog/fora are two different apps and home app will save in home, blog app will save in blog.
Happy to verify my conclusion I start `=dir /=blog=`, followed by `|start %fora`
only to discover it triggered infinite loop:

[Infinte loop gif](http://i.magaimg.net/img/2bra.gif)

Edit: Ctrl-C worked, Ship is safe. 

Edit2: Starting with `|start %blog %fora` also gives an infinite loop. Pressing Ctrl-C still works.
```

[%swim-take-vane %g %onto ~]
[%gall-take /~tonweb-pilseb/use/hood/~tonweb-pilseb/inn/drum/home/fora]
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.610 5].[12.612 39]>
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.611 5].[12.612 39]>
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.611 20].[12.611 41]>
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.596 5].[12.600 52]>
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.597 5].[12.600 52]>
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.597 9].[12.597 38]>
  /~tonweb-pilseb/home/~2017.12.21..16.42.57..ba07/sys/hoon
  <[12.597 13].[12.597 38]>



```

**Comment by ohAitch** [comment]
Someone beat you there I'm afraid, urbit/urbit#881 (and like,
urbit/urbit#649 arguably)

**Comment by mikolajpp** [comment]
Oh, sorry. Closing then. There is a separate ticket for %fora bug though.

**Comment by Fang-** [comment]
Re-opening because this issue is more appropriate in the arvo repo.
