### ISSUE TITLE
Discrepancies (?) in %eyre endpoints

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#574]
I am digging subscriptions, mostly from working talk implementation (already added to %eyre ticket in docs), and I wonder what is the ultimate convention. Some things seems to be passed in body, eg. poke takes the ship as body, while for subscriptions ship is actually part of the URL. 

I might be confused due to the basing on working examples.

**Comment by mikolajpp** [comment]
Okay, I got it to work eventually. 

A related question is, does %eyre is suppose to support multiple subscriptions. 
In plato, I am polling on compilation jobs, and later I will add pooling on snippet arrivals. 

The current architecture pretty much force me to have one large JSON and receive all state updates in it. 

Would something like the following be reasonable:

1. .../wire.json?PUT returns a unique subscription hash
2. subsequent calls to /of/[hash] receive updates for a previously specified subscription

current architecture pretty much forces either one large JSON, or switching the context of by repeated use of PUT, which I am pretty sure was not designed to alternate between subscription in each update tick.

**Comment by mikolajpp** [comment]
Okay, it seems i totally misunderstood the polling id meaning. 
Everything is fine, carry as usual.

**Comment by ohAitch** [comment]
All the subscriptions get dumped in one stream so you don't have to have multiple HTTP requests open, yeah.
If you really wanted (to split across machines or sth), you could just fetch `/~/auth.json` repeatedly, and each would give you a fresh oryx/ixor stream id: this is how having multiple independent webtalk tabs works, for example.

**Comment by mikolajpp** [comment]
Ok, one thing that I think is some leftovers. 
The "wire" field is sometimes duplicated as "wire" & "path" when sending to eyre even though the "wire" field for PUT is sufficient (I checked it, but talk for some reason sends both of them). 

Also eyre returns only "path" in polling replies. 

I think this should be best fixed by just settling on one field, "wire" being the correct one in the context of moves.

**Comment by jtobin** [comment]
Closing as I think this one is a little too idiosyncratic to be more broadly useful.
