### ISSUE TITLE
Urbit markdown files won't render with a semicolon ; at the beginning of a normal text line

### ISSUE THREAD

**Issue by keatondunsford** [urbit/arvo#588]
I imagine this is because `.umd` is expecting all tokens followed by `;` to be `;` runes such as `;=` or `;>`. I just ran into an example converting `/docs/hoon/library/zuse/gate/scanf` where a line started with a `;` and wasn't attempting to be a rune.

Simple reproduction case -- this renders:

```
:-  :~
title/'Some markdown'
==
;>

This is a line.
```

This doesn't:

```
:-  :~
title/'Some markdown'
==
;>

;This is a line.
```

Should we check for this, or just make it a rule that a sentence can't start with a `;`? If it's the latter, we should add this point to `/web/unmark/doc`.

**Comment by ohAitch** [comment]
It is indeed a rule that a sentence can't start with ; insofar as it is
valid umd to say

;this(totally-a "sentence");

If umd doc doesn't cover sail interpolation, it definitely should;
disallowing capital letters, which cannot be valid sail, is less obvious
but seems consistent
