### ISSUE TITLE
Eyre UTF-8 encoding bug

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#592]
When plato is being served from webpack dev server, 
the "run" button is displayed correctly
[run-webpack](http://i.imgs.fyi/img/2eut.png)

When it is run from eyre, the "▶" UTF character becomes garbled:
[run-eyre](http://i.imgs.fyi/img/2eus.png)

**Comment by mikolajpp** [comment]
Okay, it appears I commited slander against eyre ;-)
The charset was missing in HTML file. Setting it to UTF-8 fixes the problem.

**Comment by ohAitch** [comment]
I thought eyre injected charset UTF8 actually; I guess not in raw HTML
files though
