### ISSUE TITLE
Long bootup time - can be alleviated?

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#596]
A lot of times there is a need for a quick comet or two in order
to reproduce bugs. 

These days I find myself pre-emptively spawning comets and hoarding them in fresh/ directory 
to have them available when need arises. 

Would running fakezod net make this problem go away? I have no idea what takes the most 
time of bootup sequence. If it is |merging other comets base, putting it on local network could probably speed things up. 

If not, then I guess it will improve over time as vere gets faster.

**Comment by Fang-** [comment]
Fake local networks are by far the best way to do Urbit development. They don't spend ages waiting for hood (which, yeah, is a performance issue on the livenet), and you can back up all nodes to "go back in time" if you need to.

**Comment by mikolajpp** [comment]
Okay then, I am gonna try it out. I have had enough waiting for 3 comets to boot ;-)
