### ISSUE TITLE
gall <<>> eyre bridge

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#598]
As per #594, maybe we can slowly start thinking about best way to have eyre able to access 
a gall app state.

We need to be able to expose an app's state as a resource retrievable via URL. This entails at least a couple crucial considerations:
1. Mapping between app state and URI
2. Permission mechanism
3. Caching (rather easy? Gall knows exactly when the state changes)
4. What kind of requests should be allowed? I think this should best 
    be kept as a read-only mechanism. Subscriptions and pokes works very well for two-way communications. 

Suppose we run an app :spaceship. 
We should be able to run access some part of state as (Assuming glorious future when we already have Urbit DNS ;-))
`urbit://~ship/~g/spaceship/crew/john.crew-member`

In the following URL we have the usual ship's name. The part that indicates 
we make a gall request is `~g`. After that comes the apps name. 
If the apps does not exist, we can display "Gall 404 error". 

After that, we have URI into apps state. Now, an app state can be anything. 
So we have two options (or more?)

1. Make apps who want to be accessible through eyre conform to some interface <--- Meh

2. Devise universal mapping. For example,`~g/spaceship` is the entire app's state. <--- Cool
`/~g/spaceship.ship` we request the state as a mark `ship` which is then cast to `json`, if possible. 
Otherwise deeper paths would just straightforwardly map onto Hoon's limb resolution. 
Basic data types such as maps, lists could get eyre adapters. For example, if we have 
```
++  state
      (...)
       stories=(map name story)
```
in :hall, it would become accessible as `/~g/hall/state/stories/robinhood.story`. We can imagine similar adapters for lists, pairs and other common datatypes. Or maybe I am overengineering this, but given Hoon magic powers it does not seem very complicated, at least at the surface. 

When it comes to permission mechanism, I imagine a separate arm `++perm` or whatever, which would be invoked upon requesting a path through eyre with the full path as argument and return either true or false with some sensible default (like blocking everything unless the owner is requesting :))

Okay, this is just after an afternoon of thinking.
Hopefully this can be some starting point. In the worst case, we can garbage collect everything 
and continue with someone's else better ideas. 
 

EDIT: I retract "read-only" part. As discussed in the linked issue, there should be a way to 'inject' data into  app's state. Otherwise we will end up with people stuffing things in source code, which is what we mean to avoid. 

For example, a webapp interface could be injected into the app using POST request to
/~g/spaceship/ui.js which would take the data as json and try to stuff them into ui as 'js' (if the marks match). 

Then the public facing ui would be accessed through html which would 
request the /~g/spaceship/ui.js to be loaded. 

Similarly, youtube-like service would host videos under 
/~g/youtube/videos/funnycat.mp4, which could be uploaded through similar mechanism...

**Comment by mikolajpp** [comment]
Some time has passed, and new development in the browser world (namely servo), which promise very high performant browser engines, makes me want to to try to approach this, as this is basically the last missing puzzle that needs to be solved in order to start shipping moderately complex Urbit interfaces (and hope for some standarization emerging in the process, for people to be able to just grab some components and have working Urbit app in no time).

As it stands now, I understand that dust will begin to settle in coming months on new Ford & Clay, which seems like a perfect time to make some serious attempts at this. 

Plato for now is sadly sitting rather idle, since without a way to reliably distribute UI blobs I can't really launch it, without risking blowing up people ships and being branded a pirate.  

This boils down to the state of binary blobs in clay and how far are we from implementing them?

My current view on clay <-> eyre bridge is that perhaps it is not at all desirable, as this kind of seamless 'views' are fulfilled with increasingly new ford, and subscription/poke mechanism is very versatile. Moderately complex apps will unavoidably have to expose API, as it is unlikely simply "mounting" the state will provide any kind of advantage. In fact, application designers should have to expect their internal application state being introspectable, as this would place unnecessary burden on them.

So unless someone thinks this kind of bridge would be preferrable to the options we already have, I propose to close this ticket and instead open a working ticket on "Blob support in clay" which hopefully will lead first to fixing exploding clay bug and then to developing a full support for this kind of feature.

**Comment by jtobin** [comment]
Closing as, per the above comment, I believe the referenced issue supersedes this one.
