### ISSUE TITLE
Put vane definition for tasks application-side

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#599]
Currently, gall does [this](https://github.com/urbit/arvo/blob/master/sys/vane/gall.hoon#L1221-L1243).

In a future iteration of gall, it might be better to have the user specify the vane a request has to go to themselves. This feels like it's in line with the separation of each vane's `++task`s that happens in zuse (it's possible for multiple vanes to have a task with the same tag), and would bring a bit more clarity to application code.

**Comment by Fang-** [comment]
Though maybe this was done to prevent userspace access to certain tasks?

**Comment by Fang-** [comment]
Actually, upon further thought and inspection, this is probably not a great idea.

**Comment by cgyarvin** [comment]
Ha ha this thread slipped between the cracks.  I agree with the conclusion :-)

**Comment by ohAitch** [comment]
Multiple vanes having the same task tag is possible but a terrible idea, if
you ever want to refer to tasks in text without specifying the vane each
time. The app interface follows a similar principle, though having a fully
expanded ++app-move type in ++gall would definitely be helpful as
reference. (perhaps with an argument for the set of casks the app knows
about, which get implicitly hoisted into cages)

Sandboxing was definitely a concern, but mostly in the form of "userspace
can't pass an invalid cage to the rest of the system", excepting ford which
has its own encapsulation semantics.

**Comment by Fang-** [comment]
Agreed about the task tag collisions. Explicit `++app-move` sounds like a good idea.

I'm assuming we feel the same way about gifts and their application arm names.

**Comment by ohAitch** [comment]
Ideally those would be quarantined to an interface core, and/or permit
describing their patterns with actual wires and marks. Not sure how to do
that short of a giant ?- however :/
