### ISSUE TITLE
Vane error during playback causes boot to abort, "sing: ovum failed"

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#605]
See also [this paste](https://pastebin.com/fvazbnDB) and [this fora post](https://fora.urbit.org/posts/~2018.1.28..00.32.39..2abd~/).

If you're unlucky enough to have received #538, but haven't received the related and required #603 yet (which I wasn't smart enough to push onto the network simultaneously) then your hall or talk may cause gall to print an "invalid bone" error. It seems that if this happens during boot (more accurately, playback) then the boot aborts with `sing: ovum failed!` Userspace apps doing dumb things should probably not have that kind of show-stopping power.

Not sure if this happens exclusively for gall errors. I imagine an error in another vane can have the same result.

**Comment by jtobin** [comment]
Closing as this no longer appears to be relevant.
