### ISSUE TITLE
Crash caused by sync causes sync to break permanently

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#611]
Issue #501 was caused by this. See that for past discussion and an outdated repro case.  
That particular root cause was fixed in #538, but probably didn't change the fact that a crash caused by the effects of a sync seems to break the sync/it's subscription permanently.

Crashes shouldn't be breaking upstream subscriptions as aggressively as they are.

Maybe we should just separate the notification %clay sends after file change more strongly.

**Comment by jtobin** [comment]
I was going to leave this one open, but remembered a great line from the 1998 film *Ronin*:

> If there's any doubt, there is no doubt.

I think it needs to be updated, or more detail needs to be provided, in order for it to be useful.

**Comment by joemfb** [comment]
> Maybe we should just separate the notification %clay sends after file change more strongly.

This was just done in @philipcmonk's clay transaction rewrites.
