### ISSUE TITLE
Actions that may take a while to complete/show progress should be explicit about starting

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#612]
Pulled from #558. Examples:

`|merge` should print out "starting merge..." to let the user know we're merging in the background.

On `%init` merge, mention that the new desk is not mounted tell the user how to mount it.

`|mount` of nonexistent desk should either give a readable error or succeed and tell the user it doesn't exist yet.

**Comment by jtobin** [comment]
I'm going to close this as I think it's too broad to ever really resolve as-is.  There are a probably lot of such commands, and I think more focused/specific issues (e.g. "`|merge` should print.." or `|mount` should print..") would prove to be more useful.
