### ISSUE TITLE
Better dojo error messages for common mistakes

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#613]
Common mistakes should have explicit error messages. For examples, +ls should suggest you try `+ls %`, `=% /=examples=` should suggest `=% /=examples`, and `|mount /=examples` should suggest `|mount /=examples=`.

This issue was split off from https://github.com/urbit/arvo/issues/558. See discussion there regarding `+ls`.

**Comment by jtobin** [comment]
As per my comment on #612, I'm going to close this one as I think it's too broad to be resolvable as-is (i.e. it involves altering many generators in many ways)
