### ISSUE TITLE
New talk messages load in web UI but not in console

### ISSUE THREAD

**Issue by jyng** [urbit/arvo#617]
![screen recording terminal](https://user-images.githubusercontent.com/9557907/36052651-6eb99854-0da3-11e8-9df5-d25d6f13e6d6.gif)

**Comment by keatondunsford** [comment]
I had @jyng do a hard merge of his `%base` and `%home` desks with whatever code was on `~marzod` as of `~2018.2.9..14.12`. So this seems weird. CC @Fang-.

**Comment by jyng** [comment]
That fixed it!
