### ISSUE TITLE
Including library breaks tests

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#622]
1. Boot a fakezod using latest master
2. Run `+test /new-hoon/thr` to confirm tests work and complete successfully
3. Create `/lib/breaker.hoon` with the contents `|%  ++  a  0  --`
4. Add it to the `/+` in `/tests/new-hoon/thr.hoon`
5. Run `+test /new-hoon/thr` again and watch the tests fail with the following stack trace:
```
/~zod/home/0/gen/test:<[32 20].[32 30]>
/~zod/home/0/lib/tester:<[57 3].[59 51]>
/~zod/home/0/lib/tester:<[58 3].[59 51]>
/~zod/home/0/lib/tester:<[58 10].[58 58]>
nest-fail
```

**Comment by belisarius222** [comment]
@eglaysher maybe you know something about this?

**Comment by eglaysher** [comment]
This is weird. This appears to be nest failing while trying to run the test inside the dynamic compilation. But I don't know why adding another library would break things.

**Comment by cgyarvin** [comment]
A semantic bug in ford, I suspect...

**Comment by ohAitch** [comment]
The stack trace I'm getting is
```
- have
<2.yix 16.cyv 19.mtp 41.blb 112.kyi 224.bkh 54.tyv 119.luq 30.hhq 1.jmk $143>
- need
<3.hmq 16.cyv 19.mtp 41.blb 112.kyi 224.bkh 54.tyv 119.luq 30.hhq 1.jmk $143>
```
which is to say yes semantic bug in ford, namely the trash fire that is "reprocessed cheese" library translcudes. (`++tester-type` is in one place defined as not having `lib/breaker` in its subject, while in another instance of the *same library* is built with it dumped into its namespace)

That said, just putting a `^?` around the `init-test` call doesn't seem to help, and just results in a more specific mismatch trace:
```
- have
<5?oux {{eny/@uvJ check-iterations/@ud current-iteration/@u} <8.wre 2.cbm 16.cyv 19.mtp 41.blb 112.kyi 224.bkh 54.tyv 119.luq 30.hhq 1.jmk $143>}>
- need
<5.oux {{eny/@uvJ check-iterations/@u current-iteration/@u} <8.wre 3.lov 16.cyv 19.mtp 41.blb 112.kyi 224.bkh 54.tyv 119.luq 30.hhq 1.jmk $143>}>
```

unless you put it in both lib/tester and tests/new-hoon/thr, in which case the type error reverts back to the first. I think I don't fully get what ^? does yet P:

**Comment by cgyarvin** [comment]
Given the existence of =, do you think it might be the right time to murder
the reprocessed cheese?  I've always thought of this as just not that
hard.  Given =, -- which was hard...

**Comment by ohAitch** [comment]
I don't think you even need =, tbh, just cons together a bunch of vases
with faces on.

Like, =, is as helpful with the current "fake core" model

**Comment by Fang-** [comment]
Can still reproduce, except now there is no output anymore. No stack trace, nothing.

**Comment by joemfb** [comment]
Closing, as reprocessed-cheese has been eradicated. There are existing tests that import multiple libraries without issue, for instance `%/tests/lib/pkcs/hoon`.
