### ISSUE TITLE
Talk should only print status updates on-change

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#624]
I could swear I put a check for this in, but apparently not.  
Find the relevant code under `++ta-change-circle`'s `$status` case in `/app/talk.hoon`.

**Comment by pkova** [comment]
I'm going to try to tackle this one. Would you have an example of when talk prints unnecessary status updates? I've poked around a bit but I'm not sure I fully understand the issue yet.

**Comment by Fang-** [comment]
The simplest repro case here would be to create a local sandbox channel, and then repeatedly `;attend %sandbox talk` to update your presence in it.  
...However, that doesn't trigger this issue. I've only ever seen it in urbit-meta, which indicates it's a federation issue, and those can be difficult to reproduce at times.

I'd start by booting up a fakezod and two stars, creating a channel on the ~zod, and then having one of the stars do `;attend %test-channel,~other-star/test-channel talk`. I'm guessing that this will send two status updates to ~zod, and it won't bother checking if they're duplicated before sending them down to the stars again, so you'll *probably* see the notification printed twice on the stars (assuming you've done `;join %test-channel`).  
If you can't get this reproduced properly, I'd totally still accept a PR that implements a check in talk's `++ta-change-circle`.

If you could fix the issue in the federation logic, even better. This probably needs to be fixed in both places though: hall shouldn't send redundant updates, but talk shouldn't notify about updates that don't change anything (which we may still get in rare cases).

...I should maybe not have tagged this "difficulty low" now knowing it's probably federation-related. (^: Happy to answer more questions if you got them.

**Comment by jtobin** [comment]
Closing this as I think it needs to be clearer in order to be useful.
