### ISSUE TITLE
%merge-no-merge-base on ~tyr

### ISSUE THREAD

**Issue by mrdomino** [urbit/arvo#648]
Hey all, I just tried to boot up ~tyr again post-breach with arvo at 798fa84 and https://bootstrap.urbit.org/latest.pill as of about ~2018.2.23..14.00.00. When I try to sync from ~zod, this happens:

```
> |sync %base ~zod %kids
>=
sync failed from %kids on ~zod to %base
please manually merge the desks with
|merge %base ~zod %kids

error code: %merge-no-merge-base
[p=~zod q=%kids]
[p=~tyr q=%base]
[%ud p=2]
%mate
> |merge %base ~zod %kids
>=
%fine merge failed, trying %meet
auto merge failed on strategy %meet
%merge-no-merge-base
[p=~zod q=%kids]
[p=~tyr q=%base]
[%da p=~2018.2.23..14.13.43..b952]
%meet
```

What's going on? How can I fix it? In the end, I suppose that I'd like ~tyr to get live updates from ~zod.

**Comment by Fang-** [comment]
You probably want to do what we did for our galaxies:

1. `|merge %base ~zod %kids, =gem %that`, which I'm assuming gives the two involved ships a point of reference for synchronicity.
2. `|sync %base ~zod %kids`, as you did, to keep them in sync.

Let me know if that works for you!

**Comment by mrdomino** [comment]
Seems like it works. Did I just have too new of an arvo or something?

**Comment by Fang-** [comment]
If you used a checkout of `urbit/arvo/master` from today, probably. But also the two ships not having any frame of reference as to where their desks stand in relation to each other might have tripped things up here. ie "no merge base"

Closing this as a non-issue, will create an issue in urbit/docs to include galaxy-specific instructions somewhere.
