### ISSUE TITLE
Separate type-checks for head and tail of generator arguments

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#65]
Tag @ault011 

Confusing:

```
nest-fail
-want.{{* *} {txt/@tas $~} $~}
- have
{ { now/@da
    eny/@uvI
    bec/{p/@p q/@tas r/?({$tas p/@tas} {$da p/@da} {$ud p/@ud})}
  }
  $~
  $~
}
```

Somewhat better:

```
nest-fail
-want.{{txt/@tas $~} $~}
-have.{$~ $~}
```

In particular, mis-called generators are a separate, common error from mis-written generators.

**Comment by jtobin** [comment]
Closing this one as I think it's a bit too idiosyncratic to be useful more broadly.

**Comment by ohAitch** [comment]
Disagree that this is idiosyncratic, just low priority. Unless you've never called a `+generator` with incorrect / number of arguments?
