### ISSUE TITLE
web talk filtering hangs

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#652]
When I try to filter my web talk so it only displays one channel, it spins forever. I can click "clear" and normal operation resumes.

This is the case even for channels with recent messages, so I don't think it's spinning as a result of being blank.

I did see this error in the console, but couldn't find its line number for some reason:
`Empty string passed to getElementById().`

**Comment by Fang-** [comment]
This seems related to urbit/talk#48.

**Comment by jtobin** [comment]
Is web talk still a thing?  I'm going to assume it has been at effectively (if not entirely) deprecated by Landscape and close this one, but correct me if it's still a going concern somewhere.
