### ISSUE TITLE
Equality test failure doesn't pretty-print values

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#654]
Consider the following test file:

```
/+  tester
|_  tester-type:tester
++  test-simple
  (expect-eq "yes" "no" "example")
--
```

Running it prints out the following:

```
/tests/simple/test-simple FAILED
  failure: 'example'
    actual:   '[121 101 115 0]'
    expected: '[110 111 0]'
```

From a quick glance, it looks like `++expect-eq` is *trying* to pretty-print them, but it's obviously not succeeding for whatever reason.

**Comment by belisarius222** [comment]
Looks to me like the type information got lost somewhere along the way.

**Comment by ohAitch** [comment]
this makes sense, without !> a wet gate won't have the type information to
pretty-print as non-*++noun*
