### ISSUE TITLE
.^ dotket rune appears to be broken across ships

### ISSUE THREAD

**Issue by keatondunsford** [urbit/arvo#656]
This seems to be the case between fake ships as well as livenet ones.

Repro on urbit/urbit@4db7eb4 and urbit/arvo@9c67754678bdd373513412bc91b003f703ee1848:

1. Boot up two fresh ships (fakenet or livenet).
2. On the first ship, test that a local `.^` works on a trivial markdown file, which it should:
   ```
   ~litsec_larwet:dojo> our
   ~litsec-podret-sopsel-sansun--somlec-fortun-tamnys-larwet
   ~litsec_larwet:dojo> .^(@t %cx /~litsec-podret-sopsel-sansun--somlec-fortun-tamnys-larwet/home/1/web/md)
   \/'---\0acontainer: false\0alayout: plan\0aanchor: none\0atitle: Home\0a---\0\/
     a\0a<div class="above">\0a  <div class="container panel stack">\0a    <pane
     l></panel>\0a  </div>\0a  <div class="container plan stack">\0a    <div cla
     ss="col-md-9">\0a      <plan></plan>\0a    </div>\0a  </div>\0a</div>\0a'
   \/                                                                           \/
   ~litsec_larwet:dojo>
   ```
3. On the first ship still, try loading the same file located on the second remote ship (a second comet in the below example, which should produce the same result in Step 2 if run on that ship) by changing the ship in the Clay path:

   ```
   ~folwet_haltyr:dojo> our
   ~folwet-botsyt-rondex-dopwyd--lopheb-witsen-narmug-haltyr
   ```

   ```
   ~litsec_larwet:dojo> .^(@t %cx /~folwet-botsyt-rondex-dopwyd--lopheb-witsen-narmug-haltyr/home/1/web/md)
   >> [ %camping
     %c
     %x
     [ p=~folwet-botsyt-rondex-dopwyd--lopheb-witsen-narmug-haltyr
       q=%home
       r=[%ud p=1]
     ]
     s=/md/web
   ]
   ~litsec_larwet:dojo>
   ```

   The ships do become neighbors:

   ```
   ~litsec_larwet:dojo>
   ; ~folwet-botsyt-rondex-dopwyd--lopheb-witsen-narmug-haltyr not responding still trying
   ; ~folwet-botsyt-rondex-dopwyd--lopheb-witsen-narmug-haltyr is ok
   ; ~folwet-botsyt-rondex-dopwyd--lopheb-witsen-narmug-haltyr is your neighbor
   ~litsec_larwet:dojo>
   ```

   ```
   ~folwet_haltyr:dojo>
   ; ~litsec-podret-sopsel-sansun--somlec-fortun-tamnys-larwet is your neighbor
   ~folwet_haltyr:dojo>
   ```
 
   But notice that Dojo blocks and prevents you from entering any keystrokes:

    ```
    ~litsec_larwet:dojo> <up arrow on keyboard>
    %dy-edit-busy
    %dy-edit-busy
    %dy-edit-busy
    ~litsec_larwet:dojo>
    ```
    
    Because the request doesn't complete.

---

Seems possibly related to #191. CC @ohAitch and @Fang-.

**Comment by keatondunsford** [comment]
@belisarius222 asked me just now if the two comets can `|hi` each other. To clarify, yes, they can.

**Comment by Fang-** [comment]
Hurray! Clay permissions are functioning as they should!

Only the %kids desk is public by default. For the others, run `|public %desk` to make it so. `|private %desk` to undo. You can also do `|public %desk /path` to change permissions for just that path (and everything under it).  
See also [this comment](https://github.com/urbit/arvo/pull/610#issuecomment-365428038) in the clay permissions PR.

**Comment by ohAitch** [comment]
huh, should eyre be attempting to enforce this? like viewing /web/foo as an
anonymous web client still works afaict

**Comment by keatondunsford** [comment]
Mkay, that worked @Fang-, thanks.
