### ISSUE TITLE
CI should run +test

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#660]
...and fail when `FAILED` or `CRASHED` gets seen in output.

This will get more useful as we get more tests, but we already have *some* so why not put them to good use?

**Comment by ohAitch** [comment]
They take two minutes to run(a third of that is compiling everything, which afaict ignores the filter), so if this is "barely any tests" I hope there's a plan for them not taking forever :P

**Comment by ohAitch** [comment]
Due to `/_` semantics, test files that don't compile are currently ignored entirely. This is currently [caught](https://travis-ci.org/ohAitch/arvo/builds/351550254#L1524) by my compile-everything test, but something to keep in mind if those ever get integrated.

**Comment by ohAitch** [comment]
...which is already files as #655, right
