### ISSUE TITLE
can't DM in web talk

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#663]
Whenever I try to send a DM in web talk, the username bar goes red and it won't let me send the message. This happens both when I type `~master-morzod/inbox` manually, and when I click on the name from an earlier message. I can send DMs from CLI talk without issue.

@Fang- maybe you know what this is about.

**Comment by Fang-** [comment]
Can't reproduce, I can send DMs to `~rovnys-ricfer/inbox`, `~rovnys-ricfer` and `rovnys-ricfer` just fine. Clicking ship-names also works.

Not sure what you're hitting here. You can try pointing your browser's debugger at [this function](https://github.com/urbit/talk/blob/master/js/components/WritingComponent.coffee#L284) and seeing if it's doing anything weird, but I'm not sure why that would be out of the ordinary.

**Comment by Fang-** [comment]
Oh I see, the ship name parsing is out of date. [This](https://github.com/urbit/talk/blob/master/js/components/WritingComponent.coffee#L21-L55) still contains old syllables. It was failing on the `mor` part of `~master-morzod`. brb fixing now.

**Comment by joemfb** [comment]
See also urbit/womb#3. I had to use the browser console to claim `~master-morzod` because of that ;)
