### ISSUE TITLE
Sign-in failures via the web ui

### ISSUE THREAD

**Issue by aupiff** [urbit/arvo#668]
I'm running an urbit on a remote server. I am using nginx to forward any requests to routes beginning with /~ or /=== to `127.0.0.1:8443` using [this nginx config](https://gist.github.com/aupiff/660c30189f8b397c7530d704ec00a218#file-example_urbit_proxy_nginx-L17-L23).

In this image you see the state of the application just after I entered what I think is the correct code. A narrow gray html element appears `<pre><code id="err"></code></pre>` with no useful content and I don't get signed in.

<img width="1440" alt="screen shot 2018-03-11 at 14 06 41" src="https://user-images.githubusercontent.com/804266/37256942-223e7416-2538-11e8-9cb0-e3a652795082.png">

Another screenshot of me trying the same thing, this time not in incognito mode.
<img width="1440" alt="screen shot 2018-03-11 at 14 08 40" src="https://user-images.githubusercontent.com/804266/37256943-224a2676-2538-11e8-8cf1-46699ed934c9.png">

**Comment by aupiff** [comment]
So, if I intentionally enter a bad code, I see the error text that starts with something like: `:( 
 1520794597260  %exit`

If I enter the correct code, I just see that empty gray `<code id="err">` element and my urbit emits an error like: `[%bad-oryx 'mirres-samleg-bannec-ponfyr--hanpyx-pinmeb-racdec-talser' {}] `

**Comment by ohAitch** [comment]
The `#err` codebox is always there I think, tho I'm not sure why it got CSSed to be visible while empty.

What is the devtools Network "Response" view of the request like? E.g. for the %auth-fail one(which is supposed to only happen if your password is wrong):

![screenshot 2018-03-12 12 25 52](https://user-images.githubusercontent.com/1857414/37305195-e8d18556-25f0-11e8-9a56-8b9906d58eb0.png)
![screenshot 2018-03-12 12 27 08](https://user-images.githubusercontent.com/1857414/37305197-ea900f34-25f0-11e8-92d5-0cbb7d5ccf4f.png)

**Comment by ohAitch** [comment]
Also, this might be running into the issues mentioned in #941; don't suppose you're running "nightly" urbit off github?

**Comment by aupiff** [comment]
Yep, I'm running latest master.

**Comment by aupiff** [comment]
Looks like a 401 in the network devtools.

<img width="1440" alt="screen shot 2018-03-12 at 19 23 46" src="https://user-images.githubusercontent.com/804266/37314517-f378a086-262a-11e8-8f60-b5cd8b6a7825.png">

**Comment by ohAitch** [comment]
That's the page itself, what about the `auth.json` XHR request for submitting the code?

**Comment by aupiff** [comment]
<img width="1111" alt="screen shot 2018-03-12 at 19 49 52" src="https://user-images.githubusercontent.com/804266/37315161-937a50e0-262e-11e8-9816-c78f4cb9a199.png">
Under the response tab I see:
<img width="1167" alt="screen shot 2018-03-12 at 19 50 25" src="https://user-images.githubusercontent.com/804266/37315174-ade8446e-262e-11e8-93cd-182af5264cc8.png">

I still see `[%bad-oryx 'tanwep-danwyt-rolryp-minbep--togrex-rocsyr-magnyt-lavsyp' {}]  ` on my urbit.

**Comment by aupiff** [comment]
{ship: "pattus-malsec", code: "tindev-motmec-tilbyt-filsyr",…}
code
:
"-----GOOD CODE-----"
oryx
:
"bitnyl-nortug-fogrum-hacpes--fanwyx-landeg-fasner-racteb"
ship
:
"pattus-malsec"

**Comment by ohAitch** [comment]
huh okay 200, that's weird

and the preview/response?

(bad-oryx is cosmetic, though would be an error if we cared more about CSRF; I guess it points to the session not being recognized? But like I can log in from incognito successfully myself)

**Comment by aupiff** [comment]
Preview & Response both say "failed to load response data". It might be that I messed up my nginx config... pasting my current config below.

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name boustro.com www.boustro.com;
    return 301 https://boustro.com$request_uri;
}

server {
    listen 443 http2 default_server;
    listen [::]:443 http2 default_server;
    server_name boustro.com www.boustro.com;

    root /var/www/boustro.com;

    index index.html;

    location /~ {
        proxy_pass http://127.0.0.1:8443;
        proxy_pass_header  Set-Cookie;
        proxy_pass_header  P3P;
    }

    location /=== {
        proxy_pass http://127.0.0.1:8443;
        proxy_pass_header  Set-Cookie;
        proxy_pass_header  P3P;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    ssl on;
    ssl_certificate /etc/letsencrypt/live/boustro.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/boustro.com/privkey.pem;
}
```

**Comment by aupiff** [comment]
By the way, I am being redirected after I submit my code because to see my `auth.json?PUT` I have to select the `Preserve Log` option in my devtools. It didn't seem like you had to do that to record the XHR request.

**Comment by ohAitch** [comment]
I did not, with the incorrect code it doesn't redirect you anywhere

So it's like getting the response back, parsing it as a success, and refreshing to load the authenticated version of the page. I think you're on the right track with `proxy_pass_header Set-Cookie`: it looks like the cookie gets set on 127.0.0.1, while you want it on boustro.com

**Comment by aupiff** [comment]
Yep that fixed. I'm a web n00b, sorry.

This config makes everything work:

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name boustro.com www.boustro.com;
    return 301 https://boustro.com$request_uri;
}

server {
    listen 443 http2 default_server;
    listen [::]:443 http2 default_server;
    server_name boustro.com www.boustro.com;

    root /var/www/boustro.com;

    index index.html;

    location /~ {
        proxy_pass http://127.0.0.1:8443;
        proxy_pass_header  Set-Cookie;
        proxy_pass_header  P3P;
        proxy_cookie_domain 127.0.0.1 boustro.com;
    }

    location /=== {
        proxy_pass http://127.0.0.1:8443;
        proxy_pass_header  Set-Cookie;
        proxy_pass_header  P3P;
        proxy_cookie_domain 127.0.0.1 boustro.com;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    ssl on;
    ssl_certificate /etc/letsencrypt/live/boustro.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/boustro.com/privkey.pem;
}
```

**Comment by aupiff** [comment]
Well, there are a few console errors that still appear while loading resources, but at least the auth works; if I figure out the rest I'll write up what I did in case others want to do something similar. Not sure if a guide like this already exists.
