### ISSUE TITLE
Mark translation from httr to user-type through json should work

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#67]
Expand the single-layer grab to better handle response translation.

**Comment by galenwp** [comment]
Could you be a bit more specific here?  I don't understand this one.

**Comment by ohAitch** [comment]
Right now, `&my-type &httr …` will fail if `mar/my-type` has a grab-json but not a grab-httr. The old mark translation system could handle that fine, but the old mark translation system was in general too magic; probably some way of registering desire-to-grab without touching either mar/json or mar/httr would be sufficient here.

**Comment by jtobin** [comment]
Closing this one as I think it's a bit too idiosyncratic to be useful more broadly.
