### ISSUE TITLE
Urbit syncing capabilities are in dire need of thorough bug squashing

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#685]
This is meant as a call to action, not critique, so take it easy folks :-)

Basically, for the last couple of months of my intense Urbit usage, sync has always been broken except for the simplest case of the fresh merge. Any elaborate scenario save for fresh home sync between two ships is eventually bound to bork the ships. Sometimes I don't even have a way to reproduce those, because they appear only after clay history has accumulated some stuff. Other times it is not clear what is happening. 

There are simply no diagnostic messages, which complicate bug tracing even further. 
I have garbage collected 3 moons just in one evening due to unexplainable sync bugs. 

My idea to fight against this, syncing being especially important as this is basically emanation of the Urbit network - transfer of data between urbit entities is to have the following:

1. Gather a library of test cases for syncing:
    - test every topology, from moons to star to galaxies in various configurations. 
    - do the above tests for various clay histories. Never test things on just fresh home - this is pretty much useless in light of recent bugs; It always almost works.

2. Automate this using scripts and fakenets:
    - Prepare 10x copies of each class of ships and stuff the clay with elaborate file change histories
    - Make a simple app which exposes '|merge and |sync' over API
    - Write scripts which will use this API to conduct test cases

3. Do not release Urbit unless tests from 2 passed. 

Writing an app which has a simple interface for merge and sync is trivial. 
If no one volunteers (I would like to concentrate on extending Plato right now), I will eventually do this, but hopefully someone will spend an evening on this:

1. {'action': 'sync'|'merge'|'public/private', 'her': desk, 'our': desk, ship: addr}

All we need is an app with an API like this. Then hacking a script to test fakenets using this is easy.

**Comment by ohAitch** [comment]
For the last bit, the hood kiln API is pretty close to this? I can write
the actual json converter

**Comment by mikolajpp** [comment]
I guess so. I am unsure as to whether it passes requests from unauthenticated fake comet?
If it checks for authentication we have to best disable it somehow, because otherwise we will have to grab the passcodes from fakenet ships and do auth before performing anything.

**Comment by mikolajpp** [comment]
Down the road I would like to write integrated test environment for fakenets, tangientially related to the Urbit Harbour that was discussed before. 

MVP for this would be working test harness for syncing.

Something along the lines of: On the left you have library of test scenarios. 
main screen is network topology in the form of interactive graph. Latency between nodes can be adjusted, or simulated randomly (also certain presets, like ~zod in US, stars in Asia for example).
You can add nodes to the graph, choosing the class, starting clay content and so on. Then you press "Simulate" and ships are deployed to some hosting and scripts begin running. More elaborate scenarios will need more than 10 ships, ~zod, and 3 ships of each kind, so that we at least can form sync loops in each class, so in the end it might be even worthwhile to buy some more potent cloud machine (Stuffing a lot of RaspPis into Tlon's basement also an option)

**Comment by ohAitch** [comment]
> I guess so. I am unsure as to whether it passes requests from
unauthenticated fake comet?

The urb.py "lens" interface lets you make unauthenticated requests from
localhost, and in general tries to pretend to be a request-response RPC
mechanism(perhaps too hard)

On Sunday, 25 March 2018, mikolajpp <notifications@github.com> wrote:

> Down the road I would like to write integrated test environment for
> fakenets, tangientially related to the Urbit Harbour that was discussed
> before.
>

Fleet, which is a collection of scripts trying to do this, iirc currently
works on a single machine, and has included multi-machine orchestration
capability at ~some~ point in the past

> MVP for this would be working test harness for syncing.
>
> Something along the lines of: On the left you have library of test
> scenarios.
> main screen is network topology in the form of interactive graph. Latency
> between nodes can be adjusted, or simulated randomly (also certain presets,
> like ~zod in US, stars in Asia for example).
> You can add nodes to the graph, choosing the class, starting clay content
> and so on. Then you press "Simulate" and ships are deployed to some hosting
> and scripts begin running. More elaborate scenarios will need more than 10
> ships, ~zod, and 3 ships of each kind, so that we at least can form sync
> loops in each class, so
>
>  in the end it might be even worthwhile to buy some more potent cloud
> machine (Stuffing a lot of RaspPis into Tlon's basement also an option)
>
+1 would recommend starting up 16-CPU Google Cloud instances for a few
hours at a time, I've done talk stress testing on them before and it really
isn't prohibitive as long as you remember to turn them back off.

**Comment by ohAitch** [comment]
Ofc as the designer of the eyre API, I hold that using it from a script is
not too onerous:
https://gist.github.com/ohAitch/13488b9de2c7fd9dbc0b7bf2439dd46c

Given that all -F network ship passcodes are deterministic :P

**Comment by cgyarvin** [comment]
Yes, I'm aware that %clay is a piece of pumice that looks like basalt until
you step on it.

If you want to do this, Anton will help you integrate these tests and
possibly also even... debug %clay.  Yeah that'd be awesome.

But it's worth noting that we really do need an all-new %clay.  In general,
Urbit moves forward not by debugging subsystems into existence, but by
writing subsystems that work the first time because they are designed
right.  Thinking about this is by no means a mistake (and there are also
some old fora posts about it).  This seems very likely to actually happen
in 2018.

**Comment by mikolajpp** [comment]
Such a test harness would be even more useful for the upcoming clay, if only to make sure nothing ever breaks.

Sync is such a crucial feature for network stability, that I think this is worth dongi.

In any way, we can treat this as a groundwork for new %clay :-)

**Comment by cgyarvin** [comment]
Definitely anyone who fixes sync deserves plenty of dongi for it!

**Comment by mikolajpp** [comment]
As I don't believe in mock ups (if it does not compile, it is not real), but believe in coding, I will hack some elm frontend demos soon. 
My plan is to write another Serious Urbit App (SUA) called "Komandor" (feel free to suggest a different name, though I am sure @ohAitch will find the name familiar ;-)

I had the following Vision Grandeur:

Komandor will not only enable Universe Unit Testing, but will offer one solution to Urbit top. An interface will be be split into to parts. Toolbar, and Universe Map. The map will be the map of urbit universe. Each known ship (from the perspective of host ship) will be visible on a map. Connections will be modelled as visible links. The links length will model a latency metric, i.e. the further the ships are, the higher the latency. The links will also be coloured, to indicate packet intensity. 

The map will be fully interactive, draggable, breathable etc. If a ship on a map is green, it will mean the ship is accesible, ie. we can access its remote console. Thus komandor running on mainnet on simple martian's ship, only his own ship will be in green (unless he managed to steal someone's password ;-))
 
If we run fakenet and are running komandor from zod (a martian custom), all ships will be green.

We will be able to execute hoon scripts by dragging them onto a particular ship on a map (here Plato integration will come handy). 

Clicking on a ship will display an information panel about the ship, as well as offer context menu (open konsole, move to graveyard, regenerate and so on.)

Thus the testing of urbit network capabilities will become just one of Komandor functions. Using "Mass apply" of scripts, we will be able to command ships to form different configurations and make them sync, or make them do pretty much anything. 

In the future Komandor will also become Universal "Urbit Awareness" interface for galaxy, star, planet owners, and posses many management capabilities. 

I am the star owner. What are the network usage patters of my planets? How could I improve my service. Maybe a mirroring Urbit in Asia will make my star better, 
as significant portion of my customers have ships there? 

These kinds of questions will also be answerable through Komandor.

The important thing is that everything will be written in Hoon. The main Komandor app will sit inside each urbit. The only non Hoon part will be a small addon backend for managing actual ships creation in Unix.

**Comment by ohAitch** [comment]
> The only non Hoon part will be a small addon backend for managing actual ships creation in Unix.

Which in turn can just be an RPC script that your urbit calls with arbitary `sh` commands ;)

**Comment by mikolajpp** [comment]
Pretty sure someone wrote http server with bash, small RPC script would be nothing nothing obscene ;-)

Another thought I had, is that Komandor could help establishing the notion of "Network corectness" in Urbit. As Unit test apply to isolated chunks of code and (we hope for), establish "functional correctness", in Urbit functional corectness is not enough. Urbit as a whole has network-emergent functonality, and testing proper would treat this emergent functionality first class.

**Comment by mikolajpp** [comment]
@ohAitch for further work on Komandor, lets stay in touch via Urbit chat.
Once I have some demo, I will send the link there. If your planet is defunct, feel free to ping my planet with new coordinates

**Comment by jtobin** [comment]
Closing as I feel this was meant as a one-time call to action -- it's too broadly-scoped to be useful, otherwise.

**Comment by ohAitch** [comment]
Urbit syncing capabilities instead themselves received thorough squashing :P

**Comment by cgyarvin** [comment]
I think eventually you want to restore the auto commit, but not in a way that expects inotify to work magically.  I think autocommit should happen (a) on console input, (b) after the FS has been quiet for a second or so. Otherwise you run into all kinds of lame things like emacs deleting the file to rewrite.

A way to edit files when cloud hosted, without sshing into your planet, is also urgently need...

**Comment by philipcmonk** [comment]
Inotify is a dead end.  "Autocommit every 2 seconds" is actually not as bad as it sounds, but it will always be a hack.  I still suspect FUSE is the future.  It's been largely untenable because herb/urbit was slow, but that's much less the case now.

> A way to edit files when cloud hosted, without sshing into your planet, is also urgently need...

Even a simple "download a file, edit it, then upload it" cycle wouldn't be too bad for occasional changes.

**Comment by cgyarvin** [comment]
I don’t think Inotify is a dead end *if* you use it only as a hint which is an input to a heuristic process. Mistake is treating it as a command.

The official answer to the client problem is upstream sync from a moon.  But that has to actually be made smooth...

The right answer is a client side editor.  More work but existing JS components can be reused...

**Comment by ohAitch** [comment]
Given things like https://atom.io/packages/remote-atom, directly exposing a
filesystem-like API(which may or may not be basically FUSE) shouldn't be
/too/ difficult
