### ISSUE TITLE
Urbit Proxy - preventing moon IP address leaking

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#689]
Urbit crowd being particularly mindful of privacy issues, there is a following thing of interest regarding 
current Moon architecture:

We can already hide behind our cloud planet in talk.
But there is still theoretical possibility of someone scanning our moon address space.

I did a simple experiment with tcpdump. People running ships on their home PC are "toast". Current IP geolocation services are effing good. They almost identify you to a block (to a district in my case).
If we use a moon instead, we are good, but some malicious actor could still scan our moon address space. 

Most people will probably run only one or two moons. This presents significant danger wrt discovering someone real location. 

Is it possible to hook up into ames on the planet and have a little command like 
`|hide ~mymoon`
to prevent external address resolutions on `~mymoon`. 

Or maybe even 
`|proxy ~mymoon` wherein all traffic to the moon would be proxied through the planet. 

This could be humble beginnings of native Urbit VPN

**Comment by ohAitch** [comment]
nothing is stopping you from sending a thousand |hi's in parallel - or
well, your ISP/the parent planet might object, but that sort of detection
can be put in even in the serial case

**Comment by mikolajpp** [comment]
By parallel you mean requests from the same ship, or spawning a thousand comets and coordinating?

If the first, I can't see how current vere handles that differently. It is not like we spawn worker threads, so a thousand |hi would still take a thousands of seconds to complete, would not they?

**Comment by ohAitch** [comment]
the latency is mostly actual network latency, and not local processing
throughput :P

**Comment by mikolajpp** [comment]
I will, uh, adjust  my opinion on vere performance then ;-)

**Comment by ohAitch** [comment]
Don't adjust it too far!
(In particular, the fora.urbit.org load-time/timeout is a problem of
precisely the sort you first thought)
