### ISSUE TITLE
Talk displays gibberish character in terminal upon channel creation

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#690]
Reproduction: create any channel.

`--------------| %komandor-dev: fit: caps:Y unic:â`

**Comment by Fang-** [comment]
That should be a Unicode checkmark `✔`, to signal Unicode is supported in the `fit`/filter/channel config. This actually used to print nicely for me, but doesn't anymore. Maybe it's a fonts thing? Easiest fix here is to stop being clever and just use `y` instead of `✔`.

**Comment by mikolajpp** [comment]
I can see the unicode checkmark you posted. I can also paste it into console and it renders normally. 
So clearly it must have a different code to that character, or there are some other encoding issues.

**Comment by ohAitch** [comment]
I mean, it's not "being clever", it's notifying you that you just created a
channel that people can post unicode to which your terminal will then garble
(unless it's only that character and urbit is displaying other unicode
fine, but that's the ~intent~ of this sort of inline check at least)

**Comment by jtobin** [comment]
Closing as it's not clear this is an issue.

**Comment by joemfb** [comment]
Their are lots of issues with our output handling -- this specifically points at a current (but low priority) regression. No strong feelings about this issue, the entire output pipeline needs to be redesigned IMO.
