### ISSUE TITLE
Inbox activation for talk

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#697]
Currenty talk model works well only for one or two channels. In reality mixing high volume channels such as urbit-meta with low-volume ones (such as plato-dev, which is mostly announcements), does not work great. 

Here is one idea how to fix it (or maybe this is already possible?)
Instead of printing messages from all channels, only display notification for inboxes with (notify set to on). Then upon switching to a channel actual messages would be displayed.

**Comment by jtobin** [comment]
Closing as this is too broadly scoped.

**Comment by ohAitch** [comment]
"Add per-channel mute flag, don't print muted channel messages until you switch to the channel" feels pretty concrete?
