### ISSUE TITLE
:talk uses unreadable conventions for its JSON API

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#700]
So I have been looking at talk, and  its JSON API uses weird tri-letter convention.
I don't see any reason for that, and it makes it hard to understand what's going on without delving into hoon code. 

I believe we should use descriptive name for public facing APIs, such as eyre is already using, or which Plato implemented. Shortening everything to 3 letter codes goes against usability. API, unlike Hoon code, will oftentimse be read without any context, and currently it is difficult to re-use it in other applications without reading through :talk code, which should not be the case. 

I propose to change all tri-letter codes, such as 
```
cos
rem
loc
pes
sep
lin
pat
```
and so on, into proper descriptive names. 

If the same is true for :tree, we should also go and change that too.

**Comment by Fang-** [comment]
@c-johnson and I have talked a little bit about hall's API recently. They've been using it extensively for the ongoing frontend work, and they've identified a few potential pain points that we'll want to address.

Surprisingly, the naming wasn't mentioned. Currently, making developers not need to look at hoon code is not a priority (and I'm not sure if that'll ever be a goal we strive for exactly). The hall structures file and its documentation is readable *enough*.  
That said, this is clearly not space-rated hoon. When we get to making changes to its API, better faces in the structures file are definitely on the to-do list.

(Though, maybe we'll end up deciding it's not great to mirror hoon structures into JSON after all, making the structures file irrelevant in this, but we'll see how it all goes.)

In the mean time, no need to dive into hoon code per se. There's actually [documentation for its API](https://urbit.org/docs/hall/interface/) you can use as reference.

**Comment by mikolajpp** [comment]
I mean, plato is also mirroring its structures, but they look like this:

```
+=  job  [type=job-type id=@ud stat=job-status src=tape blob=(unit hoon) err=(unit job-error) res=tape]
```

I could make it all into `sta, blo, typ`, but what is the point?
I can't see how naming structures which are reused in the entire program using u3 naming convention is going to help us ;-)

If I had any vote, I would vote to giving proper descriptive names to anything that is not local part of the code. So stuff in /sur, /lib should use user-friendly naming, so that going back after a month I don't have to recall which 3-letter code meant which.

**Comment by mikolajpp** [comment]
Also another point of using descriptive names is that oftentimes I don't even need to consult documentation. It is enough to look at the API as is to understand what's going on. I think this in itself is a good reason to rething naming conventions.

**Comment by Fang-** [comment]
What you describe is exactly what I intend to change when I finally get to touching hall again. Three letters is just too few! (:

**Comment by mikolajpp** [comment]
More about not requiring developers to stare at hoon code. 
I think in principle it should be required when it is really required. In the long-distant future, 
when many important arvo components have stabilized, a lot of times it will not be necesarry to touch hoon code to write an app, at least until we get native VM running in the browser and Hoon UI language. 

At this stage not having to learn hoon and be able to write Urbit apps in a chosen language is actually a great selling point. 

Over time those hooked on Urbit will learn hoon anyway, but being able to just hack a quick app or two in  Elm and have it instantly work with Urbit would be a great thing.

**Comment by jtobin** [comment]
Closing this as every component of Urbit uses unreadable conventions for its API.

(Ha ha.  But what I mean is that this is a broader issue that exists throughout the codebase, thus I think an issue that focuses on the problem in `:talk` in particular doesn't really accomplish much.)
