### ISSUE TITLE
New Eyre - New Hope

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#702]
Since Plato v0.3.0 will require router and possible other functionality to make it work, after Plato v0.2.0 I decided to temporarily freeze its development and shift focus to eyre itself. 

A long time ago I proposed UP3, which I will finally get to. After implementing UP3, I would like to eye re-designing eyre itself. With new %ford coming up, it is certainly something beneficial, as it would even more speed up the public face of Urbit. 

New Eyre should provide at least the following:
- Significantly speeding up requests, if possible. Request to google server several hundreds miles 
  away take around milisecond. Plato request to eyre sitting just here take 500x time longer to complete. I am not sure where latency comes from, but it seems unlikely that from the plato code execution itself, which in dojo is almost instaneous. 
- Redesign of the eyre APIs - with the focus on uniformity, predictability, eliminating reduntant API endpoints and so on. 
- Passing of Marks - With alpha of elm-urbit released, marks should be passed from eyre with preserving their data type, and then seamlessly reconstructed using elm-urbit. We should probably provide stock mark decoders in elm-urbit for all stock marks convertible to JSON.
- Routing capabilities for SPAs
- Some other areas which I am not aware of (...)

**Comment by mikolajpp** [comment]
This probably should be best developed against the cc-branch - if it is possible at this stage. 
It will take at least solid couple of months to have anything, so we should treat this with a longer time-horizon. 

I will definitely require assistance and coordination from @ohAitch, which I believe, originally implemented %eyre? :-)

**Comment by ohAitch** [comment]
Not originally, but rewrote the current implementation ground up yeah!

To address your points:
> Significantly speeding up requests, if possible. Request to google server several hundreds miles 
  away take around milisecond. Plato request to eyre sitting just here take 500x time longer to complete. **I am not sure where latency comes from**, but it seems unlikely that from the plato code execution itself, which in dojo is almost instaneous. 

A good first step might be turning on `-DGHETTO` in the Makefile(mesonfile?), `|verb`, and looking at the timing information for how long each arvo-level event is taking. My bet it most of it is in ford, but this may be pride talking, I've only rewritten like *half* of that :)


> Redesign of the eyre APIs - with the focus on uniformity, predictability, eliminating reduntant API endpoints and so on.

You might want to look at the [https://github.com/ohAitch/arvo/tree/cleaner-http](cleaner-http) branch, which among other things refactors the uniform two-letter `/~/xx/...` URL names to instead be descriptive – I'm really surprised you cited those as user-friendly in #700, actually. The main feature disabled on that branch is single-sign-on, which I think will not be necessary in MVE; but also feel free to treat that branch as \~inspirational\~ and pick and choose whichever refactorings still look useful :P


> Passing of Marks - With alpha of elm-urbit released, marks should be passed from eyre with preserving their data type, and then seamlessly reconstructed using elm-urbit. We should probably provide stock mark decoders in elm-urbit for all stock marks convertible to JSON.

Not sure what precisely you mean by "mark decoders", given they're already in JSON; is there a standard convention for annotating JSON with Elm types, using a `@@type@@` key or such? A more ambitious plan might be writing an elm implementation of the mold system, and passing the mark data as `++jam` or at least untyped noun-json; but I'm not sure how much of an undertaking that would be, and whether auto-generating elm based on `sur/` files even makes sense.


> Routing capabilities for SPAs

I think **cleaner-eyre** involved a `foo.urbit.org/:talk/path/passed/to/javascript` url format, but maybe that part never got implemented. It's also possible that there was more extensive routing involving talking to the app during the first HTTP request: I certainly remember that when gall v1 was written a few years ago, there was just a `++page` app interface arm that you could generate arbitrary html from by path.

> Some other areas which I am not aware of (...)

I'm not on my work computer right now, but I'll look around for any other areas *I* am: I remember writing up extensive wishlists for various parts of urbit, and might even be able to find some of them. Have you looked through the [%eyre issue tag](https://github.com/urbit/arvo/labels/%25eyre) for anything UI-related?

**Comment by mikolajpp** [comment]
@ohAitch 

By passing marks at the very minimum I mean tagging passed JSON properly. 
Currently, everything that comes out of eyre is tagged with `json` mark. 

This is very bad for elm<->urbit bridge, because it essentially means your mark codecs inside Elm have to camp on a particular /wire, and bind proper decoders per wire. With mark tagging, Elm mark codecs will dispatch based on mark field. 

Autogenerating elm decoders from sur/ is actually a very good idea, but I am not sure if I follow. Given sur/ hoon file, there is an easy way to turn given mold into elm structure decoder - unsure what passing mark data as jam would mean? Is it binary encoding of the nouns?

**Comment by ohAitch** [comment]
It would not be difficult to add a `"_mark":foo` in every `mar/foo++grow++json`, certainly :P

`++jam` is the native binary encoding yeah. It doesn't have all the json name/atom-type/human-readability overhead, which `sur`-derived Elm could just rehydrate using the `mold` algorithms.

**Comment by mikolajpp** [comment]
@ohAitch we should hop on skype some day to talk about the state of %eyre; 
We finally need to get it done, since I would like to release the elm-urbit library, for which we will need 
to at least build in the routing...

**Comment by jtobin** [comment]
Closing this one as `%lighter-than-eyre` is the new hope for the time being.
