### ISSUE TITLE
Difference between "{" and "\{"

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#706]
For some reason this:
```
!:
%-  scan
    :*  
    "{1 9}"
    (just 'a')
    ==
```

Nests fails. But when I change to `\{` it correctly syntax-errors. 
What is causing this?

**Comment by ohAitch** [comment]
"foo bar b{(reap 10 ’a')}z" is the [string interpolation](https://urbit.org/docs/hoon/atom/knit/) syntax; trying to interpolate [1 9] into the (list @tD) is indeed a nest-fail.

**Comment by ohAitch** [comment]
I think currently the compiler spits out errors *by crashing*, so this might be somewhat difficult; parsers on the other hand do produce approximately `[location (unit result)]`, and as `ream` is just `(scan (trip txt) vast)`, you can just call `((full vast) [1 1] txt)` directly. (Otoh, you will not get a *type* from a parse error :P)

**Comment by ohAitch** [comment]
I guess if you want to fiddle with the `++mule` jet to make a variant that's similarly type-cheaty but produces raw ++mink `%spot`/`%mean`/etc hints instead of a rendered stack trace, you could get something *more* structured, at least for `[path [start-row start-col] [end-row end-col]]`? But if you want to avoid parsing the compile errors themselves back from text, that would probably involve mucking around in where those errors are generated a bunch. (`~| (en-json ...)` perhaps?)

**Comment by mikolajpp** [comment]
That is too advanced. I am yet a humble hooner. For now I am happy I have a functional reparser. 
I might try to do this kind of magic in the future, hopefully after we have got new parser interface :P

**Comment by ohAitch** [comment]
```
pax = [a-z0-9/-]*
num = [0-9.]*
/{pax}:<[{num} {num}].[{num} {num}]>
```
should not be \~that~ hard to extract in either hoon or elm, fair ^-^

**Comment by mikolajpp** [comment]
I am afraid it is too late. I am already in parsers' power :%)

```
    %-  scan
    :*  where
    %-  ifix
        :*  [(just '{') (jest '}\0a')]
        ;~  (glue gaw)
            dem
            dem
        ==
        ==
```

**Comment by ohAitch** [comment]
I think you want

```
    %+  scan
      where
    %+  ifix
      [(just '{') (jest '}\0a')]
    ;~  (glue gaw)
        dem
        dem
    ==
```

but otherwise looks good!

**Comment by mikolajpp** [comment]
@ohAitch 
I think my Hoon skills need a little direction here:
```
%-
%~  parse-location
|_  a=@
          ++  parse-location
              |=  where=tape
                   %+  scan
                       where
                       ;~  pfix
                           (jest '/:')
                           total-location
                        ==
          
          ++  total-location
              %+  ifix
                  [(just '<') (just '>')]
                  ;~  (glue dot)
                  parse-loc-pair
                  parse-loc-pair
                  ==
          ++  parse-loc-pair
              %+  ifix
                  [(just '[') (just ']')]
                  ;~  (glue gaw)
                      dem
                      dem
                      ==
          --
    0
    ==
"/:<[2 120].[34 101]>"
```

I would like to get rid of that dummy sample argument to core. I tried to use `|%` but it nests fails on me when using `%~`...

**Comment by ohAitch** [comment]
I think you want just `=<  parse-location` :P 
Or even use the ford implicit auto-`=~`, so
```
|%
++  parse-location
  |=  where=tape
  %+  scan
    where
  ;~  pfix
    (jest '/:')
    total-location
  ==
::
++  total-location
  %+  ifix
    [(just '<') (just '>')]
  ;~  (glue dot)
    parse-loc-pair
    parse-loc-pair
  ==
::
++  parse-loc-pair
  %+  ifix
    [(just '[') (just ']')]
  ;~  (glue gaw)
      dem
      dem
  ==
--
::
(parse-location "/:<[2 120].[34 101]>")
```

(also tightened up the indents: 4 spaces is definitely unidiomatic, and unlike most functional languages hoon uses [backstep indentation](https://urbit.org/docs/hoon/syntax/) to avoid interminable rightward drift)
