### ISSUE TITLE
Sync stuck until |hi

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#714]
I observed weird behavior on the crowdsale galaxies just now.

~zod has long since pushed out the recent update to most of its children, yet most of the crowdsale galaxies hadn't received the sync.
When I executed a `|hi ~zod` on one of them, it came back with a `hi successful` followed by a `~zod is ok`, and then it started amesing in the sync.

So it appears as if networking with ~zod had gotten stuck for them.

For the record, I used this to kick the sync on the following galaxies:
~pub, ~bus, ~dev, ~ten, ~def, ~pem

**Comment by jtobin** [comment]
Closing as I don't think this one captures the underlying issue enough to be useful.
