### ISSUE TITLE
Redundant unsubscribe events when subscription ends

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#715]
Observed on a comet that had done a brief subscription to ~binzod (`;join ~binzod/urbit-meta/now/~m1`) a while before it processed a ton of messages. The comet got multiple `off + ~binzod/urbit-meta` messages.

Assuming this happens because for every diff it tries to send, it checks whether a subscription has ended, but doesn't remember this when processing the next diff.

It's actually kind of nice to have these print redundantly, so that we can see when we're getting/sending redundant changes. These should be fixed.

**Comment by jtobin** [comment]
Closing as I think this one is too isolated/obscure to be useful -- it needs some sort of minimal reproduction case.
