### ISSUE TITLE
Comets running off base desk is confusing

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#720]
[/lib/hood/drum.hoon](https://github.com/urbit/arvo/blob/master/lib/hood/drum.hoon#L81-L82) says that everyone boots their default applications off the home desk, except comets. They boot them off base.

Is there a reason for it to be this way? Running things from home by default makes sense to me, and I'm not sure why that should be different for comets.

This bit me when trying to configure a hall filter on the current stream comet. Changes didn't seem to be sticking, until I tried making them to the base desk instead.

**Comment by jtobin** [comment]
Closing this for the time being as this one hasn't attracted any attention in over a year, and it's not clear that the described behaviour is actually an issue.
