### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by msutherl** [urbit/arvo#723]
This repository needs a README so that it is not completely opaque to new contributors

**Comment by ohAitch** [comment]
I would rather avoid a proliferation of allcaps-named extensionless text-files in the "boot-time urbit contents" toplevel. We should perhaps have more extensive documentation in `web/`, but it'll have a valid urbit filename; `LICENSE` is certainly going as soon as we move to a proper monorepo.

**Comment by ohAitch** [comment]
(alternately, we could have a `LICENSE` `README` `CONTRIBUTING.md` `actual-arvo/` github layout, but this seems like it would have other problems)

**Comment by joemfb** [comment]
Doesn't the clay unix mount ignore files without extensions (or where the extension has no corresponding mark)?

**Comment by belisarius222** [comment]
Is there a compelling reason not to add .txt to the other files?

**Comment by Fang-** [comment]
Resolved in #1121.
