### ISSUE TITLE
Callback url expects user id in path or query string

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#73]
Isn't set up to handle Twitter "here, have a token at a static url, you can use it to find out what account it represents if you really care" flow.

Triaged: p-low

**Comment by galenwp** [comment]
I'm confused, Urbit doesn't capture the query string, or we don't write to it?

**Comment by ohAitch** [comment]
Twitter doesn't / let urbit provide the "which account is this token for" information in the redirect url, which means eyre can't route the token to the correct identity's secret storage.

**Comment by jtobin** [comment]
Closing as I think this one is not clear enough to be useful.
