### ISSUE TITLE
Security drivers don't check that requested identity is granted by service provider

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#74]
The oauth libraries add "login hints" that select the correct variant if the user is not logged in(or logged in with multiple accounts including the intended one), but this is silently overridden if the wrong account is logged in. Correct behaviour here would be making an "inspect token" call checking that the username which provided it matches the `usr` parameter passed into the driver.
#73 makes this somewhat difficult in the general case

Triaged: P-low, multi-user support is largely demonstrative.

**Comment by ohAitch** [comment]
Further thoughts:
- the "defaulted" `~.` identity would work better as a symlink, delegating to some existing name if one already exists
- Something that might be necessary here is a "migrate identity" method: upon getting a token, the token is used to authenticate a "what is my username call", whose result is used to set the true `usr` of the driver. If the provided `iden` was `~.`, set up forwarding; if it was something other than what was received, stash the token for further use by the actual `iden`, print an error, and ask the user to actually log in with the requested user name.
  + with the option to cancel the app request which wanted them to be logged in thus; for that matter, generic "log out"/"log out + blacklist username as someone whom i definitely am not" functionality

**Comment by jtobin** [comment]
Closing this one as I think it's a bit too idiosyncratic to be useful more broadly.

**Comment by ohAitch** [comment]
The "security driver" system is largely gone nextbreach right?

**Comment by philipcmonk** [comment]
That's correct
