### ISSUE TITLE
=, doesn't allow mutation

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#744]
I'm not sure if this is intended behavior or a bug, but I was surprised to find the following doesn't work:
```
=/  a  [b=2 c=3]
=,  a
=.  b  7
b
```
This errors out with `-tack.b`.

The `=.` isn't allowed on a face exposed by a `=,` implying that it's a read-only exposure.

**Comment by cgyarvin** [comment]
That should work, it’d be a fun one to fix

**Comment by cgyarvin** [comment]
Sorry, I was wrong, this shouldn't work.

The reason is that you can only mutate a wing of the subject, and when you
say b you mean `b:a`.  That's all =, does for you -- replaces `b` with
`b:a`.  But you can't mutate `b:a`, even if you could mutate `b.a`.  Hoon
isn't that smart and I'm not sure it should be.

**Comment by joshuareagan** [comment]
How about using `b` for `?+  b  default ...` ?  I'm getting a `mint-coke` crash when I attempt this...

**Comment by cgyarvin** [comment]
Yeah it’s still not a wing - a.b.c.d is a wing, a.b:c.d is not

**Comment by cgyarvin** [comment]
That’s a totally different horrible hack — see under +tiki.  Thinking of removing it.

**Comment by joshuareagan** [comment]
That clears it up for me.  Thanks

**Comment by ohAitch** [comment]
in short, ?= proper only works on wings, so ?=((add 2 2) %4) gets compiled
to =/(did-add-2-2 (add 2 2) ?=(did-add-2-2 %4))
(except with axes instead of faces)

**Comment by joshuareagan** [comment]
Thanks @ohAitch , that's helpful to know.

**Comment by Fang-** [comment]
Closing this as won't fix.
