### ISSUE TITLE
Clay permissions scry is too opaque

### ISSUE THREAD

**Issue by ixv** [urbit/arvo#749]
The `+dict` structure returned by scrying for clay permissions is too opaque a structure.

The issue is inside `+rule`, it refers to a `(set whom)` where `+whom` is `(each ship @ta)`, and the `@ta` is a key in a map to permissions groups, internal to clay. The values of this map are ignored in a scry, ie: when you scry for permissions, you can get these black box `@ta` keys returned to you.

**Comment by Fang-** [comment]
You can send a `[%crew our=ship]` move to clay to get back a `[%cruz cez=(map @ta crew)]` (where `crew` is `(set ship)`).

If we were to send back "unfolded" permissions here, then there'd be no way to get the relevant permission groups from a rule.
