### ISSUE TITLE
Testnet error in /lib/hall-json

### ISSUE THREAD

**Issue by keatondunsford** [urbit/arvo#751]
Just hit this on testnet ~marzod, urbit/arvo@fb346834:

```
[ %diff-bad-ack
  ~
    u
  [ ~
      u
    [ p=%mack
        q
      ~[
        [%leaf p="ford: vale %hall-prize ~timpyx-nocdux"]
        [%leaf p="ford: check [%hall-prize [p=~tocwer-darlud q=%home r=[%ud p=132]] ~timpyx-nocdux]"]
        [%palm p=[p="." q="-" r="" s=""] q=[i=[%leaf p="find"] t=[i=[%rose p=[p="." q="" r=""] q=[i=[%leaf p="red"]
 t=[i=[%leaf p="a"] t=~]]] t=~]]]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[236 11].[236 16]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[236 7].[236 16]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[230 16].[237 7]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[230 5].[237 7]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[229 5].[237 7]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[228 5].[237 7]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[52 3].[352 5]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[51 3].[352 5]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[8 1].[601 3]>"]
        [%leaf p="/~tocwer-darlud/home/0/lib/hall-json:<[6 1].[601 3]>"]
        [ %rose
          p=[p=":" q="" r=""]
            q
          [   i
            [ %rose
              p=[p="/" q="/" r=""]
                q
              [ i=[%leaf p="~tocwer-darlud"]
                t=[i=[%leaf p="home"] t=[i=[%leaf p="~2018.6.13..23.53.15..f833"] t=[i=[%leaf p="sys"] t=[i=[%leaf
p="vane"] t=[i=[%leaf p="ford"] t=~]]]]]
              ]
            ]
            t=[i=[%leaf p="<[1.306 24].[1.306 52]>"] t=~]
          ]
        ]
      ]
    ]
  ]
]
~marzod:dojo>
```

This crash appears to be coming from Logan's testnet planet.

cc @Fang- @loganallenc

**Comment by keatondunsford** [comment]
@Fang- Is this the same error that forced us to breach a continuity era or two ago where changes to `/sur` or `/lib` can't get updated without causing type-mismatch problems between up-to-date ships and ships that haven't received the updates?

**Comment by Fang-** [comment]
Are you sure that the commit you linked is the version of all files on `~tocwer-darlud`? The stack trace [points to](https://github.com/urbit/arvo/blob/mve/lib/hall-json.hoon#L236) a line that's not even as long as the pointer. It's also find-erroring on `red.a` if I'm parsing that correctly, which I don't think has ever existed in `hall-json`...

**Comment by keatondunsford** [comment]
Ah, @loganallenc was messing around with the Hall data structures to add a read/unread message type. We breached it in on the testnet, and all is good.

We really do need to design some interface for upgrading app data structures, though, so one change on a random ship can't bring down the whole network.

**Comment by Fang-** [comment]
> so one change on a random ship can't bring down the whole network.

But it doesn't? The `%bad-ack` is just saying delivery of one message failed. It might keep failing if it tries to send to the same ship again, but it certainly won't keep it from sending messages to other ships.

Actual interface versioning is on the to-do list for new hall. I don't expect to put it in for current hall, since it's a non-trivial change, and I hope to not make significant changes to current hall's structures either. (At least, not outside of breaches.)

**Comment by keatondunsford** [comment]
> it doesn't

Got it. It just looked scary.
