### ISSUE TITLE
Markdown shorthand <ol> splits list into <ol> / <ul>

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/arvo#757]
.md syntax like:
```
1. Latin
- Latin Variations incl. Cryllic
- Hoon ligatures
- Chinese
- Japanese
- Korean
```

renders as:
```html
<ol>
    <li>latin</li>
</ol>
<ul>
   <li>Latin Variations incl. Cryllic</li>
   <li>Hoon ligatures</li>
    ...
</ul>
```

but should render as one <ol>

**Comment by ohAitch** [comment]
Is this `udon`, or `.md`? For the latter, this is in line with the [commonmark translation](https://spec.commonmark.org/dingus/?text=1.%20Latin%0A-%20Latin%20Variations%20incl.%20Cryllic%0A-%20Hoon%20ligatures%0A-%20Chinese%0A-%20Japanese%0A-%20Korean); if you did mean unmark, could you elaborate on what the "as one" HTML would look like? Something like `<ol><li>latin <ul><li>...</li></ul></li></ol>`?

**Comment by Fang-** [comment]
Pinging @gavinpatkinson, can you clarify?

**Comment by gavinpatkinson** [comment]
This is in reference to syntax rendering in Landscape

**Comment by jtobin** [comment]
Closing this as it hasn't been followed up on, and it's not clear it's still an issue.
