### ISSUE TITLE
On Testnet, $is endpoint on Eyre sometimes breaks.

### ISSUE THREAD

**Issue by loganallenc** [urbit/arvo#763]
When attempting to bind to the last 100 messages in the inbox, or another circle, I sometimes receive:
http://tagfen-baclet.test.urbit.org:8080/~/is/~tagfen-baclet/hall/circle/inbox/grams/-100.json?PUT

`<html><head><link rel="stylesheet" href="/lib/base.css" /><title>server error</title></head><body><div id="c" class="err"><pre><code>%exit<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.727 46].[1.727 48]&gt;<br />[%duplicate /circle/inbox/grams/-100]<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.727 31].[1.727 49]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.727 7].[1.729 68]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.726 41].[1.729 68]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.111 60].[1.111 65]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.111 43].[1.111 66]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.451 22].[1.451 54]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.451 18].[1.451 55]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.450 9].[1.453 11]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.389 7].[1.458 9]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.388 21].[1.458 9]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.385 7].[1.385 29]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.384 7].[1.385 29]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.382 7].[1.385 29]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.381 7].[1.385 29]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.380 7].[1.385 29]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.132 15].[1.132 22]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.132 11].[1.132 22]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.132 7].[1.134 24]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.131 7].[1.134 24]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.130 7].[1.134 24]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.129 7].[1.134 24]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[1.128 7].[1.134 24]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[676 9].[676 57]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[675 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[674 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[672 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[671 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[664 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[663 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[662 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[661 7].[679 43]&gt;<br /><a href="x-urbit:/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre">/~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre</a>:&lt;[660 7].[679 43]&gt;<br />  /~tagfen-baclet/home/~2018.7.16..20.38.45..f6a7/sys/vane/eyre<br />  &lt;[659 22].[679 43]&gt;<br /></code></pre></div></body><script src="/~/on/0v0.js"></script></html>
`

**Comment by ohAitch** [comment]
```
%exit
[%duplicate /circle/inbox/grams/-100]
```
sounds like you're trying to add two copies of the same subscription to the same `oryx`?

**Comment by loganallenc** [comment]
Hmm, I think that is what is happening. Thanks.
