### ISSUE TITLE
++limo in hoon.hoon

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#768]
Current `++limo`:
```
++  limo                                                ::  listify
  |*  a/*
  ^+  =<  $
    |%  +-  $  ?~(a ~ ?:(*? [i=-.a t=$] $(a +.a)))  <-- type checker hack
    --
  a
```

But with current type checker the following works as well
```
++  limo                                                ::  listify
  |*  a/*
  ^+  =<  $
  |%  +-  $  ?~(a ~ [i=-.a t=$(a +.a)]) <-- no hack
    --
  a
```
without the hack(?)

Same applies for `++homo`

**Comment by mikolajpp** [comment]
I have update the code listening, mistakenly duplicated them (for those receiving by mail)

**Comment by ohAitch** [comment]
For limo this makes sense, but homo is all about introducing the i=?:(*?
&1.a &elsewhere.a) fork, regardless of the original list possibly being
?([@ @ @ ^ ^ ~]) or w/e

**Comment by mikolajpp** [comment]
How about this:

```
++  homo
|*  a=(list)
?~  a  ~
=+  e=,i.a
^+  =<  $
  |%
  +-  $  ?~(a ~ [i=e t=$(a t.a)])
  --
a
```
It almost works, with the exception of 
```
(limo ~[1 1 2])
```
producing strangely
```
[i=1 t=~[2 3]]
```
which is a strange mix of faceless and facey list. 
Is this a bug? Can't figure out why this happens.

**Comment by ohAitch** [comment]
I think that's just a pretty-printer bug introduced by the most recent hoon revision? Like, current gates like `weld` also do that iirc.

Does it work for `(homo ~[1 [2 3] 4])`? The result type should be `(list ?(@ [@ @]))`

**Comment by mikolajpp** [comment]
Wait, but the stock `homo` does not work on this example...
```
(homo ~[1 [2 3] 4])
```
nest-fails on hoon.hoon `homo` as usual.

**Comment by ohAitch** [comment]
Maybe I mean `limo`? At least one of them should unify types when you say `(sy %a %b %c ~)` or w/e

**Comment by mikolajpp** [comment]
Ah wait, I made a mistake in the previous post.
The
```
(limo ~[1 2 3])
```
was meant to be 
```
(homo ...)
```

The new limo works the same as the stock one, i.e. it will put correct 
faces on list-like things.
So the example is actually for homo working too, module that weird pretty-printing

**Comment by ohAitch** [comment]
But will it put correct types on list-like things?

**Comment by ohAitch** [comment]
`(sy %a %b %c ~)` should produce a `(set ?(%a %b %c))` and not just `(set %a)`, and I'm pretty sure it uses both internally.

**Comment by jtobin** [comment]
Closing as it's not clear this is really an issue.
