### ISSUE TITLE
proposal: +jab:by to transform a value in a map

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#771]
I think this would be a useful function for maps. It should be more efficient and convenient than the current approach of a `+got:by` followed by a `+put:by`. It avoids both a second traversal and a tree rebalancing, since `+map` treap ordering isn't affected by values, only by keys. It should really just be some lookups followed by a stack of nock 12s to replace increasing subtrees.

This is loosely inspired by Haskell's lenses. In new Ford, we use a special-case version of this extensively: https://github.com/urbit/arvo/blob/56c8f49966e1146a7ac8e28a815fafcd88c1bc9d/sys/vane/turbo2.hoon#L4982-L4993

Here is an untested general implementation:
```
  ::  +jab:by: replace the value for a key, producing new value and new map
  ::
  +-  jab
    ~/  %jab
    |*  [key=_?>(?=(^ a) p.n.a) fun=$-(_?>(?=(^ a) q.n.a) _?>(?=(^ a) q.n.a))]
    ^+  [_?>(?=(^ a) q.n.a) a]
    ::
    ?~  a  !!
    ::
    ?:  =(key p.n.a)
      =/  res  (fun q.n.a)
      [res a(q.n res)]
    ::
    ?:  (gor key p.n.a)
      =^  res  l.a  $(a l.a)
      [res a]
    ::
    =^  res  r.a  $(a r.a)
    [res a]
```

**Comment by eglaysher** [comment]
[I prototyped this](
https://github.com/urbit/arvo/commit/6ed337d02e89e643d1581a0d841fed76beae1edd). Then [added crashing on non-existent keys](https://github.com/urbit/arvo/commit/6d1c647b51e84f134b30735df78930a2d017e1f9) back in.

**Comment by joemfb** [comment]
@eglaysher, this appears to be in. Can this issue be closed?
