### ISSUE TITLE
triple exotic base adresses fall outside of urbit entity class

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#772]
I noticed hoon parser allows exotic base triple addresses
```
~marzod-marzod-marzod
```
for instance, as valid, even though they do not correspond to any urbit entity, 
and any function expecting a `@p` to be one of 
galaxy, star, planet, moon or comet can be fed such an address.

**Comment by mikolajpp** [comment]
Though more a quirk rather than a bug, such triples can be used pretty much anywhere. 
For example, in talk they will get interpreted as an (invalid?) moon etc.

**Comment by cgyarvin** [comment]
Yeah the idea of 48-bit moons is latent but could be useful.

**Comment by eglaysher** [comment]
You have to manually `+ticket` them, but I already use them for my moons. Easier to remember and type.

**Comment by mikolajpp** [comment]
Ha. So we have half-moons too. I could see people using 
them as names in games and similar, or otherwise treat them as more valuable subclass 
of moon space. Essentially 'next best thing after planet'.

**Comment by belisarius222** [comment]
Looks like this is not a problem. Closing.
