### ISSUE TITLE
jet being identified without hint??

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#776]
I'm not sure what's going on here, but this seems like a bug of some kind to me.  Is vere is detecting jet code without a hint?

I'm passing a simple list and gate to another gate.  The latter is basically a dry version of `+skim`:

```
> %.  [`(list @)`[2 3 4 5 ~] |=(a=@ (gth a 3))]
  |=  {a/(list @) b/$-(@ ?)}
  |-
  ^+  a
  ?~  a  ~
~bitnus_patmus:dojo< ?:((b i.a) [i.a $(a t.a)] $(a t.a))fine: parent not found (639a906)
improper core 6bf72803
improper label: [%skim %two %one 'k143' 0]
  ?:((b i.a) [i.a $(a t.a)] $(a t.a))
\/ford: build failed ~[/g/~bitnus-holleb-rocmeg-fotfer--migsum-nidsym-hilput-pa\/
  tmus/use/dojo/~bitnus-holleb-rocmeg-fotfer--migsum-nidsym-hilput-patmus/inn/h
  and /g/~bitnus-holleb-rocmeg-fotfer--migsum-nidsym-hilput-patmus/use/hood/~bi
  tnus-holleb-rocmeg-fotfer--migsum-nidsym-hilput-patmus/out/dojo/drum/phat/~bi
  tnus-holleb-rocmeg-fotfer--migsum-nidsym-hilput-patmus/dojo /d //term/1]
\/                                                                             \/
```

But when I take the `|-` out, it runs fine:

```
> %.  [`(list @)`[2 3 4 5 ~] |=(a=@ (gth a 3))]
  |=  {a/(list @) b/$-(@ ?)}
  ^+  a
  ?~  a  ~
  ?:((b i.a) [i.a $(a t.a)] $(a t.a))
~[4 5]
```

**Comment by cgyarvin** [comment]
It’s possible.  Paul has a new, much more correct jet detector...

**Comment by joemfb** [comment]
Jet *registration* is by hint -- jet *detection* is by battery. I think the current implementation fails to validate the parent core, which can lead to collisions.

**Comment by joemfb** [comment]
The new jet dashboard ("hashboard") is on release-candidate. I'm not able to reproduce this with an up-to-date vere. @joshuareagan, can you confirm?

**Comment by joshuareagan** [comment]
LGTM!
