### ISSUE TITLE
%bad-text trips up hall JSON conversion

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#779]
Haven't tested this in detail yet, but pretty sure these are cause and effect.

Currently, loading webtalk when you're subscribed to urbit-meta (and in the future, probably scrolling upward) will give `%mo-cyst-fail` on the `wash` call [here](https://github.com/urbit/arvo/blob/master/lib/hall-json.hoon#L69).

Part of the message scrollback is an evaluated-hoon message containing `` `?(cord @)`123.456`` and its result. When the cli tried to print the result, it gave `%bad-text` instead. That's probably also why the `wash` call is failing.

This should, of course, not fail as spectacularly as it does right now. It prevents webtalk from loading further scrollback.

**Comment by jtobin** [comment]
Closing this as I'm under the impression that webtalk is no longer really a thing, and so this is no longer immediately relevant (in the sense that there's not an immediate way to realise this issue).  Feel free to reopen if that's not right.
