### ISSUE TITLE
tarp mold with default fields

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#782]
`++tarp` is defined like this:
```
++  tarp  {d/@ud h/@ud m/@ud s/@ud f/(list @ux)}        ::  parsed time
```
Is the below line correct behaviour? 
I would except s to be 56
```
> (tarp 63.701.625.176 7 52 56)
[d=63.701.625.176 h=7 m=52 s=0 f=~]
```

**Comment by Fang-** [comment]
You generally don't want to actually call the type to cast your data, but alright:

```
> (tarp 63.701.625.176 7 52 56)
[d=63.701.625.176 h=7 m=52 s=0 f=~]
> (tarp 63.701.625.176 7 52 56 ~)
[d=63.701.625.176 h=7 m=52 s=56 f=~]
```

I think this has to do with how type gates fail when the input doesn't nest. For your input, when it gets to the `{s/@ud f/(list @ux}` part of the type (after having successfully filled in all preceding values), all input that remains is a `@ud`. That's an atom, not a cell like it still expects, so it throws its hand in the air and gives up.

**Comment by Fang-** [comment]
If you want to use the bunted type, with some values changed, the pattern is this:

```
> %*(. *tarp h 5, m 6)
[d=0 h=5 m=6 s=0 f=~]
```

**Comment by mikolajpp** [comment]
Nice! Closing then.
