### ISSUE TITLE
arc should just be called sur in the dojo

### ISSUE THREAD

**Issue by galenwp** [urbit/arvo#80]
If we call libraries `lib` then shouldn't we just call structures `sur`?  Not sure what an `arc` is, and don't really feel like I need to know.

**Comment by galenwp** [comment]
Based on a quick test a few find / replaces should do the trick.  Now using a dojo with `sur` and it seems to work.

Will wait on @cgyarvin and @philipcmonk.

**Comment by ohAitch** [comment]
+1

**Comment by cgyarvin** [comment]
Yeah I was going to change these, but right now just make them consistent.

**Comment by galenwp** [comment]
What would they change to?

**Comment by galenwp** [comment]
@cgyarvin if you don't have something to change them to then they're just going to be `lib` and `sur` as per https://github.com/urbit/arvo/pull/83

**Comment by Fang-** [comment]
#83, which fixes this, has been merged. This issue can be closed.
