### ISSUE TITLE
Code introspection - calling sloe on compiled cores

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#811]
Suppose I have a core:
```
=fancy-core
|%
   ++  arm-1  ...
   ++  arm-2  ...
    ...
--
```

I would like to be able to scan the core for arms (and arms in subcores possibly)
and keep those matching some criteria. I have found we have `++sloe`, however I can't call it properly. Neither wrapping it in a `vase` (which the sloe expect) or any other trick seems to work. 

I did look at our tester, but it seems to use ford; For this case we can assume fancy-core is already accessible.

**Comment by mikolajpp** [comment]
Ok, I think I got it.
The answer is 
```
> (sloe p:!>(a))
~[%literal]
```

**Comment by cgyarvin** [comment]
Yes or use the type structure directly
