### ISSUE TITLE
RC branch breaks urb

### ISSUE THREAD

**Issue by baudtack** [urbit/arvo#814]
Testing out the RC branch for urbit and arvo and urb seems to have borked 

```
dkerschner@swampert:~/Work/examples$ /home/dkerschner/build/urb/urb -d '(add 2 2)'
WARNING <module> 363 - No pier or port specified, looking on port 12321
{ ford: %core on /~zod/home/0/mar/lens/command/hoon failed:
  ford: %plan failed:
  ford: %ride failed to compute type:
  ford: %slim failed:
  -find.command
  /~zod/home/0/mar/lens/command/hoon::[5 9].[5 21]>
  /~zod/home/0/mar/lens/command/hoon::[5 5].[5 21]>
  /~zod/home/0/mar/lens/command/hoon::[5 1].[63 3]>
  /~zod/home/0/mar/lens/command/hoon::[4 1].[63 3]>
  /~zod/home/git-b4631e9438/sys/vane/ford:<[4.794 18].[4.794 59]>
}
while compiling %lens-command:
ford: no mark path from %json to %lens-command
ford: %cast %lens-command on [ship=~zod desk=%home] failed:
[%eyre-lens-fail %coup]

dkerschner@swampert:~/Work/examples$
```

**Comment by baudtack** [comment]
https://github.com/urbit/urbit/issues/1023

It's in both places now... so someone decide where it actually belongs.

**Comment by vvisigoth** [comment]
@belisarius222 @belisarius222 Do you guys have any insight on this? I'm not super familiar with the happy code path here.

**Comment by eglaysher** [comment]
This is a compile failure in the %/mar/lens/command/hoon file. I assume
that it just doesn't compile under new hoon anymore, either because of
organic dairy changes or because of Curtis' language changes.

—
~littel-ponnys
https://urbit.org

**Comment by belisarius222** [comment]
Yeah, I seem to recall lens getting borked sometime in the past few months.


—
~rovnys-ricfer
https://urbit.org

**Comment by vvisigoth** [comment]
This actually seems like a pretty good issue for you to take @baudtack , since it's either a matter of 1) unwinding Curtis' Hoon changes or 2) understanding how /sur imports have changed. Both would seem to be important to know from a docs POV (so that you can explain them to me!). Thoughts @belisarius222 @eglaysher ?

**Comment by baudtack** [comment]
I guess that's what i get for opening my stupid mouth. I'll look into it @vvisigoth and see what I can figure out.

**Comment by joemfb** [comment]
@baudtack, this should now be fixed on release-candidate. Can you confirm?

**Comment by baudtack** [comment]
This does fix the compile problem but the removal of ++he-lens and ++poke-lens-command from dojo.hoon still breaks urb. 

++he-lens is building a hoon dynamically that I don't understand but is not working in RC. I'm not sure how it even works in master since it's a %clsg that doesn't have a list... My current solution is to make this @belisarius222 or @eglaysher or @cgyarvin 's problem so I don't have to think about it anymore or my head will explode.

**Comment by belisarius222** [comment]
As for the `%clsg` in dojo, it does have a list, as evidenced by its last element:
https://github.com/urbit/arvo/blob/master/app/dojo.hoon#L1637

It looks like all that would be needed to reinstate `+he-lens` in dojo would be to touch up the hoons so they don't nest-fail, now that `+hoon` is different. I'll see what I can do.

**Comment by joemfb** [comment]
Note that there's a gall scry in that `%get-api` case. Not sure which of those commands `urb` requires.

**Comment by baudtack** [comment]
Thanks @belisarius222, when I make comments adjacent to "how did this ever work" I should probably just be ignored ;-p

**Comment by belisarius222** [comment]
Well, sometimes they didn't work ...

**Comment by belisarius222** [comment]
@joemfb Ok, so this might be blocked on getting asynchronous Gall scrys back into Ford-turbo. @vvisigoth maybe that issue should have its priority raised accordingly.

In the meantime, I'll see if I can at least get it to compile. If it compiles and dies somewhere in Ford, then we need asynchronous Gall scrys.

**Comment by ohAitch** [comment]
The primary users of gall scrys are going to be API generators, which are
actually asynchronous, and definitely not urb hello world s

Re: how did this ever work, esp for compile errors like "-find.", it can be
informative to check its CI status on a) master b) the last commit that
touched the file c) the first commit that touched the file(alternately, the
first commit that tested it)

If all of those say [%failed-known "uh eventually we'll get this to
build"], then you might have an actual longstanding problem…

**Comment by belisarius222** [comment]
@baudtack try with this code: https://github.com/urbit/arvo/pull/852

**Comment by baudtack** [comment]
Sent you a pr @belisarius222 to be added into yours that adds the last bit needed to make urb work again. And there was much rejoicing in the land of `hoon-mode.el` \o/

**Comment by baudtack** [comment]
Fixed in https://github.com/urbit/arvo/pull/853
