### ISSUE TITLE
[RC] static site generator relies on bilk:ford, can't find

### ISSUE THREAD

**Issue by vvisigoth** [urbit/arvo#818]
When i try to start the static site generator on release-candidate, I get

```
/~zod/home/git-d08108fb90/sys/vane/ford:<[4.794 18].[4.794 59]>
/~zod/home/0/app/static/hoon::[21 1].[125 3]>
/~zod/home/0/app/static/hoon::[27 3].[30 5]>
/~zod/home/0/app/static/hoon::[28 7].[28 41]>
/~zod/home/0/app/static/hoon::[28 24].[28 40]>
/~zod/home/0/app/static/hoon::[28 30].[28 39]>
-find.bilk
```

It appears that new ford doesn't have ++ bilk. Not sure what old bilk did. What do?

**Comment by vvisigoth** [comment]
@ixv @belisarius222 @eglaysher

**Comment by ixv** [comment]
yeah this isn't up to date, bilk is the old term for pair of beak and silk

**Comment by cgyarvin** [comment]
Obviously!

(In one of our 2019 cleanup passes, if not sooner, we need a general review
of naming.)

**Comment by vvisigoth** [comment]
But silk no longer exists ...

This is the tool that we'll be using for compiling docs, so this is not *not* urgent. Can one of @ixv @belisarius222 or @eglaysher take a look?

**Comment by ixv** [comment]
sure I will take care of it

**Comment by joemfb** [comment]
@ixv, once fixed, can you re-enable this in `%/app/test/hoon`?
