### ISSUE TITLE
[RC] crude: punted upon copying a large number of files into a pier

### ISSUE THREAD

**Issue by ixv** [urbit/arvo#826]
@belisarius222 @eglaysher 
I've got another error that looks very similar to https://github.com/urbit/arvo/issues/819 but slightly different.

I did the following things
- I copied around 600 files into a pier
- I see my ship succeed in syncing them
- I shut down my ship
- on restarting it I get this stack trace:
https://pastebin.com/fVMXsm5Q

subsequent restarts produces the same stack trace.

I can give you a ship that reproduces this.

**Comment by belisarius222** [comment]
Hm. The stack trace has a bunch of mentions of line 1671 in Ford. The most
recent release-candidate has this as that line:
https://github.com/urbit/arvo/blob/release-candidate/sys/vane/ford.hoon#L1671

Does that match the code that you're running? Seems like a strange place to
die.


—
~rovnys-ricfer
https://urbit.org

**Comment by ixv** [comment]
closed by https://github.com/urbit/arvo/pull/827
