### ISSUE TITLE
output is a top level name in hoon.hoon

### ISSUE THREAD

**Issue by baudtack** [urbit/arvo#831]
`output` used to be in `musk` but in the RC is now a top level name. This just bit me in the butt because I had also named something `output` in a library and name resolution order found it in someone else's hoon.hoon before it found it in my code. Maybe this could be changed to have a name that isn't going to repeatedly bite people for years to come.

**Comment by ohAitch** [comment]
(And hopefully a name resolution algorithm that isn't going to repeatedly
bite people for years to come; in the meantime, always import things
qualified, or ^?(ed) if you want to =, the contents of a single core)

**Comment by jtobin** [comment]
Closing this one as the linked issue captures the problem more generally.
