### ISSUE TITLE
[Sail] Escape '{' and '}' characters in Sail

### ISSUE THREAD

**Issue by c-johnson** [urbit/arvo#834]
In a sail context, I want to produce the following HTML:

`<a href="javascript:(function(){})()">Click!</a>`

In sail, curly brackets within strings denote interpolation: 

`;a(href "javascript:(function(){})()": Click!`

Which fails, since the expression is empty

Just looking for a way to escape the curly brackets. Raw tape interpolation in the dojo accepts the \ as a valid escape character, but still includes the \ in the resulting string

`> "foo \{<5>}"`
`"foo \{<5>}"`

**Comment by ohAitch** [comment]
You can `crip` it to view the cord version, which should be correct; dojo just escapes it in the tape printout, so the tape is like valid hoon to produce the same tape.

**Comment by c-johnson** [comment]
Thanks!

**Comment by ohAitch** [comment]
You can take this to its natural conclusion of `;a(href (trip 'javascript:(function(){})()')): Click!`, but it's probably overkill for a single brace :P
