### ISSUE TITLE
unable to render certain umd files in release-candidate

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#838]
I realized this morning I'd never tried to host the umd documentation files on a release-candidate ship.  After attempting it this morning I got the following result:

```
eyre: execute [%ay p=~.~zod q=~.0v6.pmcee.4kg0c.mvaeb.2cfau.j0lql ~]
ford: %bake %x-urb-elem on /~zod/home/0/web/docs/docs failed:
as-renderer
{/| failed: out of options}
as-mark
{ %alts: all options failed
  option
  { ford: %cast %x-urb-elem on [ship=~zod desk=%home] failed:
    ford: no mark path from %umd to %x-urb-elem
  }
}
```

**Comment by vvisigoth** [comment]
This almost certainly has to do with the fact that the root renderer has been changed for the benefit of landscape. Is that right, @ixv ?

**Comment by joshuareagan** [comment]
I tried the fix, and it sort of worked for some pages.  The rendering is pretty broken though, and the `;list;` portions don't seem to work.  I think we need some assistance from the interface team to get these docs working correctly.

**Comment by joshuareagan** [comment]
fwiw here is the repo that we want to get working:

https://github.com/urbit/docs/tree/2018-era-draft

I've been plopping these files under `/web/docs` to test them on a ship.
