### ISSUE TITLE
curl generator broken in release-candidate

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#845]
```
> +curl "http://www.google.com"
/~zod/home/0/gen/curl/hoon::[8 1].[14 20]>
/~zod/home/0/gen/curl/hoon::[9 1].[14 20]>
/~zod/home/0/gen/curl/hoon::[10 1].[14 20]>
/~zod/home/0/gen/curl/hoon::[10 11].[14 20]>
/~zod/home/0/gen/curl/hoon::[11 1].[14 20]>
/~zod/home/0/gen/curl/hoon::[12 1].[14 20]>
nest-fail
ford: %slim failed: 
ford: %ride failed to compute type:
ford: %plan failed: 
ford: %core on /~zod/home/0/gen/curl/hoon failed:
```

**Comment by joemfb** [comment]
`+auri:urlp` (ie, `+auri:de-purl:html` without lib/old-zuse) parses a `+tape` to a `+purl`.

**Comment by joshuareagan** [comment]
I made that change but got the same crash

**Comment by joemfb** [comment]
The point being that the input is parsed to a `+purl`, but the continuation expects an `+httr`. You'll need to accept a `+purl` in the continuation, and construct the `+httr` explicitly. My guess is this generator hasn't worked in quite awhile, but maybe I'm missing something ...

**Comment by joshuareagan** [comment]
It works on live master ships

**Comment by joemfb** [comment]
Oh, this is my bad -- `+sole-at` constructs an `+httr` from a `+purl`. I have nothing to offer without investigating further. Sorry for the misdirection!

**Comment by ohAitch** [comment]
Relatedly, can all the generators that don't outright hang ford be moved from `++skip-completely` to `++failing` in CI? (also "remove?" is not a valid reason for sth not to build: here it would be e.g. "generator library restructuring introduced type mismatch")

**Comment by ohAitch** [comment]
Looking slightly deeper into this, also the non-generators, all the things added in [the relevant commit](https://github.com/urbit/arvo/commit/47855b6#diff-6f3d736fdae3a47c80ff688a81310ec7R175) should produce in-band errors afaik.

**Comment by joemfb** [comment]
Point taken, @ohAitch. I've fixed up a bunch of these in #847, and moved the rest to `+failing`.

**Comment by joemfb** [comment]
@joshuareagan, my fix is now on release-candidate. Can you confirm?

**Comment by joshuareagan** [comment]
It's working great, thanks!
