### ISSUE TITLE
remove old-zuse

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#850]
it's been long enough ...

Discussion in #847

**Comment by rmariani** [comment]
What exactly is `old-zuse`?

**Comment by cgyarvin** [comment]
Compatibility shims for changed interfaces.  Do you want to go in and cut
them out (make everything that uses old-zuse use zuse)?

**Comment by ohAitch** [comment]
I don't see any discussion in #847, is it in the resolved diffs?

lib/old-zuse is a temporary compatibility shim with pre-refactoring four
letter names for a bunch of library functions, that was written to be
droppable at the top of unported code without having to rename everything.
(It's secondary purpose is a mapping *for the porting process* to be able
to look up the new names for pojo and friends; and for unported developers
who are used to writing the old names, tho I think the usefulness for that
has run its course)

Agree that an action that should be taken here(at some priority level etc)
is going through all the files that use it and making them work without it,
via mechanical renaming of stuff.

**Comment by rmariani** [comment]
> Compatibility shims for changed interfaces. Do you want to go in and cut them out (make everything that uses old-zuse use zuse)?

Yeah, I am tasked with making this change. Was just making sure that it was indeed this simple and that I wasn't missing something.

**Comment by ohAitch** [comment]
Should be pretty simple!

I think I at some point literally sed-ed old-zuse.hoon into a sed script,
but that ended up having unacceptably many false-positives; perhaps
something to retry now that we have CI set up(and running on *.hoon, at
least on master)

**Comment by joemfb** [comment]
I should've been more careful to link the context: https://github.com/urbit/arvo/pull/847#discussion_r223161474. See also #849. In short, there are  some strange edge cases in combining =, with ford imports. As an aside, it came up that old-zuse should probably be removed. I opened this issue as a reminder, part of an implicit release-candidate release checklist.

CI is enabled for every push to any branch on urbit/arvo. Just push your changes as you make them, and travis-ci will attempt to compile everything. You can monitor the builds here: https://travis-ci.org/urbit/arvo/builds

**Comment by ohAitch** [comment]
CI is enabled for every push, but as came up somewhat recently, on
release-candidate :test expects a (bigger)bunch of files not to compile
since they in fact don't; which will impede catching find-replace
mis-regexing that hits (only)those files.

**Comment by joemfb** [comment]
That's (mostly) fixed in #847.

**Comment by ohAitch** [comment]
Ah right, thank you again for doing that.

(And also the part where the non-terminally broken builds should now still
be attempted, which should prevent false negatives)

**Comment by rmariani** [comment]
The PR for this lives here: https://github.com/urbit/arvo/pull/867

**Comment by rmariani** [comment]
Closed because of this merge: https://github.com/urbit/arvo/pull/867
