### ISSUE TITLE
:twit .^ should have an authenitcated/unauthenticated distinction

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#88]
See commented-out `++user-to-path`, `++user-from-path`

**Comment by galenwp** [comment]
This must have been merged, no?  Do you still want to make this change, or should we plan to do it in a more general way?

**Comment by belisarius222** [comment]
@ohAitch is this still relevant? Possibly related to https://github.com/urbit/arvo/pull/415

**Comment by joemfb** [comment]
#415 doesn't change this one way or the other, it just fixes some regressions. But I think `:twit` needs some more design work, and this would certainly be relevant.

**Comment by joemfb** [comment]
#415 doesn't change this one way or the other, it just fixes some regressions. But I think `:twit` needs some more design work, and this would certainly be relevant.

**Comment by ohAitch** [comment]
:twit as a project is definitely hanging out in the "MAYFIX" category, but beyond that yeah this would be a useful distinction for using the app without a twitter account/API-key.
Re: title, the branch wasn't merged it's not one of mine so we probably won't find it, removed [unmerged] tag

**Comment by joemfb** [comment]
Closing, `:twit` was removed in #929
