### ISSUE TITLE
When do cores need an opaque payload?

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#903]
Right now we have a lot of cores throughout arvo and hoon.hoon that are being set to lead with `^?` and iron with `^|`.  It's not clear to me why this is so.  At least sometimes these runes have been used inappropriately, so that using the core in question required violating the type restrictions on lead and iron cores.  These restrictions haven't been enforced entirely, but that is changing now.  I've had to change some of these runes already.

Iron gates are useful for passing functions, and lead cores can be useful as delayed immutable computations, but why do we use the `^?` and `^|` runes so much?  I don't see the purpose in many cases, unless perhaps it's to hide the sample/context namespace to avoid collisions.  This doesn't seem to explain all uses, however.

I need to understand this better, because as I continue to fix variance enforcement I'm probably going to have to redo more of these cores, and I want to make sure I'm not breaking something else.

**Comment by cgyarvin** [comment]
Sometimes it is superfluous.  Other times it is for hiding a namespace.  Put it this way: there should never be a ^add.

**Comment by joshuareagan** [comment]
Makes sense.  I guess a few superfluous cases are no big deal, as long as people know what they're doing with `^?` and `^|`.  (Hint to all -- if the core has a sample that could, in principle, be written-to, use `^|` instead of `^?`.)

**Comment by joshuareagan** [comment]
In other discussions it was pointed out that opaque namespace doesn't have to be searched when it comes to name resolution.  Thus, hiding namespace by making it opaque can improve performance of name resolutions.  Makes sense to me.
