### ISSUE TITLE
mug hoon doesn't snip to 31 bits for pairs

### ISSUE THREAD

**Issue by rsaarelm** [urbit/arvo#93]
Try running `(mug [0 151])` using the hoon code, not the jet, you should get a value with bit 32 set.

I think [this line](https://github.com/urbit/arvo/blob/a1df9b2a5991bd0c288ff7acfe92d883b6b35207/arvo/hoon.hoon#L1091) should be

    ?. =(0 d) d

instead.

**Comment by cgyarvin** [comment]
Doh!  I'm amazed that that slipped in there.  Not using a rigorous jet
testing process, bad.

As I think others have noted, we want to switch from ++mug to ++mum.  (FNV
to Murmur32.)  This is a nontrivial change which needs to be coordinated
with the interpreter

It's reasonably impressive that you booted urbit.pill far enough to hit
this!  Much appreciated.

**Comment by ohAitch** [comment]
Doubly so since urbit.pill was being run as a nock formula :P

**Comment by cgyarvin** [comment]
It is a nock formula!  Of course, everything is...

**Comment by ohAitch** [comment]
My desire to concur on the basis of "yes exactly, I sad 'pill as
NockFormula' and not 'pill.into<NockFormula>()'" is probably rooted in
having read too much rust recently.

(Why /is/ the pill a cell of [kernel-formula arvo] though? Iirc you need
the formula to run for jet binding(see: jets not working in vanes until
reset), but that sounds like something you'd just get around with [10 [~
kernel-formula] 1 arvo])

**Comment by cgyarvin** [comment]
Jets bind from the bottom up, not the top down.  There is no way for a jet
node to know magically about its children.  They have to register
themselves.  The state created by this is evanescent (it's hint state) and
does not appear in urbit.pill.

That said, the whole init sequence is a botch and should work the way it
works in the paper.

**Comment by ohAitch** [comment]
This is why I'm proposing it be placed in a nock 10 :P

**Comment by rsaarelm** [comment]
I wouldn't have found the whole thing if I hadn't been trying to run urbit.pill as a formula. My eval run started crashing after I put in the mug jet, so I started checking whether the jet matches the nock code. Turns out the eval was crashing because it was finally getting to the point where doing `*[0 urbit.pill]` wasn't making sense anymore.
