### ISSUE TITLE
Multiple %info clay tasks in same event fail assert

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#953]
Sending multiple `%info` tasks to clay (from a gall app) in one event causes it to spew a continuous stream of crashes that look like the following:

```
crude: punted
crude: all delivery failed!
  [%swim-take-vane %c %wake ~]
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.083 3].[4.262 5]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.084 3].[4.262 5]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.102 3].[4.262 5]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.116 3].[4.262 5]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.224 5].[4.232 46]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.226 5].[4.232 46]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.227 5].[4.232 46]>
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.229 5].[4.232 46]>
  [ %mismatched-ducts
    %queued
    [ i=/g/~bud/use/send-txs/~bud/inn/write/~bud/home/~2018.12.20..00.27.13..940a/out-4/txt
        t
      ~[/g/~bud/use/dojo/~bud/inn/poke /g/~bud/use/hood/~bud/out/dojo/drum/phat/~bud/dojo /d //term/1]
    ]
    %timer
    [ i=/g/~bud/use/send-txs/~bud/inn/write/~bud/home/~2018.12.20..00.27.13..940a/out-21/txt
        t
      ~[/g/~bud/use/dojo/~bud/inn/poke /g/~bud/use/hood/~bud/out/dojo/drum/phat/~bud/dojo /d //term/1]
    ]
  ]
  /~zod/home/git-2bda0211a3/sys/vane/clay:<[4.230 5].[4.232 46]>
```

(Yes, I was running this on ~bud.)

For convenience, that's [this assert](https://github.com/urbit/arvo/blob/release-candidate/sys/vane/clay.hoon#L4115).  
That was put in during #807, which I approved. Guess it all catches up to you eventually, huh.

Commenting out that assert causes the file writes to go through one by one with behn timers in between, as expected.

**Comment by belisarius222** [comment]
I've seen this before, on a release-candidate from last week or so with new Behn, before a couple bug fixes. Have you tried this on current release-candidate? I recall confirming that this bug was squashed by https://github.com/urbit/arvo/pull/939

**Comment by jtobin** [comment]
Closing as per the above comment (and recent memory) it's not clear this one is still relevant.
