### ISSUE TITLE
Web dojo does not allow paste.

### ISSUE THREAD

**Issue by zaphar** [urbit/arvo#97]
Likely this is due to whatever input mechanism you are using. However as new people arrive they are going to want to paste examples from tutorials and docs into the /dojo and will be confused as to why it doesn't work.

This is either a bug or an enhancement request depending on how you want to categorize it :-)

**Comment by ohAitch** [comment]
Bug, or at least willfix

Technically this probably belongs in [urbit/sole](https://github.com/urbit/sole/issues), but the urbit bug report process shouldn't involve "figure out where the source code causing the problem lives", and "all external issues go on arvo" seems like a decent approximation.

**Comment by jtobin** [comment]
Closing as I'm not sure the feature being referred to is still actually a thing.

**Comment by ohAitch** [comment]
I mean, the file [web/dojo/hoon](https://github.com/urbit/arvo/blob/master/web/dojo.hoon) certainly still exists, if that doesn't work it should maybe be deleted?
