### ISSUE TITLE
<-:1> %fire-core -fire-span.{<1.abr {#t *} ...> {huge subject type}}

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#98]
While trying to pretty-print void is certainly an error, and even one I am somewhat thankful to the typesystem for catching, "fire-core" is not the most helpful of messages to print there.

**Comment by ohAitch** [comment]
As opposed to, like, a special case in `#>`/`#<` expansion for `%show-void`.

**Comment by ohAitch** [comment]
Hm, `|.((dec !!))` also fails to compile, with what is now a `fire-span`. Shouldn't that just short-circuit to an outer `%void`?

**Comment by galenwp** [comment]
Could you give the reproduction in the initial comment instead of the title?  This is confusing.

**Comment by cgyarvin** [comment]
Yes, fix this issue report please.  It might as well be an EKG core of
someone's brain while discovering this issue.  Whatever exactly the issue
is.

**Comment by ohAitch** [comment]
The issue is that the hoon expression `<-:1>` prints a very verbose and confusing type error, when the core problem is that you're trying to pretty-print a void value.

**Comment by jtobin** [comment]
Closing as I think this is too idiosyncratic to be useful more broadly.

**Comment by ohAitch** [comment]
"Too idiosyncratic" = "it does still reproduce"? Mildly disagree that "it takes multiple pages to print a 'trying to print a void type' error" is particularly an edge case(as opposed to the specific `<-:1>` minimal-example, which like, `<[!!]>` does the same thing I think), but won't insist on it

**Comment by joemfb** [comment]
Like #115, this is a bug in the current prettty-printer, likely fixed in the new printer, but that is not fully integrated.

**Comment by ohAitch** [comment]
Can we reopen these until then, and put "fixed #98, #115" in the message of whichever full-integration commit ends up resolving them? :3

**Comment by jtobin** [comment]
> Too idiosyncratic" = "it does still reproduce"?

I think the title/OP/initial comments are too idiosyncratic to be useful as-is -- i.e., it's just hard to tell what the issue is supposed to be, even if it's somehow associated with problematic behaviour (as echoed by other comments prior to mine).
